using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using AiCare.Domain;
using AiCare.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Xunit;
namespace AiCare.Tests;
[Collection("Postgres regression")]
public sealed class ComplaintGovernanceRegressionTests(PostgresRegressionFactory factory) : IClassFixture<PostgresRegressionFactory>
{
    [Fact]
    public async Task ComplaintDeadlinesTransitionsClosureAndFamilyHistoryAreGoverned()
    {
        await factory.EnsureClinicalSeedAsync(); var familyId = Guid.NewGuid(); var complaintId = Guid.NewGuid(); var familyName = $"complaint.family.{Guid.NewGuid():N}"; var coordinatorName = $"complaint.coordinator.{Guid.NewGuid():N}"; using (var scope = factory.Services.CreateScope()) { var db = scope.ServiceProvider.GetRequiredService<CareDbContext>(); db.FamilyMembers.Add(new FamilyMember(familyId, RegressionIds.ServiceUserId, "Complaint Family", $"{familyName}@aicare.local", "Daughter", "Portal", "Active", TenantDefaults.OrganizationId, TenantDefaults.BranchId)); db.AppUsers.AddRange(new AppUser(Guid.NewGuid(), familyName, $"{familyName}@aicare.local", PasswordHasher.HashPassword("Admin123!"), UserRole.FamilyMember, true, TenantDefaults.OrganizationId, TenantDefaults.BranchId, null, familyId), new AppUser(Guid.NewGuid(), coordinatorName, $"{coordinatorName}@aicare.local", PasswordHasher.HashPassword("Admin123!"), UserRole.CareCoordinator, true, TenantDefaults.OrganizationId, TenantDefaults.BranchId, null, null)); await db.SaveChangesAsync(); await db.Database.ExecuteSqlInterpolatedAsync($"""insert into family_feedback_cases(id,service_user_id,family_member_id,type,subject,description,priority,status,submitted_at,response_due_at,resolution,organization_id,branch_id) values({complaintId},{RegressionIds.ServiceUserId},{familyId},'Complaint','Missed communication','Family was not updated','High','Submitted',now(),{DateTimeOffset.UtcNow.AddHours(-1)},'',{TenantDefaults.OrganizationId},{TenantDefaults.BranchId})"""); }
        async Task<HttpClient> Login(string name) { var c = factory.CreateClient(); var r = await c.PostAsJsonAsync("/api/auth/login", new { userName = name, password = "Admin123!", mfaCode = (string?)null }); r.EnsureSuccessStatusCode(); c.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", (await r.Content.ReadFromJsonAsync<Login>())!.Token); return c; }
        var admin = await Login("admin"); var coordinator = await Login(coordinatorName); var family = await Login(familyName); var familyToken=new System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler().ReadJwtToken(family.DefaultRequestHeaders.Authorization!.Parameter);Assert.Contains(familyToken.Claims,x=>x.Type=="family_member_id"&&x.Value==familyId.ToString());
        var alertsResponse = await admin.GetAsync("/api/phase1/complaints/alerts"); Assert.True(alertsResponse.IsSuccessStatusCode, $"Alerts failed: {await alertsResponse.Content.ReadAsStringAsync()}"); var alerts = await alertsResponse.Content.ReadFromJsonAsync<Complaint[]>(); Assert.Contains(alerts!, x => x.Id == complaintId); Assert.Equal(HttpStatusCode.BadRequest, (await admin.PatchAsJsonAsync($"/api/phase1/complaints/{complaintId}/assign", new { assignedTo = "Lead", responseDueAt = DateTimeOffset.UtcNow.AddMinutes(-1) })).StatusCode); Assert.Equal(HttpStatusCode.NoContent, (await admin.PatchAsJsonAsync($"/api/phase1/complaints/{complaintId}/assign", new { assignedTo = "Complaint lead", responseDueAt = DateTimeOffset.UtcNow.AddDays(2) })).StatusCode);
        Assert.Equal(HttpStatusCode.NoContent, (await coordinator.PostAsJsonAsync($"/api/phase1/complaints/{complaintId}/transition", new { action = "Acknowledge" })).StatusCode); Assert.Equal(HttpStatusCode.NoContent, (await coordinator.PostAsJsonAsync($"/api/phase1/complaints/{complaintId}/transition", new { action = "StartReview" })).StatusCode); Assert.Equal(HttpStatusCode.BadRequest, (await coordinator.PostAsJsonAsync($"/api/phase1/complaints/{complaintId}/transition", new { action = "Respond", investigationSummary = "", responseText = "" })).StatusCode); Assert.Equal(HttpStatusCode.NoContent, (await coordinator.PostAsJsonAsync($"/api/phase1/complaints/{complaintId}/transition", new { action = "Respond", investigationSummary = "Records and staff reviewed", responseText = "We identified and corrected the communication failure." })).StatusCode); Assert.Equal(HttpStatusCode.NoContent, (await coordinator.PostAsJsonAsync($"/api/phase1/complaints/{complaintId}/transition", new { action = "Resolve", resolution = "New escalation procedure implemented" })).StatusCode); Assert.Equal(HttpStatusCode.Forbidden, (await coordinator.PostAsJsonAsync($"/api/phase1/complaints/{complaintId}/transition", new { action = "Close", closureSummary = "Coordinator close" })).StatusCode); Assert.Equal(HttpStatusCode.NoContent, (await admin.PostAsJsonAsync($"/api/phase1/complaints/{complaintId}/transition", new { action = "Close", closureSummary = "Response accepted and improvement verified" })).StatusCode);
        var mine = await family.GetFromJsonAsync<Complaint[]>($"/api/phase1/complaints/mine"); var item = Assert.Single(mine!); Assert.Equal("Closed", item.Status); Assert.Contains(item.History, x => x.EventType == "Respond"); Assert.DoesNotContain(item.History, x => x.EventType == "StartReview"); Assert.Equal(HttpStatusCode.NoContent, (await admin.PostAsJsonAsync($"/api/phase1/complaints/{complaintId}/transition", new { action = "Reopen", reason = "New evidence received" })).StatusCode);
    }
    private sealed record Login(string Token); private sealed record Event(string EventType); private sealed record Complaint(Guid Id, string Status, Event[] History);
}
