using System.Net;using System.Net.Http.Headers;using System.Net.Http.Json;using AiCare.Domain;using AiCare.Infrastructure;using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.DependencyInjection;using Xunit;
namespace AiCare.Tests;
[Collection("Postgres regression")]
public sealed class InvoiceRunGovernanceRegressionTests(PostgresRegressionFactory factory):IClassFixture<PostgresRegressionFactory>
{
 [Fact]public async Task RunIsFilteredIdempotentConcurrentSnapshotBasedAndRequiresReview()
 {await factory.EnsureClinicalSeedAsync();var person=Guid.NewGuid();var worker=Guid.NewGuid();var visit=Guid.NewGuid();var funder=Guid.NewGuid();var card=Guid.NewGuid();var version=Guid.NewGuid();var rule=Guid.NewGuid();var arrangement=Guid.NewGuid();var billable=Guid.NewGuid();var name=$"run.finance.{Guid.NewGuid():N}";using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<CareDbContext>();db.ServiceUsers.Add(new ServiceUser(person,"Run Person",new DateOnly(1950,1,1),"1","Care","Contact","",RiskLevel.Low,"Active","Address","None","None","Private","","","Independent","Independent","Verbal","Routine","Standard",TenantDefaults.OrganizationId,TenantDefaults.BranchId));db.CareWorkers.Add(new CareWorker(worker,"Run Worker","Care","Flexible",0,0,"Valid","Compliant","10",TenantDefaults.OrganizationId,TenantDefaults.BranchId));db.Visits.Add(new Visit(visit,person,worker,new DateTimeOffset(2044,4,2,9,0,0,TimeSpan.Zero),"Care",60,"Care",VisitStatus.Completed,null,null,null,null,null,null,TenantDefaults.OrganizationId,TenantDefaults.BranchId));db.AppUsers.Add(new AppUser(Guid.NewGuid(),name,$"{name}@aicare.local",PasswordHasher.HashPassword("Admin123!"),UserRole.BackOffice,true,TenantDefaults.OrganizationId,TenantDefaults.BranchId,null,null));await db.SaveChangesAsync();await db.Database.ExecuteSqlRawAsync("""insert into finance_funders(id,organization_id,branch_id,name,normalized_name,funder_type,payment_terms_days,default_invoice_frequency,currency,created_by,updated_by) values({0},{1},{2},'Run Council','RUN COUNCIL','LocalAuthority',30,'Monthly','GBP','test','test');insert into finance_rate_cards(id,organization_id,branch_id,name,service_type,currency,created_by,updated_by) values({3},{1},{2},'Run Rate','Care','GBP','test','test');insert into finance_rate_versions(id,rate_card_id,organization_id,branch_id,version,effective_from,effective_to,status,created_by) values({4},{3},{1},{2},1,'2044-04-01','2045-03-31','Active','test');insert into finance_rate_rules(id,rate_version_id,organization_id,rule_type,day_type,unit,unit_rate,created_by) values({5},{4},{1},'Standard','Any','Hour',40,'test');insert into funding_arrangements(id,service_user_id,organization_id,branch_id,funding_source,funder_name,authorized_hours_per_week,hourly_rate,valid_from,status,funder_id,rate_card_id,created_by) values({6},{7},{1},{2},'LocalAuthority','Run Council',10,0,'2044-04-01','Active',{0},{3},'test');insert into finance_billable_events(id,organization_id,branch_id,service_user_id,visit_id,funder_id,funding_arrangement_id,rate_version_id,rate_rule_id,service_date,quantity,unit,unit_rate,gross_amount,final_amount,currency,calculation_explanation,status,created_by,approved_at,approved_by) values({8},{1},{2},{7},{9},{0},{6},{4},{5},'2044-04-02',1,'Hour',40,40,40,'GBP','1 hour x GBP 40','Approved','test',now(),'test')""",funder,TenantDefaults.OrganizationId,TenantDefaults.BranchId,card,version,rule,arrangement,person,billable,visit);}
  var client=await Client(name);var preview=await client.PostAsJsonAsync("/api/phase1/finance/invoice-runs/preview",new{periodStart="2044-04-01",periodEnd="2044-04-30",funderId=funder,idempotencyKey="preview"});preview.EnsureSuccessStatusCode();Assert.Contains("\"totalAmount\":40",await preview.Content.ReadAsStringAsync());var requests=await Task.WhenAll(client.PostAsJsonAsync("/api/phase1/finance/invoice-runs",new{periodStart="2044-04-01",periodEnd="2044-04-30",funderId=funder,idempotencyKey="RUN-2044-04"}),client.PostAsJsonAsync("/api/phase1/finance/invoice-runs",new{periodStart="2044-04-01",periodEnd="2044-04-30",funderId=funder,idempotencyKey="RUN-2044-04"}));Assert.All(requests,x=>Assert.True(x.StatusCode is HttpStatusCode.Created or HttpStatusCode.OK));var history=await client.GetStringAsync($"/api/phase1/finance/invoice-runs?funderId={funder}");Assert.Contains("RUN",history,StringComparison.OrdinalIgnoreCase);using var verify=factory.Services.CreateScope();var db2=verify.ServiceProvider.GetRequiredService<CareDbContext>();Assert.Equal(1,await db2.Database.SqlQueryRaw<int>("select count(*)::int as \"Value\" from finance_invoice_lines where billable_event_id={0}",billable).SingleAsync());var invoice=await db2.Invoices.SingleAsync(x=>x.ServiceUserId==person);Assert.Equal(40m,invoice.Amount);Assert.Equal("Generated",invoice.Status);Assert.Equal(HttpStatusCode.Conflict,(await client.PostAsync($"/api/phase1/finance/invoices/{invoice.Id}/approve",null)).StatusCode);Assert.Equal(HttpStatusCode.OK,(await client.PostAsync($"/api/phase1/finance/invoices/{invoice.Id}/review",null)).StatusCode);Assert.Equal(HttpStatusCode.OK,(await client.PostAsync($"/api/phase1/finance/invoices/{invoice.Id}/approve",null)).StatusCode);
 }
 async Task<HttpClient>Client(string n){var c=factory.CreateClient();var r=await c.PostAsJsonAsync("/api/auth/login",new{userName=n,password="Admin123!",mfaCode=(string?)null});r.EnsureSuccessStatusCode();c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",(await r.Content.ReadFromJsonAsync<Login>())!.Token);return c;}sealed record Login(string Token);
}
