using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using AiCare.Domain;
using AiCare.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Npgsql;
using Xunit;

namespace AiCare.Tests;

[Collection("Postgres regression")]
public sealed class ProductionEmarRegressionTests(PostgresRegressionFactory factory):IClassFixture<PostgresRegressionFactory>
{
 [Fact]
 public async Task PrnWitnessStockOmissionEscalationAndImmutableHistoryAreEnforced()
 {
  await factory.EnsureClinicalSeedAsync();var person=Guid.NewGuid();var workerId=Guid.NewGuid();var medication=Guid.NewGuid();var first=Guid.NewGuid();var second=Guid.NewGuid();var omitted=Guid.NewGuid();var workerName=$"emar.worker.{Guid.NewGuid():N}";Guid adminId;
  using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<CareDbContext>();adminId=(await db.AppUsers.SingleAsync(x=>x.UserName=="admin")).Id;db.ServiceUsers.Add(new ServiceUser(person,"eMAR Person",new DateOnly(1950,1,1),"+10000000009","Medication support","Contact","",RiskLevel.Medium,"Active","Address","None","None","Private","Regression","","Independent","Independent","Verbal","None","Standard",TenantDefaults.OrganizationId,TenantDefaults.BranchId));db.CareWorkers.Add(new CareWorker(workerId,"eMAR Worker","Medication administration","Available",1,20,"Valid","Compliant","10 miles",TenantDefaults.OrganizationId,TenantDefaults.BranchId));db.AppUsers.Add(new AppUser(Guid.NewGuid(),workerName,$"{workerName}@aicare.local",PasswordHasher.HashPassword("Worker123!"),UserRole.CareWorker,true,TenantDefaults.OrganizationId,TenantDefaults.BranchId,workerId,null));db.Medications.Add(new Medication(medication,person,"Morphine solution","2.5 mg","Oral","PRN",true,"Pharmacy","None",TenantDefaults.OrganizationId,TenantDefaults.BranchId));db.MedicationAdministrationRecords.AddRange(Mar(first,medication,workerId),Mar(second,medication,workerId),Mar(omitted,medication,workerId));await db.SaveChangesAsync();}
  var admin=await Client("admin","Admin123!");var worker=await Client(workerName,"Worker123!");await StepUpTestGrants.GrantAsync(factory,admin,"medication");
  var profile=await admin.PutAsJsonAsync($"/api/phase1/medication-safety/medications/{medication}/profile",new{indication="Severe breakthrough pain",prescriber="Dr Safety",form="Solution",strength="10mg/5ml",startDate=DateTimeOffset.UtcNow.AddDays(-1),endDate=DateTimeOffset.UtcNow.AddMonths(1),doseWindowMinutes=60,maxPrnDoses24h=4,minPrnIntervalMinutes=240,prnIndication="Pain score 7 or above",prnEffectReviewMinutes=30,stockOnHand=5m,reorderLevel=2m,requiresWitness=true,lastReconciledAt=DateTimeOffset.UtcNow,reconciledBy="Medication lead"});Assert.Equal(HttpStatusCode.OK,profile.StatusCode);
  var selfWitness=await worker.PostAsJsonAsync($"/api/phase1/emar-safety/mar/{first}/record",new{outcome="Administered",occurredAt=DateTimeOffset.UtcNow,doseQuantity=1m,reasonCode="",reasonDetail="",prnIndication="Pain score 8",witnessUserId=(Guid?)null,overrideReason=""});Assert.Equal(HttpStatusCode.BadRequest,selfWitness.StatusCode);Assert.Contains("witness",await selfWitness.Content.ReadAsStringAsync(),StringComparison.OrdinalIgnoreCase);
  var administered=await worker.PostAsJsonAsync($"/api/phase1/emar-safety/mar/{first}/record",new{outcome="Administered",occurredAt=DateTimeOffset.UtcNow,doseQuantity=1m,reasonCode="",reasonDetail="",prnIndication="Pain score 8",witnessUserId=adminId,overrideReason=""});Assert.True(administered.StatusCode==HttpStatusCode.Created,$"Administration returned {administered.StatusCode}: {await administered.Content.ReadAsStringAsync()}");var ledgerId=(await administered.Content.ReadFromJsonAsync<Created>())!.Id;
  var tooSoon=await worker.PostAsJsonAsync($"/api/phase1/emar-safety/mar/{second}/record",new{outcome="Administered",occurredAt=DateTimeOffset.UtcNow.AddMinutes(30),doseQuantity=1m,reasonCode="",reasonDetail="",prnIndication="Pain persists",witnessUserId=adminId,overrideReason=""});Assert.Equal(HttpStatusCode.Conflict,tooSoon.StatusCode);Assert.Contains("interval",await tooSoon.Content.ReadAsStringAsync(),StringComparison.OrdinalIgnoreCase);
  var omission=await worker.PostAsJsonAsync($"/api/phase1/emar-safety/mar/{omitted}/record",new{outcome="Omitted",occurredAt=DateTimeOffset.UtcNow,doseQuantity=0m,reasonCode="NotAvailable",reasonDetail="Supply not delivered",prnIndication="",witnessUserId=adminId,overrideReason=""});Assert.Equal(HttpStatusCode.Created,omission.StatusCode);
  var history=await admin.GetStringAsync($"/api/phase1/emar-safety/mar/{first}/history");Assert.Contains("PRNEffectReview",history);Assert.Contains("stockAfter\":4",history);Assert.Contains("admin",history);
  var omissionHistory=await admin.GetStringAsync($"/api/phase1/emar-safety/mar/{omitted}/history");Assert.Contains("MissedDose",omissionHistory);Assert.Contains("Supply not delivered",omissionHistory);
  var effect=await worker.PostAsJsonAsync($"/api/phase1/emar-safety/mar/{first}/prn-effect",new{effect="Pain reduced from 8 to 3",observedAt=DateTimeOffset.UtcNow.AddMinutes(30)});Assert.Equal(HttpStatusCode.Created,effect.StatusCode);history=await admin.GetStringAsync($"/api/phase1/emar-safety/mar/{first}/history");Assert.Contains("Pain reduced from 8 to 3",history);Assert.Contains("Resolved",history);
  var missingWasteWitness=await admin.PostAsJsonAsync($"/api/phase1/emar-safety/medications/{medication}/stock",new{transactionType="Waste",quantity=1m,reference="W-1",reason="Spillage",witnessUserId=(Guid?)null});Assert.Equal(HttpStatusCode.BadRequest,missingWasteWitness.StatusCode);
  Guid witnessId;Guid escalationId;using(var operationsScope=factory.Services.CreateScope()){var operationsDb=operationsScope.ServiceProvider.GetRequiredService<CareDbContext>();witnessId=(await operationsDb.AppUsers.SingleAsync(x=>x.UserName==workerName)).Id;var connection=operationsDb.Database.GetDbConnection();await connection.OpenAsync();await using var command=connection.CreateCommand();command.CommandText="select id from emar_escalations where mar_record_id=@mar and escalation_type='MissedDose'";command.Parameters.Add(new NpgsqlParameter("mar",omitted));escalationId=(Guid)(await command.ExecuteScalarAsync())!;}
  var receipt=await admin.PostAsJsonAsync($"/api/phase1/emar-safety/medications/{medication}/stock",new{transactionType="Receipt",quantity=3m,reference="DEL-1",reason="Pharmacy delivery",witnessUserId=witnessId});Assert.Equal(HttpStatusCode.Created,receipt.StatusCode);Assert.Contains("balanceAfter",await receipt.Content.ReadAsStringAsync());
  var correction=await admin.PostAsJsonAsync($"/api/phase1/emar-safety/mar/{first}/corrections",new{correctsLedgerId=ledgerId,correctedOutcome="Administered - note corrected",reason="Original narrative omitted route confirmation"});Assert.Equal(HttpStatusCode.Created,correction.StatusCode);history=await admin.GetStringAsync($"/api/phase1/emar-safety/mar/{first}/history");Assert.Contains("Correction",history);Assert.Contains("Original narrative omitted route confirmation",history);
  Assert.Equal(HttpStatusCode.NoContent,(await admin.PostAsJsonAsync($"/api/phase1/emar-safety/escalations/{escalationId}/progress",new{action="Acknowledge",comment="Medication lead contacted"})).StatusCode);Assert.Equal(HttpStatusCode.NoContent,(await admin.PostAsJsonAsync($"/api/phase1/emar-safety/escalations/{escalationId}/progress",new{action="Resolve",comment="Replacement supply received"})).StatusCode);
  using var verify=factory.Services.CreateScope();var verifyDb=verify.ServiceProvider.GetRequiredService<CareDbContext>();var error=await Assert.ThrowsAsync<PostgresException>(()=>verifyDb.Database.ExecuteSqlRawAsync("update emar_ledger set reason_detail='changed' where id={0}",ledgerId));Assert.Contains("immutable",error.MessageText,StringComparison.OrdinalIgnoreCase);Assert.True(await verifyDb.AuditEvents.AnyAsync(x=>x.Action=="emar.governed_outcome_recorded"&&x.EntityId==first));
 }
 private static MedicationAdministrationRecord Mar(Guid id,Guid medication,Guid worker)=>new(id,medication,Guid.NewGuid(),worker,DateTimeOffset.UtcNow,null,"Scheduled","",TenantDefaults.OrganizationId,TenantDefaults.BranchId);
 private async Task<HttpClient> Client(string name,string password){var client=factory.CreateClient();var login=await client.PostAsJsonAsync("/api/auth/login",new{userName=name,password,mfaCode=(string?)null});login.EnsureSuccessStatusCode();client.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",(await login.Content.ReadFromJsonAsync<Login>())!.Token);return client;}
 private sealed record Login(string Token);private sealed record Created(Guid Id,string Outcome,decimal? StockAfter);
}
