using System.Net;using System.Net.Http.Headers;using System.Net.Http.Json;using System.Text.Json;using AiCare.Domain;using AiCare.Infrastructure;using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.DependencyInjection;using Xunit;
namespace AiCare.Tests;[Collection("Postgres regression")]public sealed class SessionSecurityRegressionTests(PostgresRegressionFactory factory):IClassFixture<PostgresRegressionFactory>
{
 [Fact]public async Task InventoryRevocationRotationReuseAndCredentialRevocationAreGoverned(){await factory.EnsureClinicalSeedAsync();var name=$"session.user.{Guid.NewGuid():N}";var otherName=$"session.other.{Guid.NewGuid():N}";Guid userId;using(var s=factory.Services.CreateScope()){var db=s.ServiceProvider.GetRequiredService<CareDbContext>();var user=User(name);userId=user.Id;db.AppUsers.AddRange(user,User(otherName));await db.SaveChangesAsync();}
 var first=await Login(name,"Laptop");var firstClient=Auth(first.Token);var second=await Login(name,"Phone");var secondClient=Auth(second.Token);var list=JsonDocument.Parse(await firstClient.GetStringAsync("/api/security/sessions")).RootElement;Assert.Equal(2,list.GetArrayLength());Assert.Contains(list.EnumerateArray(),x=>x.GetProperty("deviceName").GetString()=="Laptop"&&x.GetProperty("current").GetBoolean());Assert.DoesNotContain("user-agent",list.ToString(),StringComparison.OrdinalIgnoreCase);
 var refresh=await factory.CreateClient().PostAsJsonAsync("/api/auth/refresh-token",new{refreshToken=first.RefreshToken});Assert.Equal(HttpStatusCode.OK,refresh.StatusCode);var rotated=(await refresh.Content.ReadFromJsonAsync<LoginResponse>())!;Assert.NotEqual(first.RefreshToken,rotated.RefreshToken);var reuse=await factory.CreateClient().PostAsJsonAsync("/api/auth/refresh-token",new{refreshToken=first.RefreshToken});Assert.Equal(HttpStatusCode.Unauthorized,reuse.StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await firstClient.GetAsync("/api/auth/me")).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await Auth(rotated.Token).GetAsync("/api/auth/me")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await secondClient.GetAsync("/api/auth/me")).StatusCode);
 var sessions=JsonDocument.Parse(await secondClient.GetStringAsync("/api/security/sessions")).RootElement;var phone=sessions.EnumerateArray().Single(x=>x.GetProperty("deviceName").GetString()=="Phone").GetProperty("id").GetGuid();Assert.Equal(HttpStatusCode.BadRequest,(await secondClient.PostAsJsonAsync($"/api/security/sessions/{phone}/revoke",new{reason=""})).StatusCode);var outsider=Auth((await Login(otherName,"Other user's device")).Token);Assert.Equal(HttpStatusCode.NotFound,(await outsider.PostAsJsonAsync($"/api/security/sessions/{phone}/revoke",new{reason="Cross-user attempt"})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await secondClient.GetAsync("/api/auth/me")).StatusCode);Assert.Equal(HttpStatusCode.NoContent,(await secondClient.PostAsJsonAsync($"/api/security/sessions/{phone}/revoke",new{reason="User ended current phone session"})).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await secondClient.GetAsync("/api/auth/me")).StatusCode);
 var third=await Login(name,"Replacement browser");var thirdClient=Auth(third.Token);Assert.Equal(HttpStatusCode.NoContent,(await factory.CreateClient().PostAsJsonAsync("/api/auth/change-password",new{userName=name,currentPassword="Admin123!",newPassword="ChangedAdmin123!"})).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await thirdClient.GetAsync("/api/auth/me")).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await factory.CreateClient().PostAsJsonAsync("/api/auth/refresh-token",new{refreshToken=third.RefreshToken})).StatusCode);
 using var verify=factory.Services.CreateScope();var verifyDb=verify.ServiceProvider.GetRequiredService<CareDbContext>();Assert.True(await verifyDb.AuditEvents.AnyAsync(x=>x.Action=="security.session_revoked"));var compromised=await verifyDb.Database.SqlQuery<int>($"select count(*)::int as \"Value\" from auth_sessions where user_id={userId} and compromise_detected_at is not null").SingleAsync();Assert.True(compromised>0);await Assert.ThrowsAnyAsync<Exception>(()=>verifyDb.Database.ExecuteSqlInterpolatedAsync($"update auth_session_events set detail='changed' where user_id={userId}"));}
 private async Task<LoginResponse> Login(string name,string device){var c=factory.CreateClient();c.DefaultRequestHeaders.UserAgent.ParseAdd("AiCare-Regression/1.0");var r=await c.PostAsJsonAsync("/api/auth/login",new{userName=name,password="Admin123!",mfaCode=(string?)null,deviceName=device});r.EnsureSuccessStatusCode();return(await r.Content.ReadFromJsonAsync<LoginResponse>())!;}private HttpClient Auth(string token){var c=factory.CreateClient();c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",token);return c;}private static AppUser User(string name)=>new(Guid.NewGuid(),name,$"{name}@aicare.local",PasswordHasher.HashPassword("Admin123!"),UserRole.CareWorker,true,TenantDefaults.OrganizationId,TenantDefaults.BranchId);private sealed record LoginResponse(string Token,string RefreshToken,int ExpiresInMinutes,Guid SessionId);
}
