using System.Net;using System.Net.Http.Headers;using System.Net.Http.Json;using System.Text.Json;using AiCare.Domain;using AiCare.Infrastructure;using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.DependencyInjection;using Xunit;
namespace AiCare.Tests;
[Collection("Postgres regression")]
public sealed class WorkforceDevelopmentRegressionTests(PostgresRegressionFactory factory):IClassFixture<PostgresRegressionFactory>
{
 [Fact]public async Task RecruitmentTrainingAndProbationRequireEvidenceRolesAndWorkerScope()
 {await factory.EnsureClinicalSeedAsync();var worker=Guid.NewGuid();var other=Guid.NewGuid();var managerName=$"development.manager.{Guid.NewGuid():N}";var coordinatorName=$"development.coordinator.{Guid.NewGuid():N}";var workerName=$"development.worker.{Guid.NewGuid():N}";var otherName=$"development.other.{Guid.NewGuid():N}";using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<CareDbContext>();db.CareWorkers.AddRange(new CareWorker(worker,"Development Worker","Care","Flexible",0,0,"Valid","Pending","Local",TenantDefaults.OrganizationId,TenantDefaults.BranchId),new CareWorker(other,"Other Development Worker","Care","Flexible",0,0,"Valid","Pending","Local",TenantDefaults.OrganizationId,TenantDefaults.BranchId));db.AppUsers.AddRange(User(managerName,UserRole.CareManager),User(coordinatorName,UserRole.CareCoordinator),User(workerName,UserRole.CareWorker,worker),User(otherName,UserRole.CareWorker,other));await db.SaveChangesAsync();}
 async Task<HttpClient> Login(string name){var c=factory.CreateClient();var r=await c.PostAsJsonAsync("/api/auth/login",new{userName=name,password="Admin123!",mfaCode=(string?)null});r.EnsureSuccessStatusCode();c.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",(await r.Content.ReadFromJsonAsync<Login>())!.Token);return c;}var manager=await Login(managerName);var coordinator=await Login(coordinatorName);var self=await Login(workerName);var outsider=await Login(otherName);var root=$"/api/phase1/workforce-development/care-workers/{worker}";
 Assert.Equal(HttpStatusCode.OK,(await self.GetAsync(root)).StatusCode);Assert.Equal(HttpStatusCode.NotFound,(await outsider.GetAsync(root)).StatusCode);
 object recruitment(string status,string identity="Pending",string rtw="Pending",string dbs="Pending",string health="Pending",string onboarding="NotStarted",string reason="")=>new{status,applicationReference="APP-1",appliedAt=DateTimeOffset.UtcNow.AddDays(-5),interviewAt=(DateTimeOffset?)null,interviewOutcome="",identityStatus=identity,rightToWorkStatus=rtw,dbsStatus=dbs,healthDeclarationStatus=health,onboardingStatus=onboarding,owner="Recruitment lead",decisionReason=reason};
 Assert.Equal(HttpStatusCode.Forbidden,(await coordinator.PutAsJsonAsync($"{root}/recruitment",recruitment("Application"))).StatusCode);Assert.Equal(HttpStatusCode.BadRequest,(await manager.PutAsJsonAsync($"{root}/recruitment",recruitment("Cleared"))).StatusCode);Assert.Equal(HttpStatusCode.OK,(await manager.PutAsJsonAsync($"{root}/recruitment",recruitment("Onboarding","Verified","Verified","Verified","Cleared","InProgress"))).StatusCode);
 Assert.Equal(HttpStatusCode.BadRequest,(await coordinator.PostAsJsonAsync($"{root}/references",new{refereeName="Previous manager",relationship="Manager",requestedAt=DateTimeOffset.UtcNow.AddDays(-2),receivedAt=DateTimeOffset.UtcNow,outcome="Satisfactory",evidenceReference=""})).StatusCode);Assert.Equal(HttpStatusCode.Created,(await coordinator.PostAsJsonAsync($"{root}/references",new{refereeName="Previous manager",relationship="Manager",requestedAt=DateTimeOffset.UtcNow.AddDays(-2),receivedAt=DateTimeOffset.UtcNow,outcome="Satisfactory",evidenceReference="REF-1"})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await manager.PutAsJsonAsync($"{root}/recruitment",recruitment("Cleared","Verified","Verified","Verified","Cleared","Completed"))).StatusCode);
 var courseResponse=await manager.PostAsJsonAsync("/api/phase1/workforce-development/courses",new{code=$"SAFE-{Guid.NewGuid():N}",title="Safeguarding adults",category="Mandatory",provider="Internal",validityMonths=12,isMandatory=true,organizationWide=false,description="Annual mandatory course"});Assert.Equal(HttpStatusCode.Created,courseResponse.StatusCode);var course=JsonDocument.Parse(await courseResponse.Content.ReadAsStringAsync()).RootElement.GetProperty("id").GetGuid();Assert.Equal(HttpStatusCode.Forbidden,(await coordinator.PostAsJsonAsync("/api/phase1/workforce-development/courses",new{code="DENIED",title="Denied",category="Mandatory",provider="",validityMonths=12,isMandatory=true,organizationWide=false,description=""})).StatusCode);
 Assert.Equal(HttpStatusCode.BadRequest,(await coordinator.PostAsJsonAsync($"{root}/bookings",new{courseId=course,scheduledAt=DateTimeOffset.UtcNow.AddDays(-1)})).StatusCode);var bookingResponse=await coordinator.PostAsJsonAsync($"{root}/bookings",new{courseId=course,scheduledAt=DateTimeOffset.UtcNow.AddDays(1)});Assert.Equal(HttpStatusCode.Created,bookingResponse.StatusCode);var booking=JsonDocument.Parse(await bookingResponse.Content.ReadAsStringAsync()).RootElement.GetProperty("id").GetGuid();Assert.Equal(HttpStatusCode.Forbidden,(await coordinator.PostAsJsonAsync($"{root}/bookings/{booking}/complete",new{completedAt=DateTimeOffset.UtcNow,evidenceReference="CERT-1"})).StatusCode);Assert.Equal(HttpStatusCode.BadRequest,(await manager.PostAsJsonAsync($"{root}/bookings/{booking}/complete",new{completedAt=DateTimeOffset.UtcNow,evidenceReference=""})).StatusCode);Assert.Equal(HttpStatusCode.OK,(await manager.PostAsJsonAsync($"{root}/bookings/{booking}/complete",new{completedAt=DateTimeOffset.UtcNow,evidenceReference="CERT-1"})).StatusCode);Assert.Equal(HttpStatusCode.Conflict,(await manager.PostAsJsonAsync($"{root}/bookings/{booking}/complete",new{completedAt=DateTimeOffset.UtcNow,evidenceReference="CERT-2"})).StatusCode);
 Assert.Equal(HttpStatusCode.BadRequest,(await manager.PostAsJsonAsync($"{root}/probation",new{reviewAt=DateTimeOffset.UtcNow,outcome="Extended",objectives="Review",evidenceReference="PROB-1",extensionUntil=(DateOnly?)null})).StatusCode);Assert.Equal(HttpStatusCode.Created,(await manager.PostAsJsonAsync($"{root}/probation",new{reviewAt=DateTimeOffset.UtcNow,outcome="Passed",objectives="All objectives met",evidenceReference="PROB-1",extensionUntil=(DateOnly?)null})).StatusCode);
 var summary=JsonDocument.Parse(await (await manager.GetAsync($"/api/phase1/care-workers/{worker}/compliance/summary")).Content.ReadAsStringAsync()).RootElement;Assert.Contains(summary.GetProperty("training").EnumerateArray(),x=>x.GetProperty("certificateReference").GetString()=="CERT-1");var workspace=JsonDocument.Parse(await(await self.GetAsync(root)).Content.ReadAsStringAsync()).RootElement;Assert.Equal("Cleared",workspace.GetProperty("recruitment").GetProperty("status").GetString());Assert.Contains(workspace.GetProperty("bookings").EnumerateArray(),x=>x.GetProperty("status").GetString()=="Completed");using var verify=factory.Services.CreateScope();var dbVerify=verify.ServiceProvider.GetRequiredService<CareDbContext>();Assert.True(await dbVerify.AuditEvents.AnyAsync(x=>x.Action=="training.booking_completed"));
 }
 private static AppUser User(string name,UserRole role,Guid? worker=null)=>new(Guid.NewGuid(),name,$"{name}@aicare.local",PasswordHasher.HashPassword("Admin123!"),role,true,TenantDefaults.OrganizationId,TenantDefaults.BranchId,worker,null);private sealed record Login(string Token);
}
