using Microsoft.EntityFrameworkCore.Infrastructure;using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace AiCare.Infrastructure.Migrations;
[DbContext(typeof(CareDbContext))][Migration("20260831163000_AddWorkforceGovernanceRestrictions")]
public sealed class AddWorkforceGovernanceRestrictions:Migration
{
 protected override void Up(MigrationBuilder m)=>m.Sql("""
 create table if not exists worker_assignment_restrictions(id uuid primary key,care_worker_id uuid not null references "CareWorkers"("Id") on delete cascade,organization_id uuid not null,branch_id uuid not null,restriction_type text not null,skill text not null default '',status text not null default 'Active',reason text not null,evidence_reference text not null,starts_at timestamptz not null,ends_at timestamptz null,approved_by text not null,created_at timestamptz not null default now(),constraint ck_worker_restriction_status check(status in ('Active','Lifted','Expired')));create index if not exists ix_worker_restrictions_active on worker_assignment_restrictions(organization_id,care_worker_id,status,starts_at,ends_at);
 create table if not exists worker_medication_authorizations(id uuid primary key,care_worker_id uuid not null references "CareWorkers"("Id") on delete cascade,organization_id uuid not null,branch_id uuid not null,status text not null,scope text not null,evidence_reference text not null,authorized_at timestamptz not null,expires_at timestamptz null,authorized_by text not null,reason text not null default '',created_at timestamptz not null default now(),constraint ck_worker_med_authorization_status check(status in ('Authorized','Suspended','Revoked')));create index if not exists ix_worker_med_authorization on worker_medication_authorizations(organization_id,care_worker_id,created_at desc);
 create table if not exists workforce_policies(id uuid primary key,organization_id uuid not null,branch_id uuid null,title text not null,version text not null,content_reference text not null,published_at timestamptz not null,published_by text not null,requires_acknowledgement boolean not null default true,active boolean not null default true,constraint uq_workforce_policy_version unique(organization_id,title,version));
 create table if not exists workforce_policy_acknowledgements(id uuid primary key,policy_id uuid not null references workforce_policies(id) on delete restrict,care_worker_id uuid not null references "CareWorkers"("Id") on delete cascade,organization_id uuid not null,acknowledged_at timestamptz not null,acknowledged_by text not null,evidence_reference text not null,unique(policy_id,care_worker_id));
 create table if not exists worker_employee_relations_cases(id uuid primary key,care_worker_id uuid not null references "CareWorkers"("Id") on delete cascade,organization_id uuid not null,branch_id uuid not null,case_type text not null,status text not null default 'Open',summary text not null,owner text not null,outcome text not null default '',evidence_reference text not null,opened_at timestamptz not null,closed_at timestamptz null,created_by text not null,constraint ck_employee_case_type check(case_type in ('Disciplinary','Grievance')),constraint ck_employee_case_status check(status in ('Open','Investigating','Resolved','Closed')));
 create table if not exists worker_wellbeing_records(id uuid primary key,care_worker_id uuid not null references "CareWorkers"("Id") on delete cascade,organization_id uuid not null,branch_id uuid not null,recorded_at timestamptz not null,category text not null,summary text not null,action text not null,owner text not null,review_due date null,status text not null default 'Open',evidence_reference text not null,created_by text not null,constraint ck_wellbeing_status check(status in ('Open','Reviewed','Closed')));
 create table if not exists worker_self_service_requests(id uuid primary key,care_worker_id uuid not null references "CareWorkers"("Id") on delete cascade,organization_id uuid not null,branch_id uuid not null,request_type text not null,starts_at timestamptz null,ends_at timestamptz null,detail text not null,status text not null default 'Submitted',submitted_at timestamptz not null default now(),submitted_by text not null,decision text not null default '',decided_at timestamptz null,decided_by text not null default '',constraint ck_worker_self_service_type check(request_type in ('Leave','Sickness','AvailabilityChange','EmploymentDetailChange')),constraint ck_worker_self_service_status check(status in ('Submitted','Approved','Rejected','Cancelled')));create index if not exists ix_worker_self_service_requests on worker_self_service_requests(organization_id,care_worker_id,status,submitted_at desc);
 """);
 protected override void Down(MigrationBuilder m)=>m.Sql("""drop table if exists worker_self_service_requests;drop table if exists worker_wellbeing_records;drop table if exists worker_employee_relations_cases;drop table if exists workforce_policy_acknowledgements;drop table if exists workforce_policies;drop table if exists worker_medication_authorizations;drop table if exists worker_assignment_restrictions;""");
}
