using Microsoft.EntityFrameworkCore.Infrastructure;using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable
namespace AiCare.Infrastructure.Migrations;[DbContext(typeof(CareDbContext))][Migration("20260831223000_AddReportingDataGovernance")]public sealed class AddReportingDataGovernance:Migration{protected override void Up(MigrationBuilder m)=>m.Sql("""
create table if not exists governed_metric_definitions(id uuid primary key,organization_id uuid not null,branch_id uuid null,key text not null,version integer not null,name text not null,description text not null,calculation_key text not null,owner text not null,source_entities text not null,lineage text not null,effective_from timestamptz not null,effective_to timestamptz null,status text not null default 'Draft',approved_by text not null default '',approved_at timestamptz null,created_at timestamptz not null default now(),constraint uq_metric_version unique(organization_id,key,version),constraint ck_metric_status check(status in ('Draft','Approved','Retired')));create index if not exists ix_metric_current on governed_metric_definitions(organization_id,key,status,effective_from);
create table if not exists governed_report_catalogue(id uuid primary key,organization_id uuid not null,branch_id uuid null,name text not null,category text not null,description text not null,metric_keys text[] not null,allowed_roles text[] not null,field_profile text not null default 'AggregateOnly',active boolean not null default true,created_by text not null,created_at timestamptz not null default now());
create table if not exists governed_report_schedules(id uuid primary key,report_catalogue_id uuid not null references governed_report_catalogue(id) on delete restrict,organization_id uuid not null,branch_id uuid not null,frequency text not null,next_run_at timestamptz not null,enabled boolean not null default true,last_run_at timestamptz null,owner text not null,created_at timestamptz not null default now(),constraint ck_report_schedule_frequency check(frequency in ('Daily','Weekly','Monthly')));
create table if not exists governed_export_events(id uuid primary key,report_run_id uuid not null references report_runs(id) on delete restrict,organization_id uuid not null,branch_id uuid not null,exported_by text not null,role text not null,field_profile text not null,row_count integer not null,reason text not null,exported_at timestamptz not null default now());
create table if not exists data_quality_issues(id uuid primary key,organization_id uuid not null,branch_id uuid not null,rule_key text not null,entity_type text not null,entity_id uuid null,severity text not null,status text not null default 'Open',description text not null,owner text not null,detected_at timestamptz not null default now(),due_at timestamptz null,resolution text not null default '',resolved_at timestamptz null,constraint ck_data_quality_status check(status in ('Open','Investigating','Resolved','Accepted')));create index if not exists ix_data_quality_queue on data_quality_issues(organization_id,branch_id,status,severity,due_at);
""");protected override void Down(MigrationBuilder m)=>m.Sql("""drop table if exists data_quality_issues;drop table if exists governed_export_events;drop table if exists governed_report_schedules;drop table if exists governed_report_catalogue;drop table if exists governed_metric_definitions;""");}
