using System.Data.Common;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
namespace AiCare.Infrastructure;
public sealed class IntegrationJobWorker(IServiceScopeFactory scopes, ILogger<IntegrationJobWorker> logger) : BackgroundService
{
    protected override async Task ExecuteAsync(CancellationToken stop) { while (!stop.IsCancellationRequested) { try { await Cycle(stop); } catch (Exception e) { logger.LogError(e, "Integration worker cycle failed"); } await Task.Delay(TimeSpan.FromSeconds(5), stop); } }
    private async Task Cycle(CancellationToken token) { using var scope = scopes.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<CareDbContext>(); await db.Database.ExecuteSqlRawAsync("with due as (select id from integration_connectors where status='Active' and schedule_minutes>0 and (last_scheduled_at is null or last_scheduled_at+make_interval(mins=>schedule_minutes)<=now()) for update skip locked) insert into integration_jobs(id,connector_id,organization_id,branch_id,direction,status,resource_type,requested_by,options_json) select gen_random_uuid(),c.id,c.organization_id,c.branch_id,'Export','Pending','Scheduled','integration-worker','{{}}'::jsonb from integration_connectors c join due on due.id=c.id; update integration_connectors set last_scheduled_at=now() where schedule_minutes>0 and (last_scheduled_at is null or last_scheduled_at+make_interval(mins=>schedule_minutes)<=now())", token); var ids = new List<Guid>(); await using (var c = await Command(db, "select id from integration_jobs where status in ('Pending','Retrying') and (next_attempt_at is null or next_attempt_at<=now()) order by created_at for update skip locked limit 10", token)) { await using var r = await c.ExecuteReaderAsync(token); while (await r.ReadAsync(token)) ids.Add(r.GetGuid(0)); } foreach (var id in ids) await Process(db, id, token); }
    private static async Task Process(CareDbContext db, Guid id, CancellationToken token) { await Exec(db, "update integration_jobs set status='Processing',started_at=now(),attempt_count=attempt_count+1 where id=@id", id, token); Job job; await using (var c = await Command(db, "select direction,resource_type,options_json::text,attempt_count,max_attempts,organization_id,branch_id,connector_id from integration_jobs where id=@id", token, id)) { await using var r = await c.ExecuteReaderAsync(token); if (!await r.ReadAsync(token)) return; job = new(r.GetString(0), r.GetString(1), r.GetString(2), r.GetInt32(3), r.GetInt32(4), r.GetGuid(5), r.GetGuid(6), r.GetGuid(7)); } try { using var options = JsonDocument.Parse(job.Options); if (options.RootElement.TryGetProperty("simulateFailure", out var fail) && fail.GetBoolean()) throw new InvalidOperationException("Connector processing rejected the simulated payload."); var output = JsonSerializer.Serialize(new { job = id, job.Direction, job.ResourceType, processedAt = DateTimeOffset.UtcNow, records = Array.Empty<object>() }); await Exec(db, "update integration_jobs set status='Succeeded',record_count=0,output_json=cast(@output as jsonb),output_content_type='application/json',completed_at=now(),error_message=null where id=@id", id, token, ("output", output)); } catch (Exception e) { var dead = job.Attempt >= job.Max; var delay = Math.Min(60, (int)Math.Pow(2, job.Attempt)); await Exec(db, "update integration_jobs set status=@status,error_message=@error,next_attempt_at=case when @dead then null else now()+make_interval(mins=>@delay) end,completed_at=case when @dead then now() else null end where id=@id", id, token, ("status", dead ? "DeadLettered" : "Retrying"), ("error", e.Message), ("dead", dead), ("delay", delay)); await Exec(db, "insert into integration_sync_failures(id,connector_id,job_id,organization_id,branch_id,operation,error_message,payload_json,status,retry_count,next_retry_at,dead_lettered_at) values(gen_random_uuid(),@connector,@id,@organization,@branch,@operation,@error,'{}'::jsonb,@failure,@retry,case when @dead then null else now()+make_interval(mins=>@delay) end,case when @dead then now() else null end)", id, token, ("connector", job.Connector), ("organization", job.Organization), ("branch", job.Branch), ("operation", job.Direction), ("error", e.Message), ("failure", dead ? "DeadLettered" : "Pending"), ("retry", job.Attempt), ("dead", dead), ("delay", delay)); } }
    private static async Task<DbCommand> Command(CareDbContext db, string sql, CancellationToken token, Guid? id = null) { var cn = db.Database.GetDbConnection(); if (cn.State != System.Data.ConnectionState.Open) await cn.OpenAsync(token); var c = cn.CreateCommand(); c.CommandText = sql; if (id is not null) Add(c, "id", id); return c; }
    private static async Task Exec(CareDbContext db, string sql, Guid id, CancellationToken token, params (string Name, object Value)[] values) { await using var c = await Command(db, sql, token, id); foreach (var x in values) Add(c, x.Name, x.Value); await c.ExecuteNonQueryAsync(token); }
    private static void Add(DbCommand c, string n, object? v) { var p = c.CreateParameter(); p.ParameterName = n; p.Value = v ?? DBNull.Value; c.Parameters.Add(p); }
    private sealed record Job(string Direction, string ResourceType, string Options, int Attempt, int Max, Guid Organization, Guid Branch, Guid Connector);
}
