<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d8acc770-b5b6-4335-bf38-6eea5c79aa68</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AiCare.Application\AiCare.Application.csproj" />
    <ProjectReference Include="..\AiCare.Domain\AiCare.Domain.csproj" />
    <ProjectReference Include="..\AiCare.Infrastructure\AiCare.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
  </ItemGroup>
</Project>
