using System.Data;
using System.Data.Common;
using AiCare.Application;
using AiCare.Domain;
using AiCare.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;

namespace AiCare.Api;

[ApiController,Authorize(Roles="Administrator,BackOffice,CareManager")]
[Route("api/phase1/finance/billing")]
public sealed class BillingEngineController(CareDbContext db,ITenantContext tenant,ICurrentUserContext user):ControllerBase
{
 Guid Branch=>tenant.BranchId??TenantDefaults.BranchId;bool Manage=>user.IsAdministrator||user.IsBackOffice;
 [HttpPost("generate")]
 public async Task<IActionResult> Generate(GenerateBillableEventsRequest request,CancellationToken token)
 {
  if(!Manage)return Forbid();if(request.PeriodStart>=request.PeriodEnd)return BadRequest(new{message="Period start must be before period end."});
  return await db.Database.CreateExecutionStrategy().ExecuteAsync(async()=>{await using var tx=await db.Database.BeginTransactionAsync(token);await Exec("select pg_advisory_xact_lock(hashtextextended(@lock,0))",c=>Add(c,"lock",$"billing:{tenant.OrganizationId}"),token);
   var visits=await db.Visits.AsNoTracking().Where(v=>v.OrganizationId==tenant.OrganizationId&&(tenant.IsOrganizationWide||v.BranchId==tenant.BranchId)&&v.StartsAt>=request.PeriodStart&&v.StartsAt<request.PeriodEnd).OrderBy(v=>v.StartsAt).ToListAsync(token);var generated=0;var skipped=0;var exceptions=0;
   foreach(var visit in visits){if(await Scalar("select count(*) from finance_billable_events where organization_id=@organization and visit_id=@visit",c=>Add(c,"visit",visit.Id),token)>0){skipped++;continue;}if(visit.Status!=VisitStatus.Completed||visit.DurationMinutes<=0){exceptions+=await Exception(visit,"VISIT_NOT_ELIGIBLE","Visit must be completed with a positive duration.",token);continue;}
    var matches=await Query("""select a.id,a.funder_id,a.rate_card_id,f.currency from funding_arrangements a join finance_funders f on f.id=a.funder_id where a.organization_id=@organization and a.service_user_id=@person and a.status='Active' and a.valid_from<=@service and (a.valid_to is null or a.valid_to>=@service) order by case a.allocation_rule when 'Primary' then 0 else 1 end,a.valid_from desc""",c=>{Add(c,"person",visit.ServiceUserId);Add(c,"service",visit.StartsAt);},r=>new FundingMatch(r.GetGuid(0),r.GetGuid(1),r.IsDBNull(2)?null:r.GetGuid(2),r.GetString(3).Trim()),token);
    if(matches.Count==0){exceptions+=await Exception(visit,"MISSING_FUNDING","No effective funding arrangement exists for the service date.",token);continue;}if(matches.Count(x=>x.RateCardId is not null)>1){exceptions+=await Exception(visit,"CONFLICTING_FUNDING","Multiple effective funding arrangements require review.",token);continue;}var funding=matches[0];if(funding.RateCardId is null){exceptions+=await Exception(visit,"MISSING_RATE_CARD","Funding arrangement has no rate card.",token);continue;}
    var day=visit.StartsAt.DayOfWeek is DayOfWeek.Saturday or DayOfWeek.Sunday?"Weekend":"Weekday";var rates=await Query("""select v.id,r.id,r.unit,r.unit_rate,r.minimum_quantity,v.version from finance_rate_versions v join finance_rate_rules r on r.rate_version_id=v.id where v.organization_id=@organization and v.rate_card_id=@card and v.status='Active' and v.effective_from<=@date and (v.effective_to is null or v.effective_to>=@date) and r.day_type in (@day,'Any') order by case when r.day_type=@day then 0 else 1 end,r.priority desc limit 2""",c=>{Add(c,"card",funding.RateCardId);Add(c,"date",DateOnly.FromDateTime(visit.StartsAt.UtcDateTime));Add(c,"day",day);},r=>new RateMatch(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetDecimal(3),r.GetDecimal(4),r.GetInt32(5)),token);
    if(rates.Count==0){exceptions+=await Exception(visit,"MISSING_RATE","No effective rate rule matches this visit.",token);continue;}var rate=rates[0];var raw=rate.Unit=="Visit"?1m:Math.Round(visit.DurationMinutes/60m,2,MidpointRounding.AwayFromZero);var quantity=Math.Max(raw,rate.Minimum);var gross=Math.Round(quantity*rate.Rate,2,MidpointRounding.AwayFromZero);var id=Guid.NewGuid();var explanation=$"{quantity:0.##} {rate.Unit.ToLowerInvariant()} × {funding.Currency} {rate.Rate:0.0000}; {day} rule; rate version {rate.Version}; rounded to 2 decimals.";
    await Exec("""insert into finance_billable_events(id,organization_id,branch_id,service_user_id,visit_id,funder_id,funding_arrangement_id,rate_version_id,rate_rule_id,service_date,quantity,unit,unit_rate,gross_amount,final_amount,currency,calculation_explanation,status,created_by) values(@id,@organization,@visitBranch,@person,@visit,@funder,@funding,@version,@rule,@date,@quantity,@unit,@rate,@gross,@gross,@currency,@explanation,'Validated',@actor)""",c=>{Add(c,"id",id);Add(c,"visitBranch",visit.BranchId??Branch);Add(c,"person",visit.ServiceUserId);Add(c,"visit",visit.Id);Add(c,"funder",funding.FunderId);Add(c,"funding",funding.Id);Add(c,"version",rate.VersionId);Add(c,"rule",rate.RuleId);Add(c,"date",DateOnly.FromDateTime(visit.StartsAt.UtcDateTime));Add(c,"quantity",quantity);Add(c,"unit",rate.Unit);Add(c,"rate",rate.Rate);Add(c,"gross",gross);Add(c,"currency",funding.Currency);Add(c,"explanation",explanation);},token);generated++;}
   Audit("BILLABLE_EVENTS_GENERATED","BillableEvent",null);await db.SaveChangesAsync(token);await tx.CommitAsync(token);return Ok(new{examined=visits.Count,generated,skipped,exceptions});});
 }
 [HttpGet("events")]
 public async Task<IActionResult> Events([FromQuery]string? status,CancellationToken token)=>Ok(await Query("""select e.id,e.visit_id,e.service_user_id,e.service_date,e.quantity,e.unit,e.unit_rate,e.gross_amount,e.adjustment_amount,e.final_amount,e.currency,e.calculation_explanation,e.status,f.name from finance_billable_events e join finance_funders f on f.id=e.funder_id where e.organization_id=@organization and (@wide or e.branch_id=@branch) and (coalesce(@status,'')='' or e.status=@status) order by e.service_date desc,e.created_at desc""",c=>Add(c,"status",status??""),r=>new{id=r.GetGuid(0),visitId=r.GetGuid(1),serviceUserId=r.GetGuid(2),serviceDate=r.GetFieldValue<DateOnly>(3),quantity=r.GetDecimal(4),unit=r.GetString(5),unitRate=r.GetDecimal(6),grossAmount=r.GetDecimal(7),adjustmentAmount=r.GetDecimal(8),finalAmount=r.GetDecimal(9),currency=r.GetString(10).Trim(),calculationExplanation=r.GetString(11),status=r.GetString(12),funderName=r.GetString(13)},token));
 [HttpGet("exceptions")]
 public async Task<IActionResult> Exceptions(CancellationToken token)=>Ok(await Query("select id,visit_id,service_user_id,exception_code,message,status,created_at from finance_billing_exceptions where organization_id=@organization and (@wide or branch_id=@branch) order by status,created_at desc",_=>{},r=>new{id=r.GetGuid(0),visitId=r.GetGuid(1),serviceUserId=r.GetGuid(2),code=r.GetString(3),message=r.GetString(4),status=r.GetString(5),createdAt=r.GetFieldValue<DateTimeOffset>(6)},token));
 [HttpPost("events/{id:guid}/approve")]
 public async Task<IActionResult> Approve(Guid id,CancellationToken token){if(!Manage)return Forbid();var changed=await Exec("update finance_billable_events set status='Approved',approved_at=now(),approved_by=@actor,revision=revision+1 where id=@id and organization_id=@organization and (@wide or branch_id=@branch) and status='Validated'",c=>Add(c,"id",id),token);if(changed==0)return Conflict(new{message="Only validated billable events can be approved."});Audit("BILLABLE_EVENT_APPROVED","BillableEvent",id);await db.SaveChangesAsync(token);return NoContent();}
[HttpPost("events/{id:guid}/adjust")]
public async Task<IActionResult> Adjust(Guid id,AdjustBillableEventRequest request,CancellationToken token){if(!Manage)return Forbid();if(request.AdjustmentAmount==0||string.IsNullOrWhiteSpace(request.Reason))return BadRequest(new{message="A non-zero adjustment and reason are required."});var changed=await Exec("update finance_billable_events set adjustment_amount=@amount,final_amount=gross_amount+@amount,adjustment_reason=@reason,revision=revision+1 where id=@id and organization_id=@organization and (@wide or branch_id=@branch) and status in ('Pending','Validated') and gross_amount+@amount>=0",c=>{Add(c,"id",id);Add(c,"amount",request.AdjustmentAmount);Add(c,"reason",request.Reason.Trim());},token);if(changed==0)return Conflict(new{message="Event cannot be adjusted in its current state or adjustment makes the total negative."});Audit("BILLABLE_EVENT_ADJUSTED","BillableEvent",id);await db.SaveChangesAsync(token);return NoContent();}
 [HttpPost("events/{id:guid}/reject")]
 public async Task<IActionResult> Reject(Guid id,BillingDecisionRequest request,CancellationToken token){if(!Manage)return Forbid();if(string.IsNullOrWhiteSpace(request.Reason))return BadRequest(new{message="A rejection reason is required."});var changed=await Exec("update finance_billable_events set status='Rejected',adjustment_reason=@reason,revision=revision+1 where id=@id and organization_id=@organization and (@wide or branch_id=@branch) and status in ('Pending','Validated')",c=>{Add(c,"id",id);Add(c,"reason",request.Reason.Trim());},token);if(changed==0)return Conflict(new{message="Event cannot be rejected in its current state."});Audit("BILLABLE_EVENT_REJECTED","BillableEvent",id);await db.SaveChangesAsync(token);return NoContent();}
 [HttpPost("exceptions/{id:guid}/resolve")]
 public async Task<IActionResult> ResolveException(Guid id,BillingDecisionRequest request,CancellationToken token){if(!Manage)return Forbid();if(string.IsNullOrWhiteSpace(request.Reason))return BadRequest(new{message="A resolution is required."});var changed=await Exec("update finance_billing_exceptions set status='Resolved',resolved_at=now(),resolved_by=@actor,resolution=@reason where id=@id and organization_id=@organization and (@wide or branch_id=@branch) and status='Open'",c=>{Add(c,"id",id);Add(c,"reason",request.Reason.Trim());},token);if(changed==0)return Conflict(new{message="Only open exceptions can be resolved."});Audit("BILLING_EXCEPTION_RESOLVED","BillingException",id);await db.SaveChangesAsync(token);return NoContent();}
 async Task<int> Exception(Visit visit,string code,string message,CancellationToken token)=>await Exec("insert into finance_billing_exceptions(id,organization_id,branch_id,visit_id,service_user_id,exception_code,message) values(@id,@organization,@visitBranch,@visit,@person,@code,@message) on conflict do nothing",c=>{Add(c,"id",Guid.NewGuid());Add(c,"visitBranch",visit.BranchId??Branch);Add(c,"visit",visit.Id);Add(c,"person",visit.ServiceUserId);Add(c,"code",code);Add(c,"message",message);},token);
 async Task<int> Scalar(string sql,Action<DbCommand> bind,CancellationToken t){await using var c=await Command(sql,t);bind(c);return Convert.ToInt32(await c.ExecuteScalarAsync(t));}async Task<int> Exec(string sql,Action<DbCommand> bind,CancellationToken t){await using var c=await Command(sql,t);bind(c);return await c.ExecuteNonQueryAsync(t);}async Task<List<T>> Query<T>(string sql,Action<DbCommand> bind,Func<DbDataReader,T> map,CancellationToken t){var a=new List<T>();await using var c=await Command(sql,t);bind(c);await using var r=await c.ExecuteReaderAsync(t);while(await r.ReadAsync(t))a.Add(map(r));return a;}async Task<DbCommand> Command(string sql,CancellationToken t){var cn=db.Database.GetDbConnection();if(cn.State!=ConnectionState.Open)await cn.OpenAsync(t);var c=cn.CreateCommand();c.Transaction=db.Database.CurrentTransaction?.GetDbTransaction();c.CommandText=sql;Add(c,"organization",tenant.OrganizationId);Add(c,"branch",Branch);Add(c,"wide",tenant.IsOrganizationWide);Add(c,"actor",user.UserName);return c;}static void Add(DbCommand c,string n,object? v){if(c.Parameters.Contains(n))return;var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}void Audit(string action,string entity,Guid? id)=>db.AuditEvents.Add(new AuditEvent(Guid.NewGuid(),action,user.UserName,entity,id,DateTimeOffset.UtcNow,tenant.OrganizationId,Branch));
 sealed record FundingMatch(Guid Id,Guid FunderId,Guid? RateCardId,string Currency);sealed record RateMatch(Guid VersionId,Guid RuleId,string Unit,decimal Rate,decimal Minimum,int Version);
}
public sealed record GenerateBillableEventsRequest(DateTimeOffset PeriodStart,DateTimeOffset PeriodEnd);
public sealed record AdjustBillableEventRequest(decimal AdjustmentAmount,string Reason);
public sealed record BillingDecisionRequest(string Reason);
