using System.Data.Common;
using AiCare.Application;
using AiCare.Domain;
using AiCare.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AiCare.Api;

[ApiController]
[Authorize(Roles="CareCoordinator,CareManager,Administrator")]
[Route("api/phase1/service-users/{personId:guid}/governance")]
public sealed class CapacityAuthorityController(CareDbContext db,ITenantContext tenant,ICurrentUserContext user):ControllerBase
{
 [HttpGet]
 public async Task<IActionResult> Get(Guid personId,CancellationToken token){if(!await CanAccess(personId,token))return NotFound();return Ok(new{capacity=await Capacity(personId,token),bestInterests=await BestInterests(personId,token),authorities=await Authorities(personId,token)});}

 [HttpPost("capacity")]
 public async Task<IActionResult> RecordCapacity(Guid personId,CapacityDecisionRequest request,CancellationToken token)
 {
  if(!await CanAccess(personId,token))return NotFound();if(Missing(request.DecisionContext)||Missing(request.AssessmentReason)||Missing(request.AssessorName)||Missing(request.AssessorRole)||Missing(request.SupportProvided))return BadRequest(new{message="Decision context, reason, support and assessor details are required."});
  var outcome=request.CanUnderstand&&request.CanRetain&&request.CanUseOrWeigh&&request.CanCommunicate?"HasCapacity":"LacksCapacity";var previous=await CurrentCapacity(personId,request.DecisionContext,token);var id=Guid.NewGuid();var version=(previous?.Version??0)+1;
  await Exec("update capacity_decisions set status='Superseded' where id=@previous and organization_id=@organization;insert into capacity_decisions(id,service_user_id,organization_id,branch_id,decision_context,assessment_reason,outcome,can_understand,can_retain,can_use_or_weigh,can_communicate,support_provided,assessor_name,assessor_role,evidence_reference,assessed_at,review_due_at,status,version,supersedes_id,best_interest_required,created_by) values(@id,@person,@organization,@branch,@context,@reason,@outcome,@understand,@retain,@weigh,@communicate,@support,@assessor,@role,@evidence,@assessed,@review,'Current',@version,@previous,@best,@actor)",personId,id,c=>{Add(c,"previous",previous?.Id);Add(c,"context",request.DecisionContext.Trim());Add(c,"reason",request.AssessmentReason.Trim());Add(c,"outcome",outcome);Add(c,"understand",request.CanUnderstand);Add(c,"retain",request.CanRetain);Add(c,"weigh",request.CanUseOrWeigh);Add(c,"communicate",request.CanCommunicate);Add(c,"support",request.SupportProvided.Trim());Add(c,"assessor",request.AssessorName.Trim());Add(c,"role",request.AssessorRole.Trim());Add(c,"evidence",request.EvidenceReference?.Trim()??"");Add(c,"assessed",request.AssessedAt??DateTimeOffset.UtcNow);Add(c,"review",request.ReviewDueAt);Add(c,"version",version);Add(c,"best",outcome=="LacksCapacity");},token);
  Audit("capacity_decision.recorded","CapacityDecision",id);await db.SaveChangesAsync(token);return CreatedAtAction(nameof(Get),new{personId},new{id,outcome,version});
 }

 [HttpPost("capacity/{capacityId:guid}/best-interest")]
 [Authorize(Roles="CareManager,Administrator")]
 public async Task<IActionResult> RecordBestInterest(Guid personId,Guid capacityId,BestInterestRequest request,CancellationToken token)
 {
  if(!await CanAccess(personId,token))return NotFound();var valid=await Scalar("select count(*) from capacity_decisions where id=@target and service_user_id=@person and organization_id=@organization and branch_id=@branch and status='Current' and outcome='LacksCapacity'",personId,capacityId,token);if(valid==0)return Conflict(new{message="A current lacks-capacity decision is required."});
  if(Missing(request.Decision)||Missing(request.OptionsConsidered)||Missing(request.ConsultedPeople)||Missing(request.PersonWishes)||Missing(request.RisksAndBenefits)||Missing(request.LeastRestrictiveReason)||Missing(request.DecisionMaker))return BadRequest(new{message="Complete best-interest evidence is required."});var id=Guid.NewGuid();
  try{await Exec("insert into best_interest_decisions(id,capacity_decision_id,service_user_id,organization_id,branch_id,decision,options_considered,consulted_people,person_wishes,risks_and_benefits,least_restrictive_reason,decision_maker,decided_at,review_due_at,created_by) values(@id,@target,@person,@organization,@branch,@decision,@options,@consulted,@wishes,@risks,@least,@maker,@decided,@review,@actor)",personId,id,c=>{Add(c,"target",capacityId);Add(c,"decision",request.Decision.Trim());Add(c,"options",request.OptionsConsidered.Trim());Add(c,"consulted",request.ConsultedPeople.Trim());Add(c,"wishes",request.PersonWishes.Trim());Add(c,"risks",request.RisksAndBenefits.Trim());Add(c,"least",request.LeastRestrictiveReason.Trim());Add(c,"maker",request.DecisionMaker.Trim());Add(c,"decided",request.DecidedAt??DateTimeOffset.UtcNow);Add(c,"review",request.ReviewDueAt);},token);}catch(DbException){return Conflict(new{message="A current best-interest decision already exists for this assessment."});}
  Audit("best_interest_decision.recorded","BestInterestDecision",id);await db.SaveChangesAsync(token);return CreatedAtAction(nameof(Get),new{personId},new{id});
 }

 [HttpPost("authorities")]
 public async Task<IActionResult> RecordAuthority(Guid personId,AuthorityRequest request,CancellationToken token)
 {
  if(!await CanAccess(personId,token))return NotFound();if(Missing(request.AuthorityType)||Missing(request.HolderName)||Missing(request.Scope)||request.VerificationStatus!="Verified"||Missing(request.VerificationReference))return BadRequest(new{message="Verified authority type, holder, scope, and evidence are required."});if(request.ValidUntil is not null&&request.ValidUntil<=request.ValidFrom)return BadRequest(new{message="Authority expiry must follow its start."});
  var previous=await CurrentAuthority(personId,request.AuthorityType,request.HolderName,token);var id=Guid.NewGuid();var version=(previous?.Version??0)+1;await Exec("update authority_records set status='Superseded' where id=@previous and organization_id=@organization;insert into authority_records(id,service_user_id,organization_id,branch_id,authority_type,holder_name,holder_relationship,scope,verification_status,verification_reference,valid_from,valid_until,status,version,supersedes_id,created_by) values(@id,@person,@organization,@branch,@type,@holder,@relationship,@scope,'Verified',@evidence,@from,@until,'Active',@version,@previous,@actor)",personId,id,c=>{Add(c,"previous",previous?.Id);Add(c,"type",request.AuthorityType.Trim());Add(c,"holder",request.HolderName.Trim());Add(c,"relationship",request.HolderRelationship?.Trim()??"");Add(c,"scope",request.Scope.Trim());Add(c,"evidence",request.VerificationReference.Trim());Add(c,"from",request.ValidFrom);Add(c,"until",request.ValidUntil);Add(c,"version",version);},token);Audit("authority_record.recorded","AuthorityRecord",id);await db.SaveChangesAsync(token);return CreatedAtAction(nameof(Get),new{personId},new{id,version});
 }

 [HttpPost("authorities/{id:guid}/revoke")]
 public async Task<IActionResult> Revoke(Guid personId,Guid id,RevokeAuthorityRequest request,CancellationToken token){if(!await CanAccess(personId,token))return NotFound();if(Missing(request.Reason))return BadRequest(new{message="Revocation reason is required."});var changed=await Exec("update authority_records set status='Revoked',revoked_at=now(),revocation_reason=@reason where id=@id and service_user_id=@person and organization_id=@organization and branch_id=@branch and status='Active'",personId,id,c=>Add(c,"reason",request.Reason.Trim()),token);if(changed==0)return NotFound();Audit("authority_record.revoked","AuthorityRecord",id);await db.SaveChangesAsync(token);return NoContent();}

 private async Task<bool> CanAccess(Guid id,CancellationToken token){var person=await db.ServiceUsers.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.OrganizationId==tenant.OrganizationId,token);return person is not null&&tenant.CanAccess(person.OrganizationId,person.BranchId);}
 private Task<List<CapacityResponse>> Capacity(Guid person,CancellationToken token)=>Query("select id,decision_context,assessment_reason,outcome,can_understand,can_retain,can_use_or_weigh,can_communicate,support_provided,assessor_name,assessor_role,evidence_reference,assessed_at,review_due_at,status,version,supersedes_id,best_interest_required from capacity_decisions where service_user_id=@person and organization_id=@organization order by assessed_at desc",person,r=>new CapacityResponse(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetBoolean(4),r.GetBoolean(5),r.GetBoolean(6),r.GetBoolean(7),r.GetString(8),r.GetString(9),r.GetString(10),r.GetString(11),r.GetFieldValue<DateTimeOffset>(12),r.IsDBNull(13)?null:r.GetFieldValue<DateTimeOffset>(13),r.GetString(14),r.GetInt32(15),r.IsDBNull(16)?null:r.GetGuid(16),r.GetBoolean(17)),token);
 private Task<List<BestInterestResponse>> BestInterests(Guid person,CancellationToken token)=>Query("select id,capacity_decision_id,decision,options_considered,consulted_people,person_wishes,risks_and_benefits,least_restrictive_reason,decision_maker,decided_at,review_due_at,status from best_interest_decisions where service_user_id=@person and organization_id=@organization order by decided_at desc",person,r=>new BestInterestResponse(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetString(8),r.GetFieldValue<DateTimeOffset>(9),r.IsDBNull(10)?null:r.GetFieldValue<DateTimeOffset>(10),r.GetString(11)),token);
 private Task<List<AuthorityResponse>> Authorities(Guid person,CancellationToken token)=>Query("select id,authority_type,holder_name,holder_relationship,scope,verification_status,verification_reference,valid_from,valid_until,status,version,supersedes_id,revoked_at,revocation_reason from authority_records where service_user_id=@person and organization_id=@organization order by created_at desc",person,r=>new AuthorityResponse(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetFieldValue<DateTimeOffset>(7),r.IsDBNull(8)?null:r.GetFieldValue<DateTimeOffset>(8),r.GetString(9),r.GetInt32(10),r.IsDBNull(11)?null:r.GetGuid(11),r.IsDBNull(12)?null:r.GetFieldValue<DateTimeOffset>(12),r.GetString(13)),token);
 private async Task<(Guid Id,int Version)?> CurrentCapacity(Guid person,string context,CancellationToken token){await using var c=await Command("select id,version from capacity_decisions where service_user_id=@person and organization_id=@organization and branch_id=@branch and status='Current' and lower(decision_context)=lower(@context)",person,null,token);Add(c,"context",context.Trim());await using var r=await c.ExecuteReaderAsync(token);return await r.ReadAsync(token)?(r.GetGuid(0),r.GetInt32(1)):null;}
 private async Task<(Guid Id,int Version)?> CurrentAuthority(Guid person,string type,string holder,CancellationToken token){await using var c=await Command("select id,version from authority_records where service_user_id=@person and organization_id=@organization and branch_id=@branch and status='Active' and lower(authority_type)=lower(@type) and lower(holder_name)=lower(@holder)",person,null,token);Add(c,"type",type.Trim());Add(c,"holder",holder.Trim());await using var r=await c.ExecuteReaderAsync(token);return await r.ReadAsync(token)?(r.GetGuid(0),r.GetInt32(1)):null;}
 private async Task<long> Scalar(string sql,Guid person,Guid id,CancellationToken token){await using var c=await Command(sql,person,id,token);Add(c,"target",id);return Convert.ToInt64(await c.ExecuteScalarAsync(token));}
 private async Task<int> Exec(string sql,Guid person,Guid id,Action<DbCommand> bind,CancellationToken token){await using var c=await Command(sql,person,id,token);bind(c);return await c.ExecuteNonQueryAsync(token);}
 private async Task<List<T>> Query<T>(string sql,Guid person,Func<DbDataReader,T> map,CancellationToken token){var a=new List<T>();await using var c=await Command(sql,person,null,token);await using var r=await c.ExecuteReaderAsync(token);while(await r.ReadAsync(token))a.Add(map(r));return a;}
 private async Task<DbCommand> Command(string sql,Guid person,Guid? id,CancellationToken token){var cn=db.Database.GetDbConnection();if(cn.State!=System.Data.ConnectionState.Open)await cn.OpenAsync(token);var c=cn.CreateCommand();c.CommandText=sql;Add(c,"person",person);Add(c,"organization",tenant.OrganizationId);Add(c,"branch",tenant.BranchId??TenantDefaults.BranchId);Add(c,"actor",user.UserName);if(id is not null)Add(c,"id",id);return c;}
 private void Audit(string action,string entity,Guid id)=>db.AuditEvents.Add(new AuditEvent(Guid.NewGuid(),action,user.UserName,entity,id,DateTimeOffset.UtcNow,tenant.OrganizationId,tenant.BranchId??TenantDefaults.BranchId));
 private static void Add(DbCommand c,string n,object? v){if(c.Parameters.Contains(n))return;var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}private static bool Missing(string? v)=>string.IsNullOrWhiteSpace(v);
}

public sealed record CapacityDecisionRequest(string DecisionContext,string AssessmentReason,bool CanUnderstand,bool CanRetain,bool CanUseOrWeigh,bool CanCommunicate,string SupportProvided,string AssessorName,string AssessorRole,string? EvidenceReference,DateTimeOffset? AssessedAt,DateTimeOffset? ReviewDueAt);
public sealed record BestInterestRequest(string Decision,string OptionsConsidered,string ConsultedPeople,string PersonWishes,string RisksAndBenefits,string LeastRestrictiveReason,string DecisionMaker,DateTimeOffset? DecidedAt,DateTimeOffset? ReviewDueAt);
public sealed record AuthorityRequest(string AuthorityType,string HolderName,string? HolderRelationship,string Scope,string VerificationStatus,string VerificationReference,DateTimeOffset ValidFrom,DateTimeOffset? ValidUntil);
public sealed record RevokeAuthorityRequest(string Reason);
public sealed record CapacityResponse(Guid Id,string DecisionContext,string AssessmentReason,string Outcome,bool CanUnderstand,bool CanRetain,bool CanUseOrWeigh,bool CanCommunicate,string SupportProvided,string AssessorName,string AssessorRole,string EvidenceReference,DateTimeOffset AssessedAt,DateTimeOffset? ReviewDueAt,string Status,int Version,Guid? SupersedesId,bool BestInterestRequired);
public sealed record BestInterestResponse(Guid Id,Guid CapacityDecisionId,string Decision,string OptionsConsidered,string ConsultedPeople,string PersonWishes,string RisksAndBenefits,string LeastRestrictiveReason,string DecisionMaker,DateTimeOffset DecidedAt,DateTimeOffset? ReviewDueAt,string Status);
public sealed record AuthorityResponse(Guid Id,string AuthorityType,string HolderName,string HolderRelationship,string Scope,string VerificationStatus,string VerificationReference,DateTimeOffset ValidFrom,DateTimeOffset? ValidUntil,string Status,int Version,Guid? SupersedesId,DateTimeOffset? RevokedAt,string RevocationReason);
