using System.Data.Common;using System.Text.Json;using AiCare.Application;using AiCare.Domain;using AiCare.Infrastructure;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
namespace AiCare.Api;
[ApiController][Authorize(Policy="Phase1User")][Route("api/phase1/care-documentation")]
public sealed class CareDocumentationController(CareDbContext db,ITenantContext tenant,ICurrentUserContext user):ControllerBase
{
 [HttpPost("notes/{noteId:guid}/amendments")]
 public async Task<IActionResult> Amend(Guid noteId,AmendCareNoteRequest request,CancellationToken t){var note=await db.CareNotes.SingleOrDefaultAsync(x=>x.Id==noteId&&x.OrganizationId==tenant.OrganizationId,t);if(note is null||!CanWrite(note.CareWorkerId))return NotFound();if(string.IsNullOrWhiteSpace(request.Reason))return BadRequest(new{message="An amendment reason is required."});var id=Guid.NewGuid();var old=JsonSerializer.Serialize(new{note.Summary,note.PersonalCare,note.MealsAndHydration,note.Medication,note.Concerns,note.RequiresReview});var next=new{Summary=request.Summary.Trim(),PersonalCare=request.PersonalCare.Trim(),MealsAndHydration=request.MealsAndHydration.Trim(),Medication=request.Medication.Trim(),Concerns=request.Concerns.Trim(),request.RequiresReview};await Exec("insert into care_note_amendments(id,care_note_id,organization_id,reason,old_values_json,new_values_json,amended_by) values(@id,@note,@organization,@reason,@old,@new,@actor)",c=>{Add(c,"id",id);Add(c,"note",noteId);Add(c,"reason",request.Reason.Trim());Add(c,"old",old);Add(c,"new",JsonSerializer.Serialize(next));},t);db.Entry(note).State=EntityState.Detached;db.CareNotes.Update(note with{Summary=next.Summary,PersonalCare=next.PersonalCare,MealsAndHydration=next.MealsAndHydration,Medication=next.Medication,Concerns=next.Concerns,RequiresReview=next.RequiresReview});Audit("care_note.amended",id);await db.SaveChangesAsync(t);return Created($"/api/phase1/care-documentation/notes/{noteId}/amendments/{id}",new{id});}
 [HttpPost("notes/{noteId:guid}/reviews")][Authorize(Roles="CareCoordinator,CareManager,Administrator")]
 public async Task<IActionResult> Review(Guid noteId,ReviewCareNoteRequest request,CancellationToken t){if(request.Status is not("Approved" or "ChangesRequired"))return BadRequest(new{message="Review status must be Approved or ChangesRequired."});if(!await db.CareNotes.AnyAsync(x=>x.Id==noteId&&x.OrganizationId==tenant.OrganizationId,t))return NotFound();var id=Guid.NewGuid();await Exec("insert into care_note_reviews(id,care_note_id,organization_id,status,comment,reviewed_by) values(@id,@note,@organization,@status,@comment,@actor)",c=>{Add(c,"id",id);Add(c,"note",noteId);Add(c,"status",request.Status);Add(c,"comment",request.Comment??"");},t);Audit("care_note.reviewed",id);await db.SaveChangesAsync(t);return Created("",new{id});}
 [HttpPut("thresholds/{observationType}")][Authorize(Roles="CareCoordinator,CareManager,Administrator")]
 public async Task<IActionResult> Threshold(string observationType,ObservationThresholdRequest request,CancellationToken t){if(request.MinimumValue is null&&request.MaximumValue is null)return BadRequest(new{message="At least one threshold is required."});await Exec("insert into observation_thresholds(id,organization_id,branch_id,observation_type,minimum_value,maximum_value,severity,instructions,active) values(@id,@organization,@branch,@type,@min,@max,@severity,@instructions,true) on conflict(organization_id,branch_id,observation_type) do update set minimum_value=@min,maximum_value=@max,severity=@severity,instructions=@instructions,active=true,updated_at=now()",c=>{Add(c,"id",Guid.NewGuid());Add(c,"type",observationType);Add(c,"min",request.MinimumValue);Add(c,"max",request.MaximumValue);Add(c,"severity",request.Severity);Add(c,"instructions",request.Instructions);},t);return Ok(request);}
 [HttpPatch("alerts/{id:guid}")][Authorize(Roles="CareCoordinator,CareManager,Administrator")]
 public async Task<IActionResult> Alert(Guid id,ProgressDeteriorationRequest request,CancellationToken t){if(request.Action is not("Acknowledge" or "Resolve"))return BadRequest(new{message="Action must be Acknowledge or Resolve."});var status=request.Action=="Acknowledge"?"Acknowledged":"Resolved";var stamp=request.Action=="Acknowledge"?"acknowledged_at":"resolved_at";var n=await Exec($"update deterioration_alerts set status=@status,{stamp}=now(),immediate_action=@immediate,external_contact=@contact,owner=@owner,updated_at=now() where id=@id and organization_id=@organization",c=>{Add(c,"id",id);Add(c,"status",status);Add(c,"immediate",request.ImmediateAction);Add(c,"contact",request.ExternalContact);Add(c,"owner",request.Owner);},t);if(n==0)return NotFound();Audit($"deterioration_alert.{status.ToLowerInvariant()}",id);await db.SaveChangesAsync(t);return NoContent();}
 [HttpGet("visits/{visitId:guid}/alerts")]
 public async Task<IActionResult> Alerts(Guid visitId,CancellationToken t){var visit=await db.Visits.SingleOrDefaultAsync(x=>x.Id==visitId&&x.OrganizationId==tenant.OrganizationId,t);if(visit is null||!CanWrite(visit.CareWorkerId))return NotFound();return Ok(await Query("select id,alert_type,severity,detail,immediate_action,external_contact,owner,status,created_at from deterioration_alerts where visit_id=@visit and organization_id=@organization order by created_at desc",c=>Add(c,"visit",visitId),r=>new{Id=r.GetGuid(0),AlertType=r.GetString(1),Severity=r.GetString(2),Detail=r.GetString(3),ImmediateAction=r.GetString(4),ExternalContact=r.GetString(5),Owner=r.GetString(6),Status=r.GetString(7),CreatedAt=r.GetFieldValue<DateTimeOffset>(8)},t));}
 [HttpGet("service-users/{personId:guid}/timeline")]
 public async Task<IActionResult> Timeline(Guid personId,CancellationToken t){if(!await db.ServiceUsers.AnyAsync(x=>x.Id==personId&&x.OrganizationId==tenant.OrganizationId,t))return NotFound();if(!await CanReadPerson(personId,t))return NotFound();var rows=new List<object>();rows.AddRange(await db.CareNotes.AsNoTracking().Where(x=>x.ServiceUserId==personId&&x.OrganizationId==tenant.OrganizationId).Select(x=>new{Type="CareNote",Title=x.Summary,Detail=x.Concerns,When=x.CreatedAt,RecordId=x.Id}).ToListAsync(t));rows.AddRange(await db.HealthObservations.AsNoTracking().Where(x=>x.ServiceUserId==personId&&x.OrganizationId==tenant.OrganizationId).Select(x=>new{Type="Observation",Title=x.ObservationType,Detail=x.Value+" "+x.Unit,When=x.RecordedAt,RecordId=x.Id}).ToListAsync(t));var raw=await Query("select 'TaskException',title,exception_reason,completed_at,id from visit_tasks where service_user_id=@person and organization_id=@organization and exception_reason<>'' union all select 'Deterioration',alert_type,detail,created_at,id from deterioration_alerts where service_user_id=@person and organization_id=@organization union all select 'Handover',summary,outstanding_actions,created_at,id from visit_handovers where service_user_id=@person and organization_id=@organization",c=>Add(c,"person",personId),r=>new{Type=r.GetString(0),Title=r.GetString(1),Detail=r.GetString(2),When=r.GetFieldValue<DateTimeOffset>(3),RecordId=r.GetGuid(4)},t);rows.AddRange(raw);return Ok(rows.OrderByDescending(x=>(DateTimeOffset)x.GetType().GetProperty("When")!.GetValue(x)!).Take(200));}
 private bool CanWrite(Guid worker)=>user.IsAdministrator||user.IsCareManager||user.IsCareCoordinator||(user.IsCareWorker&&user.CareWorkerId==worker);
 private async Task<bool> CanReadPerson(Guid personId,CancellationToken t){if(user.IsAdministrator||user.IsCareManager||user.IsCareCoordinator)return true;if(!user.IsCareWorker||user.CareWorkerId is not Guid worker)return false;if(await db.Visits.AnyAsync(x=>x.ServiceUserId==personId&&x.OrganizationId==tenant.OrganizationId&&x.CareWorkerId==worker,t))return true;try{await using var c=await Command("select exists(select 1 from visits v join visit_care_worker_assignments a on a.visit_id=v.id where v.service_user_id=@person and a.care_worker_id=@worker and v.organization_id=@organization and a.organization_id=@organization)",t);Add(c,"person",personId);Add(c,"worker",worker);return Convert.ToBoolean(await c.ExecuteScalarAsync(t));}catch(DbException){return false;}}
 private void Audit(string action,Guid id)=>db.AuditEvents.Add(new AuditEvent(Guid.NewGuid(),action,user.UserName,"CareDocumentation",id,DateTimeOffset.UtcNow,tenant.OrganizationId,tenant.BranchId??TenantDefaults.BranchId));
 private async Task<int> Exec(string sql,Action<DbCommand> bind,CancellationToken t){await using var c=await Command(sql,t);bind(c);return await c.ExecuteNonQueryAsync(t);}private async Task<List<T>> Query<T>(string sql,Action<DbCommand> bind,Func<DbDataReader,T> map,CancellationToken t){var a=new List<T>();await using var c=await Command(sql,t);bind(c);await using var r=await c.ExecuteReaderAsync(t);while(await r.ReadAsync(t))a.Add(map(r));return a;}
 private async Task<DbCommand> Command(string sql,CancellationToken t){var cn=db.Database.GetDbConnection();if(cn.State!=System.Data.ConnectionState.Open)await cn.OpenAsync(t);var c=cn.CreateCommand();c.CommandText=sql;Add(c,"organization",tenant.OrganizationId);Add(c,"branch",tenant.BranchId??TenantDefaults.BranchId);Add(c,"actor",user.UserName);return c;}private static void Add(DbCommand c,string n,object? v){if(c.Parameters.Contains(n))return;var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}
}
public sealed record AmendCareNoteRequest(string Reason,string Summary,string PersonalCare,string MealsAndHydration,string Medication,string Concerns,bool RequiresReview);public sealed record ReviewCareNoteRequest(string Status,string? Comment);public sealed record ObservationThresholdRequest(decimal? MinimumValue,decimal? MaximumValue,string Severity,string Instructions);public sealed record ProgressDeteriorationRequest(string Action,string ImmediateAction,string ExternalContact,string Owner);



