using System.Data;
using System.Data.Common;
using AiCare.Application;
using AiCare.Domain;
using AiCare.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AiCare.Api;

[ApiController]
[Authorize(Policy="Phase1User")]
[Route("api/phase1/emar-safety")]
public sealed class EmarOperationsController(CareDbContext db,ITenantContext tenant,ICurrentUserContext user):ControllerBase
{
 [HttpPost("medications/{medicationId:guid}/stock")]
 [Authorize(Roles="CareCoordinator,CareManager,Administrator")]
 public async Task<IActionResult> Stock(Guid medicationId,StockOperationRequest request,CancellationToken token)
 {
  var allowed=new[]{"Receipt","Return","Waste","Disposal","Correction","Adjustment"};if(!allowed.Contains(request.TransactionType)||request.Quantity==0||Missing(request.Reason))return BadRequest(new{message="A supported type, non-zero quantity, and reason are required."});var profile=await Profile(medicationId,token);if(profile is null)return NotFound();if(profile.Value.Stock is null)return Conflict(new{message="A reconciled stock balance is required."});var quantity=request.TransactionType=="Receipt"?Math.Abs(request.Quantity):-Math.Abs(request.Quantity);if(request.TransactionType is "Correction" or "Adjustment")quantity=request.Quantity;var after=profile.Value.Stock.Value+quantity;if(after<0)return Conflict(new{message="Stock transaction would create a negative balance."});var witness=await Witness(request.WitnessUserId,profile.Value.RequiresWitness||request.TransactionType is "Waste" or "Disposal",token);if(witness.Error is not null)return BadRequest(new{message=witness.Error});var id=Guid.NewGuid();var strategy=db.Database.CreateExecutionStrategy();await strategy.ExecuteAsync(async()=>{await using var tx=await db.Database.BeginTransactionAsync(token);await Exec("update medication_safety_profiles set stock_on_hand=@after,updated_at=now() where medication_id=@medication and organization_id=@organization;insert into medication_stock_transactions(id,medication_id,organization_id,branch_id,transaction_type,quantity,balance_before,balance_after,reference,reason,witness_user_id,witness_name,created_by_user_id,created_by) values(@id,@medication,@organization,@branch,@type,@quantity,@before,@after,@reference,@reason,@witness,@witnessName,@actorId,@actor)",c=>{Add(c,"id",id);Add(c,"medication",medicationId);Add(c,"after",after);Add(c,"type",request.TransactionType);Add(c,"quantity",quantity);Add(c,"before",profile.Value.Stock);Add(c,"reference",request.Reference?.Trim()??"");Add(c,"reason",request.Reason.Trim());Add(c,"witness",request.WitnessUserId);Add(c,"witnessName",witness.Name);},token);if(profile.Value.Reorder is not null&&after<=profile.Value.Reorder)await LowStock(medicationId,id,after,profile.Value.Reorder.Value,token);Audit("emar.stock_transaction_recorded","Medication",medicationId);await db.SaveChangesAsync(token);await tx.CommitAsync(token);});return CreatedAtAction(nameof(StockHistory),new{medicationId},new{id,balanceAfter=after});
 }

 [HttpGet("medications/{medicationId:guid}/stock")]
 public async Task<IActionResult> StockHistory(Guid medicationId,CancellationToken token){if(await Profile(medicationId,token) is null)return NotFound();return Ok(await Query("select id,transaction_type,quantity,balance_before,balance_after,reference,reason,witness_name,created_by,created_at from medication_stock_transactions where medication_id=@medication and organization_id=@organization and branch_id=@branch order by created_at desc",c=>Add(c,"medication",medicationId),r=>(object)new{id=r.GetGuid(0),transactionType=r.GetString(1),quantity=r.GetDecimal(2),balanceBefore=r.GetDecimal(3),balanceAfter=r.GetDecimal(4),reference=r.GetString(5),reason=r.GetString(6),witnessName=r.GetString(7),createdBy=r.GetString(8),createdAt=r.GetFieldValue<DateTimeOffset>(9)},token));}

 [HttpPost("mar/{marId:guid}/prn-effect")]
 public async Task<IActionResult> PrnEffect(Guid marId,PrnEffectOperationRequest request,CancellationToken token)
 {
  var mar=await Mar(marId,token);if(mar is null)return NotFound();if(!CanRecord(mar.Value.Worker))return Forbid();if(!mar.Value.IsPrn||Missing(request.Effect))return BadRequest(new{message="A PRN administration and observed effect are required."});var administration=await LedgerId(marId,"Administration",token);if(administration is null)return Conflict(new{message="PRN effect can only follow a governed administration."});if(await LedgerId(marId,"PRNEffect",token) is not null)return Conflict(new{message="PRN effect has already been recorded."});var id=Guid.NewGuid();await Exec("insert into emar_ledger(id,mar_record_id,medication_id,service_user_id,organization_id,branch_id,event_type,outcome,prn_effect,corrects_ledger_id,occurred_at,created_by_user_id,created_by) values(@id,@mar,@medication,@person,@organization,@branch,'PRNEffect','Reviewed',@effect,@administration,@occurred,@actorId,@actor);update emar_escalations set status='Resolved',resolved_at=now(),resolution=@effect where mar_record_id=@mar and organization_id=@organization and escalation_type='PRNEffectReview' and status in ('Open','Acknowledged')",c=>{Add(c,"id",id);Add(c,"mar",marId);Add(c,"medication",mar.Value.Medication);Add(c,"person",mar.Value.Person);Add(c,"effect",request.Effect.Trim());Add(c,"administration",administration);Add(c,"occurred",request.ObservedAt??DateTimeOffset.UtcNow);},token);Audit("emar.prn_effect_recorded","MedicationAdministrationRecord",marId);await db.SaveChangesAsync(token);return CreatedAtAction(nameof(ProductionEmarController.History),"ProductionEmar",new{marId},new{id});
 }

 [HttpPost("mar/{marId:guid}/corrections")]
 [Authorize(Roles="CareManager,Administrator")]
 public async Task<IActionResult> Correct(Guid marId,EmarCorrectionRequest request,CancellationToken token)
 {
  var mar=await Mar(marId,token);if(mar is null)return NotFound();if(Missing(request.Reason,request.CorrectedOutcome))return BadRequest(new{message="Correction reason and corrected outcome are required."});if(!await LedgerExists(marId,request.CorrectsLedgerId,token))return NotFound();var id=Guid.NewGuid();await Exec("insert into emar_ledger(id,mar_record_id,medication_id,service_user_id,organization_id,branch_id,event_type,outcome,reason_code,reason_detail,corrects_ledger_id,occurred_at,created_by_user_id,created_by) values(@id,@mar,@medication,@person,@organization,@branch,'Correction',@outcome,'Correction',@reason,@corrects,now(),@actorId,@actor)",c=>{Add(c,"id",id);Add(c,"mar",marId);Add(c,"medication",mar.Value.Medication);Add(c,"person",mar.Value.Person);Add(c,"outcome",request.CorrectedOutcome.Trim());Add(c,"reason",request.Reason.Trim());Add(c,"corrects",request.CorrectsLedgerId);},token);Audit("emar.correction_recorded","MedicationAdministrationRecord",marId);await db.SaveChangesAsync(token);return CreatedAtAction(nameof(ProductionEmarController.History),"ProductionEmar",new{marId},new{id});
 }

 [HttpPost("escalations/{id:guid}/progress")]
 [Authorize(Roles="CareCoordinator,CareManager,Administrator")]
 public async Task<IActionResult> Progress(Guid id,EscalationOperationRequest request,CancellationToken token)
 {
  if(request.Action is not("Acknowledge" or "Resolve" or "Reopen")||Missing(request.Comment))return BadRequest(new{message="A supported action and comment are required."});var sql=request.Action switch{"Acknowledge"=>"update emar_escalations set status='Acknowledged',acknowledged_at=now(),acknowledged_by=@actor,resolution=@comment where id=@id and organization_id=@organization and branch_id=@branch and status='Open'","Resolve"=>"update emar_escalations set status='Resolved',resolved_at=now(),resolution=@comment where id=@id and organization_id=@organization and branch_id=@branch and status in ('Open','Acknowledged')",_=>"update emar_escalations set status='Open',resolved_at=null,resolution=@comment where id=@id and organization_id=@organization and branch_id=@branch and status='Resolved'"};var changed=await Exec(sql,c=>{Add(c,"id",id);Add(c,"comment",request.Comment.Trim());},token);if(changed==0)return Conflict(new{message="Escalation cannot be progressed from its current state."});Audit("emar.escalation_progressed","EmarEscalation",id);await db.SaveChangesAsync(token);return NoContent();
 }

 private async Task LowStock(Guid medication,Guid stockId,decimal balance,decimal reorder,CancellationToken token){var mar=await ScalarGuid("select \"Id\" from \"MedicationAdministrationRecords\" where \"MedicationId\"=@medication and \"OrganizationId\"=@organization order by \"ScheduledAt\" desc limit 1",c=>Add(c,"medication",medication),token);if(mar is null)return;var ledger=await ScalarGuid("select id from emar_ledger where medication_id=@medication and organization_id=@organization order by created_at desc limit 1",c=>Add(c,"medication",medication),token);if(ledger is null)return;await Exec("insert into emar_escalations(id,mar_record_id,ledger_id,organization_id,branch_id,escalation_type,severity,message,owner) values(@id,@mar,@ledger,@organization,@branch,'LowStock','Medium',@message,'Medication lead')",c=>{Add(c,"id",Guid.NewGuid());Add(c,"mar",mar);Add(c,"ledger",ledger);Add(c,"message",$"Stock balance {balance} is at or below reorder level {reorder} after transaction {stockId}.");},token);}
 private async Task<(decimal? Stock,decimal? Reorder,bool RequiresWitness)?> Profile(Guid medication,CancellationToken token){await using var c=await Command("select stock_on_hand,reorder_level,requires_witness from medication_safety_profiles where medication_id=@medication and organization_id=@organization and branch_id=@branch",token);Add(c,"medication",medication);await using var r=await c.ExecuteReaderAsync(token);return await r.ReadAsync(token)?(Decimal(r,0),Decimal(r,1),r.GetBoolean(2)):null;}
 private async Task<(Guid Medication,Guid Person,Guid Worker,bool IsPrn)?> Mar(Guid id,CancellationToken token){await using var c=await Command("select r.\"MedicationId\",m.\"ServiceUserId\",r.\"CareWorkerId\",m.\"IsPrn\" from \"MedicationAdministrationRecords\" r join \"Medications\" m on m.\"Id\"=r.\"MedicationId\" where r.\"Id\"=@id and r.\"OrganizationId\"=@organization and r.\"BranchId\"=@branch",token);Add(c,"id",id);await using var r=await c.ExecuteReaderAsync(token);return await r.ReadAsync(token)?(r.GetGuid(0),r.GetGuid(1),r.GetGuid(2),r.GetBoolean(3)):null;}
 private bool CanRecord(Guid worker)=>user.IsAdministrator||user.IsCareManager||user.IsCareCoordinator||(user.IsCareWorker&&user.CareWorkerId==worker);private async Task<(string Name,string? Error)> Witness(Guid? id,bool required,CancellationToken token){if(id is null)return required?("","A verified witness is required."):("",null);if(id==user.UserId)return("","A user cannot witness their own transaction.");var witness=await db.AppUsers.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.OrganizationId==tenant.OrganizationId&&x.IsActive,token);return witness is null?("","Witness must be an active user in the same organization."):(witness.UserName,null);}
 private async Task<Guid?> LedgerId(Guid mar,string type,CancellationToken token)=>await ScalarGuid("select id from emar_ledger where mar_record_id=@mar and organization_id=@organization and event_type=@type order by created_at desc limit 1",c=>{Add(c,"mar",mar);Add(c,"type",type);},token);private async Task<bool> LedgerExists(Guid mar,Guid id,CancellationToken token)=>(await ScalarGuid("select id from emar_ledger where id=@id and mar_record_id=@mar and organization_id=@organization",c=>{Add(c,"id",id);Add(c,"mar",mar);},token)) is not null;private async Task<Guid?> ScalarGuid(string sql,Action<DbCommand> bind,CancellationToken token){await using var c=await Command(sql,token);bind(c);var value=await c.ExecuteScalarAsync(token);return value is Guid id?id:null;}
 private void Audit(string action,string entity,Guid id)=>db.AuditEvents.Add(new AuditEvent(Guid.NewGuid(),action,user.UserName,entity,id,DateTimeOffset.UtcNow,tenant.OrganizationId,tenant.BranchId??TenantDefaults.BranchId));private static bool Missing(params string?[] values)=>values.Any(string.IsNullOrWhiteSpace);private async Task<int> Exec(string sql,Action<DbCommand> bind,CancellationToken token){await using var c=await Command(sql,token);bind(c);return await c.ExecuteNonQueryAsync(token);}private async Task<DbCommand> Command(string sql,CancellationToken token){var connection=db.Database.GetDbConnection();if(connection.State!=ConnectionState.Open)await connection.OpenAsync(token);var c=connection.CreateCommand();c.CommandText=sql;Add(c,"organization",tenant.OrganizationId);Add(c,"branch",tenant.BranchId??TenantDefaults.BranchId);Add(c,"actor",user.UserName);Add(c,"actorId",user.UserId);return c;}private async Task<List<T>> Query<T>(string sql,Action<DbCommand> bind,Func<DbDataReader,T> map,CancellationToken token){await using var c=await Command(sql,token);bind(c);await using var r=await c.ExecuteReaderAsync(token);var result=new List<T>();while(await r.ReadAsync(token))result.Add(map(r));return result;}private static decimal? Decimal(DbDataReader r,int i)=>r.IsDBNull(i)?null:r.GetDecimal(i);private static void Add(DbCommand c,string name,object? value){var p=c.CreateParameter();p.ParameterName=name;p.Value=value??DBNull.Value;c.Parameters.Add(p);}
}

public sealed record StockOperationRequest(string TransactionType,decimal Quantity,string? Reference,string Reason,Guid? WitnessUserId);
public sealed record PrnEffectOperationRequest(string Effect,DateTimeOffset? ObservedAt);
public sealed record EmarCorrectionRequest(Guid CorrectsLedgerId,string CorrectedOutcome,string Reason);
public sealed record EscalationOperationRequest(string Action,string Comment);
