using System.Data.Common;
using AiCare.Application;
using AiCare.Domain;
using AiCare.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AiCare.Api;

[ApiController]
[Authorize(Roles="Administrator,BackOffice")]
[Route("api/phase1/finance")]
public sealed class FinanceGovernanceController(CareDbContext db,ITenantContext tenant,ICurrentUserContext user):ControllerBase
{
    [HttpGet("dashboard")]
    public async Task<IActionResult> Dashboard(CancellationToken t)=>Ok(new{
        invoiceCount=await Scalar("select count(*) from \"Invoices\" where \"OrganizationId\"=@organization",t),
        generatedInvoices=await Scalar("select count(*) from \"Invoices\" where \"OrganizationId\"=@organization and \"Status\"='Generated'",t),
        approvedInvoices=await Scalar("select count(*) from \"Invoices\" where \"OrganizationId\"=@organization and \"Status\"='Approved'",t),
        paidInvoices=await Scalar("select count(*) from \"Invoices\" where \"OrganizationId\"=@organization and \"Status\"='Paid'",t),
        invoiceTotal=await Money("select coalesce(sum(\"Amount\"),0) from \"Invoices\" where \"OrganizationId\"=@organization and \"Status\"<>'Void'",t),
        paymentsReceived=await Money("select coalesce(sum(amount),0) from finance_payments where organization_id=@organization",t),
        payrollTotal=await Money("select coalesce(sum(gross_pay),0) from finance_payroll_lines where organization_id=@organization",t),
        openReconciliations=await Scalar("select count(*) from finance_funding_reconciliations where organization_id=@organization and status='Open'",t)});

    [HttpPost("invoice-batches")]
    public async Task<IActionResult> GenerateInvoiceBatch(GenerateFinanceBatchRequest request,CancellationToken t){if(request.PeriodStart>=request.PeriodEnd)return BadRequest(new{message="Period start must be before period end."});var visits=await db.Visits.AsNoTracking().Where(x=>x.OrganizationId==tenant.OrganizationId&&x.Status==VisitStatus.Completed&&x.StartsAt>=request.PeriodStart&&x.StartsAt<request.PeriodEnd).ToListAsync(t);var grouped=visits.GroupBy(x=>x.ServiceUserId).ToList();var created=new List<Invoice>();foreach(var group in grouped){var person=await db.ServiceUsers.AsNoTracking().SingleAsync(x=>x.Id==group.Key,t);var funding=await Funding(group.Key,t);var rate=funding?.HourlyRate>0?funding.HourlyRate:request.DefaultHourlyRate;var hours=Math.Round(group.Sum(x=>x.DurationMinutes)/60m,2);var amount=Math.Round(hours*rate,2);var invoice=new Invoice(Guid.NewGuid(),group.Key,funding?.FundingSource??person.FundingSource,amount,"Generated",DateTimeOffset.UtcNow,tenant.OrganizationId,tenant.BranchId??TenantDefaults.BranchId);db.Invoices.Add(invoice);created.Add(invoice);await db.SaveChangesAsync(t);foreach(var visit in group)await Exec("insert into finance_invoice_lines(id,invoice_id,visit_id,service_user_id,organization_id,branch_id,description,quantity,unit_rate,amount,funding_source) values(@id,@invoice,@visit,@person,@organization,@branch,@description,@quantity,@rate,@amount,@funding)",c=>{var q=Math.Round(visit.DurationMinutes/60m,2);Add(c,"id",Guid.NewGuid());Add(c,"invoice",invoice.Id);Add(c,"visit",visit.Id);Add(c,"person",group.Key);Add(c,"description",visit.VisitType);Add(c,"quantity",q);Add(c,"rate",rate);Add(c,"amount",Math.Round(q*rate,2));Add(c,"funding",invoice.Funder);},t);}Audit("finance.invoice_batch_generated","Invoice",created.FirstOrDefault()?.Id);await db.SaveChangesAsync(t);return Created("/api/phase1/finance/invoice-batches",new{count=created.Count,invoices=created});}

    [HttpPost("payroll-batches")]
    public async Task<IActionResult> GeneratePayrollBatch(GenerateFinanceBatchRequest request,CancellationToken t){if(request.PeriodStart>=request.PeriodEnd)return BadRequest(new{message="Period start must be before period end."});var visits=await db.Visits.AsNoTracking().Where(x=>x.OrganizationId==tenant.OrganizationId&&x.Status==VisitStatus.Completed&&x.StartsAt>=request.PeriodStart&&x.StartsAt<request.PeriodEnd).ToListAsync(t);var workerIds=visits.Select(x=>x.CareWorkerId).Distinct().ToList();var totalHours=Math.Round(visits.Sum(x=>x.DurationMinutes)/60m,2);var payroll=new PayrollRun(Guid.NewGuid(),$"{request.PeriodStart:yyyyMMdd}-{request.PeriodEnd:yyyyMMdd}",workerIds.Count,0,"Generated",DateTimeOffset.UtcNow,tenant.OrganizationId,tenant.BranchId??TenantDefaults.BranchId);db.PayrollRuns.Add(payroll);await db.SaveChangesAsync(t);decimal total=0;foreach(var visit in visits){var hours=Math.Round(visit.DurationMinutes/60m,2);var mileage=request.MileageRate;var gross=Math.Round(hours*request.DefaultHourlyRate+mileage,2);total+=gross;await Exec("insert into finance_payroll_lines(id,payroll_run_id,visit_id,care_worker_id,organization_id,branch_id,description,payable_hours,hourly_rate,mileage_amount,gross_pay) values(@id,@run,@visit,@worker,@organization,@branch,@description,@hours,@rate,@mileage,@gross)",c=>{Add(c,"id",Guid.NewGuid());Add(c,"run",payroll.Id);Add(c,"visit",visit.Id);Add(c,"worker",visit.CareWorkerId);Add(c,"description",visit.VisitType);Add(c,"hours",hours);Add(c,"rate",request.DefaultHourlyRate);Add(c,"mileage",mileage);Add(c,"gross",gross);},t);}db.Entry(payroll).State=EntityState.Detached;db.PayrollRuns.Update(payroll with{GrossPay=Math.Round(total,2)});Audit("finance.payroll_batch_generated","PayrollRun",payroll.Id);await db.SaveChangesAsync(t);return Created($"/api/phase1/finance/payroll-batches/{payroll.Id}",payroll with{GrossPay=Math.Round(total,2)});}

    [HttpGet("invoices/{id:guid}/lines")]
    public Task<List<InvoiceLineResponse>> InvoiceLines(Guid id,CancellationToken t)=>Query("select id,invoice_id,visit_id,service_user_id,description,quantity,unit_rate,amount,funding_source,created_at from finance_invoice_lines where invoice_id=@invoice and organization_id=@organization order by created_at",c=>Add(c,"invoice",id),r=>new InvoiceLineResponse(r.GetGuid(0),r.GetGuid(1),r.IsDBNull(2)?null:r.GetGuid(2),r.GetGuid(3),r.GetString(4),r.GetDecimal(5),r.GetDecimal(6),r.GetDecimal(7),r.GetString(8),r.GetFieldValue<DateTimeOffset>(9)),t);

    [HttpGet("payroll-runs/{id:guid}/lines")]
    public Task<List<PayrollLineResponse>> PayrollLines(Guid id,CancellationToken t)=>Query("select id,payroll_run_id,visit_id,care_worker_id,description,payable_hours,hourly_rate,mileage_amount,gross_pay,created_at from finance_payroll_lines where payroll_run_id=@run and organization_id=@organization order by created_at",c=>Add(c,"run",id),r=>new PayrollLineResponse(r.GetGuid(0),r.GetGuid(1),r.IsDBNull(2)?null:r.GetGuid(2),r.GetGuid(3),r.GetString(4),r.GetDecimal(5),r.GetDecimal(6),r.GetDecimal(7),r.GetDecimal(8),r.GetFieldValue<DateTimeOffset>(9)),t);

    [HttpPost("invoices/{id:guid}/payments")]
    public async Task<IActionResult> RecordPayment(Guid id,RecordFinancePaymentRequest request,CancellationToken t){if(request.Amount<=0||string.IsNullOrWhiteSpace(request.Reference))return BadRequest(new{message="Payment amount and reference are required."});var invoice=await db.Invoices.SingleOrDefaultAsync(x=>x.Id==id&&x.OrganizationId==tenant.OrganizationId,t);if(invoice is null)return NotFound();if(invoice.Status=="Void")return BadRequest(new{message="Void invoices cannot receive payments."});var paymentId=Guid.NewGuid();await Exec("insert into finance_payments(id,invoice_id,organization_id,branch_id,amount,reference,received_at,received_by) values(@id,@invoice,@organization,@branch,@amount,@reference,@received,@actor)",c=>{Add(c,"id",paymentId);Add(c,"invoice",id);Add(c,"amount",request.Amount);Add(c,"reference",request.Reference.Trim());Add(c,"received",request.ReceivedAt??DateTimeOffset.UtcNow);},t);var paid=await Money("select coalesce(sum(amount),0) from finance_payments where invoice_id=@invoice and organization_id=@organization",t,c=>Add(c,"invoice",id));db.Entry(invoice).CurrentValues.SetValues(invoice with{Status=paid>=invoice.Amount?"Paid":"Part paid"});Audit("finance.payment_recorded","FinancePayment",paymentId);await db.SaveChangesAsync(t);return Created($"/api/phase1/finance/invoices/{id}/payments/{paymentId}",new{id=paymentId,paid,status=paid>=invoice.Amount?"Paid":"Part paid"});}

    [HttpPost("funding-reconciliations")]
    public async Task<IActionResult> ReconcileFunding(FundingReconciliationRequest request,CancellationToken t){if(request.ServiceUserId==Guid.Empty||request.PeriodStart>=request.PeriodEnd)return BadRequest(new{message="Service user and valid period are required."});var person=await db.ServiceUsers.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==request.ServiceUserId&&x.OrganizationId==tenant.OrganizationId,t);if(person is null)return NotFound();var funding=await Funding(request.ServiceUserId,t);var delivered=await Money("select coalesce(sum(\"DurationMinutes\"),0)/60 from \"Visits\" where \"ServiceUserId\"=@person and \"OrganizationId\"=@organization and \"Status\"='Completed' and \"StartsAt\">=@start and \"StartsAt\"<@end",t,c=>{Add(c,"person",request.ServiceUserId);Add(c,"start",request.PeriodStart);Add(c,"end",request.PeriodEnd);});var invoiced=await Money("select coalesce(sum(\"Amount\"),0) from \"Invoices\" where \"ServiceUserId\"=@person and \"OrganizationId\"=@organization and \"IssuedAt\">=@start and \"IssuedAt\"<@end and \"Status\"<>'Void'",t,c=>{Add(c,"person",request.ServiceUserId);Add(c,"start",request.PeriodStart);Add(c,"end",request.PeriodEnd);});var authorized=funding?.AuthorizedHoursPerWeek??0;var variance=Math.Round(delivered-authorized,2);var status=Math.Abs(variance)>request.AllowedVarianceHours?"Exception":"Matched";var id=Guid.NewGuid();await Exec("insert into finance_funding_reconciliations(id,service_user_id,organization_id,branch_id,period_start,period_end,authorized_hours,delivered_hours,invoiced_amount,variance_hours,status,notes,created_by) values(@id,@person,@organization,@branch,@start,@end,@authorized,@delivered,@invoiced,@variance,@status,@notes,@actor)",c=>{Add(c,"id",id);Add(c,"person",request.ServiceUserId);Add(c,"start",request.PeriodStart);Add(c,"end",request.PeriodEnd);Add(c,"authorized",authorized);Add(c,"delivered",delivered);Add(c,"invoiced",invoiced);Add(c,"variance",variance);Add(c,"status",status);Add(c,"notes",request.Notes??"");},t);Audit("finance.funding_reconciled","FundingReconciliation",id);await db.SaveChangesAsync(t);return Created($"/api/phase1/finance/funding-reconciliations/{id}",new{id,status,authorizedHours=authorized,deliveredHours=delivered,invoicedAmount=invoiced,varianceHours=variance});}

    private async Task<Funding?> Funding(Guid person,CancellationToken t){var rows=await Query("select funding_source,authorized_hours_per_week,hourly_rate from funding_arrangements where service_user_id=@person and organization_id=@organization and status='Active' order by valid_from desc limit 1",c=>Add(c,"person",person),r=>new Funding(r.GetString(0),r.GetDecimal(1),r.GetDecimal(2)),t);return rows.FirstOrDefault();}
    private async Task<int> Scalar(string sql,CancellationToken t,Action<DbCommand>? bind=null){await using var c=await Command(sql,t);bind?.Invoke(c);return Convert.ToInt32(await c.ExecuteScalarAsync(t));}
    private async Task<decimal> Money(string sql,CancellationToken t,Action<DbCommand>? bind=null){await using var c=await Command(sql,t);bind?.Invoke(c);return Convert.ToDecimal(await c.ExecuteScalarAsync(t));}
    private async Task<int> Exec(string sql,Action<DbCommand> bind,CancellationToken t){await using var c=await Command(sql,t);bind(c);return await c.ExecuteNonQueryAsync(t);}private async Task<List<T>> Query<T>(string sql,Action<DbCommand> bind,Func<DbDataReader,T> map,CancellationToken t){var a=new List<T>();await using var c=await Command(sql,t);bind(c);await using var r=await c.ExecuteReaderAsync(t);while(await r.ReadAsync(t))a.Add(map(r));return a;}
    private async Task<DbCommand> Command(string sql,CancellationToken t){var cn=db.Database.GetDbConnection();if(cn.State!=System.Data.ConnectionState.Open)await cn.OpenAsync(t);var c=cn.CreateCommand();c.CommandText=sql;Add(c,"organization",tenant.OrganizationId);Add(c,"branch",tenant.BranchId??TenantDefaults.BranchId);Add(c,"actor",user.UserName);return c;}private static void Add(DbCommand c,string n,object? v){if(c.Parameters.Contains(n))return;var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}private void Audit(string action,string entity,Guid? id)=>db.AuditEvents.Add(new AuditEvent(Guid.NewGuid(),action,user.UserName,entity,id,DateTimeOffset.UtcNow,tenant.OrganizationId,tenant.BranchId??TenantDefaults.BranchId));
}
public sealed record GenerateFinanceBatchRequest(DateTimeOffset PeriodStart,DateTimeOffset PeriodEnd,decimal DefaultHourlyRate,decimal MileageRate);
public sealed record RecordFinancePaymentRequest(decimal Amount,string Reference,DateTimeOffset? ReceivedAt);
public sealed record FundingReconciliationRequest(Guid ServiceUserId,DateTimeOffset PeriodStart,DateTimeOffset PeriodEnd,decimal AllowedVarianceHours,string? Notes);
public sealed record Funding(string FundingSource,decimal AuthorizedHoursPerWeek,decimal HourlyRate);
public sealed record InvoiceLineResponse(Guid Id,Guid InvoiceId,Guid? VisitId,Guid ServiceUserId,string Description,decimal Quantity,decimal UnitRate,decimal Amount,string FundingSource,DateTimeOffset CreatedAt);
public sealed record PayrollLineResponse(Guid Id,Guid PayrollRunId,Guid? VisitId,Guid CareWorkerId,string Description,decimal PayableHours,decimal HourlyRate,decimal MileageAmount,decimal GrossPay,DateTimeOffset CreatedAt);

