using System.Data;using System.Data.Common;using System.Text;using System.Text.Json;using AiCare.Application;using AiCare.Domain;using AiCare.Infrastructure;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;
namespace AiCare.Api;
[ApiController][Authorize(Roles="Administrator,BackOffice")][Route("api/phase1/integrations/imports")]
public sealed class IntegrationImportController(CareDbContext db,ITenantContext tenant,ICurrentUserContext user):ControllerBase
{
 [HttpPost("preview")][RequestSizeLimit(5*1024*1024)]
 public async Task<IActionResult> Preview([FromForm]IFormFile file,[FromForm]string resourceType,[FromForm]string mappingJson,[FromForm]Guid? connectorId,CancellationToken token){if(file.Length is <=0 or >5*1024*1024)return BadRequest(new{message="Import file must be between 1 byte and 5 MB."});var ext=Path.GetExtension(file.FileName).ToLowerInvariant();if(ext is not ".csv" and not ".json")return BadRequest(new{message="Only CSV and JSON imports are supported."});Dictionary<string,string> mapping;try{mapping=JsonSerializer.Deserialize<Dictionary<string,string>>(mappingJson)??new();}catch(JsonException){return BadRequest(new{message="Mapping must be a JSON object."});}List<Dictionary<string,string>> rows;await using(var stream=file.OpenReadStream()){rows=ext==".csv"?await ReadCsv(stream,token):await ReadJson(stream,token);}if(rows.Count>5000)return BadRequest(new{message="A preview is limited to 5,000 rows."});var batch=Guid.NewGuid();var previews=new List<object>();var valid=0;var duplicates=0;await Exec("insert into integration_import_batches(id,connector_id,organization_id,branch_id,resource_type,file_name,file_format,status,mapping_json,total_rows,created_by) values(@id,@connector,@organization,@branch,@resource,@file,@format,'Preview',cast(@mapping as jsonb),@total,@actor)",c=>{Add(c,"id",batch);Add(c,"connector",connectorId);Add(c,"resource",resourceType);Add(c,"file",Path.GetFileName(file.FileName));Add(c,"format",ext[1..].ToUpperInvariant());Add(c,"mapping",JsonSerializer.Serialize(mapping));Add(c,"total",rows.Count);},token);for(var i=0;i<rows.Count;i++){var mapped=Map(rows[i],mapping);var errors=Validate(resourceType,mapped);var duplicate=await Duplicate(resourceType,mapped,token);if(duplicate)duplicates++;if(errors.Count==0)valid++;await Exec("insert into integration_import_rows(id,batch_id,row_number,source_json,mapped_json,validation_errors,duplicate_key,action) values(@id,@batch,@row,cast(@source as jsonb),cast(@mapped as jsonb),cast(@errors as jsonb),@duplicate,@action)",c=>{Add(c,"id",Guid.NewGuid());Add(c,"batch",batch);Add(c,"row",i+2);Add(c,"source",JsonSerializer.Serialize(rows[i]));Add(c,"mapped",JsonSerializer.Serialize(mapped));Add(c,"errors",JsonSerializer.Serialize(errors));Add(c,"duplicate",duplicate?DuplicateKey(resourceType,mapped):null);Add(c,"action",duplicate?"Skip":"Create");},token);previews.Add(new{rowNumber=i+2,mapped,errors,duplicate,action=duplicate?"Skip":"Create"});}await Exec("update integration_import_batches set valid_rows=@valid,invalid_rows=@invalid,duplicate_rows=@duplicates where id=@id",c=>{Add(c,"id",batch);Add(c,"valid",valid);Add(c,"invalid",rows.Count-valid);Add(c,"duplicates",duplicates);},token);return Ok(new{id=batch,totalRows=rows.Count,validRows=valid,invalidRows=rows.Count-valid,duplicateRows=duplicates,rows=previews.Take(100)});}
 [HttpGet("{id:guid}/errors.csv")]public async Task<IActionResult> Errors(Guid id,CancellationToken token){var result=new StringBuilder("row,errors\n");await using var c=await Command("select row_number,validation_errors::text from integration_import_rows r join integration_import_batches b on b.id=r.batch_id where b.id=@id and b.organization_id=@organization and r.validation_errors<>'[]'::jsonb order by row_number",token);Add(c,"id",id);await using var reader=await c.ExecuteReaderAsync(token);while(await reader.ReadAsync(token))result.Append(reader.GetInt32(0)).Append(',').Append('"').Append(reader.GetString(1).Replace("\"","\"\"")).Append("\"\n");return File(Encoding.UTF8.GetBytes(result.ToString()),"text/csv",$"import-{id}-errors.csv");}
 private static Dictionary<string,string> Map(Dictionary<string,string> row,Dictionary<string,string> mapping){var x=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);foreach(var item in mapping)if(row.TryGetValue(item.Key,out var value))x[item.Value]=value.Trim();return x;}
 private static List<string> Validate(string type,Dictionary<string,string> row){var required=type.ToLowerInvariant() switch{"people"=>new[]{"fullName","dateOfBirth","phoneNumber"},"workers"=>new[]{"fullName"},"visits"=>new[]{"serviceUserId","careWorkerId","startsAt","visitType"},"carerecords"=>new[]{"serviceUserId","summary"},_=>Array.Empty<string>()};var errors=required.Where(x=>!row.TryGetValue(x,out var v)||string.IsNullOrWhiteSpace(v)).Select(x=>$"{x} is required").ToList();if(required.Length==0)errors.Add("Unsupported resource type.");if(row.TryGetValue("dateOfBirth",out var dob)&&!DateOnly.TryParse(dob,out _))errors.Add("dateOfBirth is invalid");foreach(var key in new[]{"serviceUserId","careWorkerId"})if(row.TryGetValue(key,out var id)&&!Guid.TryParse(id,out _))errors.Add($"{key} is invalid");return errors;}
 private async Task<bool> Duplicate(string type,Dictionary<string,string> row,CancellationToken token){var key=DuplicateKey(type,row);if(string.IsNullOrEmpty(key))return false;var sql=type.ToLowerInvariant() switch{"people"=>"select count(*) from \"ServiceUsers\" where \"OrganizationId\"=@organization and lower(\"FullName\")=lower(@key)","workers"=>"select count(*) from \"CareWorkers\" where \"OrganizationId\"=@organization and lower(\"FullName\")=lower(@key)",_=>null};if(sql is null)return false;await using var c=await Command(sql,token);Add(c,"key",key);return Convert.ToInt32(await c.ExecuteScalarAsync(token))>0;}
 private static string? DuplicateKey(string type,Dictionary<string,string> row)=>type.ToLowerInvariant() is "people" or "workers"&&row.TryGetValue("fullName",out var value)?value:null;
 private static async Task<List<Dictionary<string,string>>> ReadJson(Stream s,CancellationToken t)=>await JsonSerializer.DeserializeAsync<List<Dictionary<string,string>>>(s,cancellationToken:t)??[];
 private static async Task<List<Dictionary<string,string>>> ReadCsv(Stream s,CancellationToken t){using var r=new StreamReader(s);var header=Parse(await r.ReadLineAsync(t)??"");var result=new List<Dictionary<string,string>>();while(await r.ReadLineAsync(t) is{ } line){var values=Parse(line);var row=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);for(var i=0;i<header.Count;i++)row[header[i]]=i<values.Count?values[i]:"";result.Add(row);}return result;}
 private static List<string> Parse(string line){var result=new List<string>();var value=new StringBuilder();var quoted=false;for(var i=0;i<line.Length;i++){var ch=line[i];if(ch=='"'){if(quoted&&i+1<line.Length&&line[i+1]=='"'){value.Append('"');i++;}else quoted=!quoted;}else if(ch==','&&!quoted){result.Add(value.ToString());value.Clear();}else value.Append(ch);}result.Add(value.ToString());return result;}
 private async Task<int> Exec(string sql,Action<DbCommand> bind,CancellationToken t){await using var c=await Command(sql,t);bind(c);return await c.ExecuteNonQueryAsync(t);}private async Task<DbCommand> Command(string sql,CancellationToken t){var cn=db.Database.GetDbConnection();if(cn.State!=ConnectionState.Open)await cn.OpenAsync(t);var c=cn.CreateCommand();c.CommandText=sql;Add(c,"organization",tenant.OrganizationId);Add(c,"branch",tenant.BranchId??TenantDefaults.BranchId);Add(c,"actor",user.UserName);return c;}private static void Add(DbCommand c,string n,object? v){if(c.Parameters.Contains(n))return;var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}
}
