using System.Text;
namespace AiCare.Api;
internal sealed record InvoicePdfData(string Number,DateOnly InvoiceDate,DateOnly DueDate,string Status,string Provider,string ProviderAddress,string ProviderEmail,string ProviderPhone,string CompanyNumber,string VatNumber,string Customer,string CustomerAddress,string Funder,string Terms,string Remittance,string Currency,decimal Net,decimal VatRate,decimal Vat,decimal Gross,decimal Paid,decimal Credits,string Exemption,IReadOnlyList<InvoicePdfLine> Lines);
internal sealed record InvoicePdfLine(string Description,decimal Quantity,decimal Rate,decimal Amount);
internal static class InvoicePdfDocument
{
 internal static byte[] Create(InvoicePdfData x){var rows=new List<string>{$"INVOICE {x.Number}",$"Status: {x.Status}",$"Invoice date: {x.InvoiceDate:yyyy-MM-dd}    Due date: {x.DueDate:yyyy-MM-dd}","",$"FROM: {x.Provider}",x.ProviderAddress,$"Email: {x.ProviderEmail}  Phone: {x.ProviderPhone}",$"Company: {x.CompanyNumber}  VAT: {x.VatNumber}","",$"BILL TO: {x.Customer}",x.CustomerAddress,$"Funder: {x.Funder}","","DESCRIPTION                         QTY       RATE       AMOUNT"};foreach(var l in x.Lines)rows.Add($"{Cut(l.Description,32),-32} {l.Quantity,8:0.00} {l.Rate,10:0.00} {l.Amount,12:0.00}");rows.AddRange(["",$"Net: {x.Currency} {x.Net:0.00}",$"VAT ({x.VatRate:0.##}%): {x.Currency} {x.Vat:0.00}",$"TOTAL: {x.Currency} {x.Gross:0.00}",$"Payments: {x.Currency} {x.Paid:0.00}",$"Credits: {x.Currency} {x.Credits:0.00}",$"BALANCE DUE: {x.Currency} {Math.Max(0,x.Gross-x.Paid-x.Credits):0.00}","",x.Terms,$"VAT note: {x.Exemption}","Remittance:",x.Remittance]);return Pdf(rows);}
 private static string Cut(string value,int n)=>value.Length<=n?value:value[..n];
 private static byte[] Pdf(IEnumerable<string> values){static string E(string v)=>v.Replace("\\","\\\\").Replace("(","\\(").Replace(")","\\)").Replace("\r","");var lines=values.SelectMany(v=>Wrap(v??"",88)).Take(55);var content="BT /F1 9 Tf 11 TL 40 760 Td "+string.Join(" T* ",lines.Select(x=>$"({E(ToAscii(x))})"))+" ET";var objects=new[]{"<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>","<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>",$"<< /Length {Encoding.ASCII.GetByteCount(content)} >>\nstream\n{content}\nendstream"};var b=new StringBuilder("%PDF-1.4\n");var offsets=new List<int>{0};for(var i=0;i<objects.Length;i++){offsets.Add(Encoding.ASCII.GetByteCount(b.ToString()));b.Append(i+1).Append(" 0 obj\n").Append(objects[i]).Append("\nendobj\n");}var xref=Encoding.ASCII.GetByteCount(b.ToString());b.Append("xref\n0 6\n0000000000 65535 f \n");foreach(var o in offsets.Skip(1))b.Append(o.ToString("0000000000")).Append(" 00000 n \n");b.Append("trailer << /Size 6 /Root 1 0 R >>\nstartxref\n").Append(xref).Append("\n%%EOF");return Encoding.ASCII.GetBytes(b.ToString());}
 private static IEnumerable<string> Wrap(string s,int n){if(s.Length==0){yield return "";yield break;}for(var i=0;i<s.Length;i+=n)yield return s.Substring(i,Math.Min(n,s.Length-i));}
 private static string ToAscii(string s)=>new(s.Select(c=>c<=127?c:'?').ToArray());
}
