using System.Data;using System.Data.Common;using AiCare.Application;using AiCare.Domain;using AiCare.Infrastructure;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Storage;
namespace AiCare.Api;
[ApiController,Authorize(Roles="Administrator,BackOffice")][Route("api/phase1/finance/invoice-runs")]
public sealed class InvoiceRunHistoryController(CareDbContext db,ITenantContext tenant,ICurrentUserContext user):ControllerBase
{
 Guid Branch=>tenant.BranchId??TenantDefaults.BranchId;
 [HttpGet]public async Task<IActionResult>List([FromQuery]Guid?funderId,[FromQuery]Guid?branchId,CancellationToken t){if(branchId is not null&&!tenant.IsOrganizationWide&&branchId!=tenant.BranchId)return NotFound();return Ok(await Rows("select r.id,r.period_start,r.period_end,r.funder_id,f.name funder_name,r.branch_id,r.status,r.event_count,r.invoice_count,r.total_amount,r.failure_reason,r.created_at,r.completed_at,r.cancelled_at,r.requested_by from finance_invoice_runs r left join finance_funders f on f.id=r.funder_id where r.organization_id=@org and (@wide or r.branch_id is null or r.branch_id=@branch) and (cast(@funder as uuid) is null or r.funder_id=@funder) and (cast(@filterBranch as uuid) is null or r.branch_id=@filterBranch) order by r.created_at desc",c=>{Add(c,"funder",funderId);Add(c,"filterBranch",branchId);},t));}
 [HttpGet("{id:guid}")]public async Task<IActionResult>Detail(Guid id,CancellationToken t){var runs=await Rows("select * from finance_invoice_runs where id=@id and organization_id=@org and (@wide or branch_id is null or branch_id=@branch)",c=>Add(c,"id",id),t);if(runs.Count==0)return NotFound();var invoices=await Rows("select i.\"Id\" id,d.invoice_number,d.customer_name,d.funder_name,d.currency,d.net_amount,d.vat_amount,d.gross_amount,i.\"Status\" status,count(l.id) line_count from finance_invoice_lines l join \"Invoices\" i on i.\"Id\"=l.invoice_id join finance_invoice_details d on d.invoice_id=i.\"Id\" where l.invoice_run_id=@id and l.organization_id=@org group by i.\"Id\",d.invoice_number,d.customer_name,d.funder_name,d.currency,d.net_amount,d.vat_amount,d.gross_amount,i.\"Status\" order by d.invoice_number",c=>Add(c,"id",id),t);return Ok(new{run=runs[0],invoices});}
 [HttpPost("{id:guid}/cancel")]public async Task<IActionResult>Cancel(Guid id,CancelInvoiceRunRequest r,CancellationToken t){if(string.IsNullOrWhiteSpace(r.Reason))return BadRequest(new{message="Cancellation reason is required."});var changed=await Exec("update finance_invoice_runs set status='Cancelled',cancelled_at=now(),cancelled_by=@actor,failure_reason=@reason where id=@id and organization_id=@org and (@wide or branch_id is null or branch_id=@branch) and status in ('Processing','Failed') and not exists(select 1 from finance_invoice_lines where invoice_run_id=@id)",c=>{Add(c,"id",id);Add(c,"reason",r.Reason.Trim());},t);if(changed==0)return Conflict(new{message="Only an unclaimed processing or failed run can be cancelled."});db.AuditEvents.Add(new AuditEvent(Guid.NewGuid(),"INVOICE_RUN_CANCELLED",user.UserName,"InvoiceRun",id,DateTimeOffset.UtcNow,tenant.OrganizationId,Branch));await db.SaveChangesAsync(t);return NoContent();}
 async Task<List<Dictionary<string,object?>>>Rows(string s,Action<DbCommand>b,CancellationToken t){var a=new List<Dictionary<string,object?>>();await using var c=await Cmd(s,t);b(c);await using var r=await c.ExecuteReaderAsync(t);while(await r.ReadAsync(t)){var d=new Dictionary<string,object?>();for(var i=0;i<r.FieldCount;i++)d[r.GetName(i)]=r.IsDBNull(i)?null:r.GetValue(i);a.Add(d);}return a;}async Task<int>Exec(string s,Action<DbCommand>b,CancellationToken t){await using var c=await Cmd(s,t);b(c);return await c.ExecuteNonQueryAsync(t);}async Task<DbCommand>Cmd(string s,CancellationToken t){var n=db.Database.GetDbConnection();if(n.State!=ConnectionState.Open)await n.OpenAsync(t);var c=n.CreateCommand();c.Transaction=db.Database.CurrentTransaction?.GetDbTransaction();c.CommandText=s;Add(c,"org",tenant.OrganizationId);Add(c,"branch",Branch);Add(c,"wide",tenant.IsOrganizationWide);Add(c,"actor",user.UserName);return c;}static void Add(DbCommand c,string n,object?v){if(c.Parameters.Contains(n))return;var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}
}
public sealed record CancelInvoiceRunRequest(string Reason);
