using System.Data;using System.Data.Common;using AiCare.Application;using AiCare.Domain;using AiCare.Infrastructure;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Storage;
namespace AiCare.Api;
[ApiController,Authorize(Roles="Administrator,BackOffice")][Route("api/phase1/finance/invoice-runs")]
public sealed class InvoiceRunsController(CareDbContext db,ITenantContext tenant,ICurrentUserContext user):ControllerBase
{
 Guid Branch=>tenant.BranchId??TenantDefaults.BranchId;
 [HttpPost("preview")]
 public async Task<IActionResult> Preview(InvoiceRunRequest r,CancellationToken t){if(r.PeriodStart>r.PeriodEnd)return BadRequest(new{message="Invalid invoice period."});var rows=await Eligible(r,t);return Ok(new{eventCount=rows.Count,invoiceCount=rows.Select(x=>(x.ServiceUserId,x.FunderId)).Distinct().Count(),totalAmount=rows.Sum(x=>x.Amount),events=rows});}
 [HttpPost]
 public async Task<IActionResult> Generate(InvoiceRunRequest r,CancellationToken t){if(r.PeriodStart>r.PeriodEnd||string.IsNullOrWhiteSpace(r.IdempotencyKey))return BadRequest(new{message="Valid period and idempotency key are required."});return await db.Database.CreateExecutionStrategy().ExecuteAsync<IActionResult>(async()=>{await using var tx=await db.Database.BeginTransactionAsync(t);await Exec("select pg_advisory_xact_lock(hashtextextended(@lock,0))",c=>Add(c,"lock",$"invoice-run:{tenant.OrganizationId}"),t);var existing=await Query("select id,status,event_count,invoice_count,total_amount from finance_invoice_runs where organization_id=@organization and idempotency_key=@key",c=>Add(c,"key",r.IdempotencyKey),x=>new{Id=x.GetGuid(0),Status=x.GetString(1),Events=x.GetInt32(2),Invoices=x.GetInt32(3),Total=x.GetDecimal(4)},t);if(existing.Count>0){await tx.RollbackAsync(t);return Ok(existing[0]);}var events=await Eligible(r,t);if(events.Count==0){await tx.RollbackAsync(t);return Conflict(new{message="No approved uninvoiced billable events are available."});}var run=Guid.NewGuid();await Exec("insert into finance_invoice_runs(id,organization_id,branch_id,period_start,period_end,funder_id,status,requested_by,idempotency_key) values(@id,@organization,@runBranch,@start,@end,@funder,'Processing',@actor,@key)",c=>{Add(c,"id",run);Add(c,"runBranch",tenant.IsOrganizationWide?null:Branch);Add(c,"start",r.PeriodStart);Add(c,"end",r.PeriodEnd);Add(c,"funder",r.FunderId);Add(c,"key",r.IdempotencyKey);},t);var profile=await Profile(t);var invoices=0;
 foreach(var group in events.GroupBy(x=>new{x.ServiceUserId,x.FunderId,x.FunderName,x.Currency,x.BranchId})){var person=await db.ServiceUsers.AsNoTracking().SingleAsync(x=>x.Id==group.Key.ServiceUserId&&x.OrganizationId==tenant.OrganizationId,t);var net=group.Sum(x=>x.Amount);var vat=Math.Round(net*profile.VatRate/100m,2,MidpointRounding.AwayFromZero);var gross=net+vat;var invoiceDate=DateOnly.FromDateTime(DateTime.UtcNow);var number=await NextNumber(invoiceDate.Year,t);var invoice=new Invoice(Guid.NewGuid(),group.Key.ServiceUserId,group.Key.FunderName,gross,"Generated",DateTimeOffset.UtcNow,tenant.OrganizationId,group.Key.BranchId);db.Invoices.Add(invoice);await db.SaveChangesAsync(t);await Exec("""insert into finance_invoice_details(invoice_id,organization_id,branch_id,invoice_number,invoice_date,due_date,payment_terms,provider_name,provider_address,provider_email,provider_phone,company_number,vat_number,customer_name,customer_address,funder_name,remittance_details,currency,net_amount,vat_rate,vat_amount,gross_amount,vat_exemption_reason) values(@invoice,@organization,@lineBranch,@number,@date,@due,@terms,@provider,@address,@email,@phone,@company,@vatNumber,@customer,@customerAddress,@funderName,@remittance,@currency,@net,@vatRate,@vat,@gross,@exemption)""",c=>{Add(c,"invoice",invoice.Id);Add(c,"lineBranch",group.Key.BranchId);Add(c,"number",number);Add(c,"date",invoiceDate);Add(c,"due",invoiceDate.AddDays(profile.Terms));Add(c,"terms",$"Payment due within {profile.Terms} days");Add(c,"provider",profile.Name);Add(c,"address",profile.Address);Add(c,"email",profile.Email);Add(c,"phone",profile.Phone);Add(c,"company",profile.Company);Add(c,"vatNumber",profile.VatNumber);Add(c,"customer",person.FullName);Add(c,"customerAddress",person.Address);Add(c,"funderName",group.Key.FunderName);Add(c,"remittance",profile.Remittance);Add(c,"currency",group.Key.Currency);Add(c,"net",net);Add(c,"vatRate",profile.VatRate);Add(c,"vat",vat);Add(c,"gross",gross);Add(c,"exemption",profile.Exemption);},t);
  foreach(var e in group){await Exec("""insert into finance_invoice_lines(id,invoice_id,visit_id,service_user_id,organization_id,branch_id,description,quantity,unit_rate,amount,funding_source,billable_event_id,invoice_run_id) values(@line,@invoice,@visit,@person,@organization,@lineBranch,@description,@quantity,@rate,@amount,@funding,@event,@run)""",c=>{Add(c,"line",Guid.NewGuid());Add(c,"invoice",invoice.Id);Add(c,"visit",e.VisitId);Add(c,"person",e.ServiceUserId);Add(c,"lineBranch",e.BranchId);Add(c,"description",e.Description);Add(c,"quantity",e.Quantity);Add(c,"rate",e.UnitRate);Add(c,"amount",e.Amount);Add(c,"funding",e.FunderName);Add(c,"event",e.Id);Add(c,"run",run);},t);await Exec("update finance_billable_events set status='Invoiced',revision=revision+1 where id=@event and status='Approved'",c=>Add(c,"event",e.Id),t);}invoices++;}
 var total=events.Sum(x=>x.Amount);await Exec("update finance_invoice_runs set status='Completed',completed_at=now(),event_count=@events,invoice_count=@invoices,total_amount=@total where id=@run",c=>{Add(c,"run",run);Add(c,"events",events.Count);Add(c,"invoices",invoices);Add(c,"total",total);},t);Audit("INVOICE_RUN_CREATED","InvoiceRun",run);await db.SaveChangesAsync(t);await tx.CommitAsync(t);return Created($"/api/phase1/finance/invoice-runs/{run}",new{id=run,status="Completed",eventCount=events.Count,invoiceCount=invoices,totalAmount=total});});}
 async Task<List<EligibleEvent>> Eligible(InvoiceRunRequest r,CancellationToken t)=>await Query("""select e.id,e.visit_id,e.service_user_id,e.funder_id,f.name,e.branch_id,e.service_date,e.quantity,e.unit_rate,e.final_amount,e.currency,coalesce(v."VisitType",'Care service') from finance_billable_events e join finance_funders f on f.id=e.funder_id left join "Visits" v on v."Id"=e.visit_id where e.organization_id=@organization and (@wide or e.branch_id=@branch) and e.status='Approved' and e.service_date between @start and @end and (@funder is null or e.funder_id=@funder) and not exists(select 1 from finance_invoice_lines l where l.organization_id=e.organization_id and l.billable_event_id=e.id) order by e.service_date,e.id""",c=>{Add(c,"start",r.PeriodStart);Add(c,"end",r.PeriodEnd);Add(c,"funder",r.FunderId);},x=>new EligibleEvent(x.GetGuid(0),x.GetGuid(1),x.GetGuid(2),x.GetGuid(3),x.GetString(4),x.GetGuid(5),x.GetFieldValue<DateOnly>(6),x.GetDecimal(7),x.GetDecimal(8),x.GetDecimal(9),x.GetString(10).Trim(),x.GetString(11)),t);
 async Task<ProfileRow> Profile(CancellationToken t){var x=await Query("select provider_name,provider_address,provider_email,provider_phone,company_number,vat_number,remittance_details,default_payment_terms_days,default_vat_rate,vat_exemption_reason from finance_invoice_profiles where organization_id=@organization and branch_id=@branch",_=>{},r=>new ProfileRow(r.GetString(0),r.GetString(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetInt32(7),r.GetDecimal(8),r.GetString(9)),t);if(x.Count>0)return x[0];var org=await db.Organizations.AsNoTracking().SingleAsync(o=>o.Id==tenant.OrganizationId,t);return new(org.Name,"","","","","","",30,0,"VAT not charged");}
 async Task<string> NextNumber(int year,CancellationToken t){await using var c=await Command("insert into finance_invoice_sequences(organization_id,invoice_year,next_value) values(@organization,@year,2) on conflict(organization_id,invoice_year) do update set next_value=finance_invoice_sequences.next_value+1 returning next_value-1",t);Add(c,"year",year);return $"INV-{year}-{Convert.ToInt64(await c.ExecuteScalarAsync(t)):000000}";}
 async Task<int> Exec(string s,Action<DbCommand>b,CancellationToken t){await using var c=await Command(s,t);b(c);return await c.ExecuteNonQueryAsync(t);}async Task<List<T>> Query<T>(string s,Action<DbCommand>b,Func<DbDataReader,T>m,CancellationToken t){var a=new List<T>();await using var c=await Command(s,t);b(c);await using var d=await c.ExecuteReaderAsync(t);while(await d.ReadAsync(t))a.Add(m(d));return a;}async Task<DbCommand> Command(string s,CancellationToken t){var n=db.Database.GetDbConnection();if(n.State!=ConnectionState.Open)await n.OpenAsync(t);var c=n.CreateCommand();c.Transaction=db.Database.CurrentTransaction?.GetDbTransaction();c.CommandText=s;Add(c,"organization",tenant.OrganizationId);Add(c,"branch",Branch);Add(c,"wide",tenant.IsOrganizationWide);Add(c,"actor",user.UserName);return c;}static void Add(DbCommand c,string n,object?v){if(c.Parameters.Contains(n))return;var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}void Audit(string a,string e,Guid?id)=>db.AuditEvents.Add(new AuditEvent(Guid.NewGuid(),a,user.UserName,e,id,DateTimeOffset.UtcNow,tenant.OrganizationId,Branch));
 sealed record EligibleEvent(Guid Id,Guid VisitId,Guid ServiceUserId,Guid FunderId,string FunderName,Guid BranchId,DateOnly Date,decimal Quantity,decimal UnitRate,decimal Amount,string Currency,string Description);sealed record ProfileRow(string Name,string Address,string Email,string Phone,string Company,string VatNumber,string Remittance,int Terms,decimal VatRate,string Exemption);
}
public sealed record InvoiceRunRequest(DateOnly PeriodStart,DateOnly PeriodEnd,Guid? FunderId,string IdempotencyKey="preview");
