using System.Security.Cryptography;
using System.Text;

namespace AiCare.Api;

internal static class MfaSecurity
{
    public static string GenerateSecret() { const string alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"; var bytes = RandomNumberGenerator.GetBytes(20); var output = new StringBuilder(); int buffer = bytes[0], next = 1, bits = 8; while (bits > 0 || next < bytes.Length) { if (bits < 5) { if (next < bytes.Length) { buffer = (buffer << 8) | bytes[next++]; bits += 8; } else { buffer <<= 5 - bits; bits = 5; } } output.Append(alphabet[(buffer >> (bits - 5)) & 31]); bits -= 5; } return output.ToString(); }
    public static bool VerifyTotp(string secret, string? code, DateTimeOffset? now = null) { if (string.IsNullOrWhiteSpace(secret) || string.IsNullOrWhiteSpace(code) || code.Length != 6) return false; var key = Decode(secret); var counter = (now ?? DateTimeOffset.UtcNow).ToUnixTimeSeconds() / 30; for (long offset = -1; offset <= 1; offset++) { var bytes = BitConverter.GetBytes(counter + offset); if (BitConverter.IsLittleEndian) Array.Reverse(bytes); using var hmac = new HMACSHA1(key); var hash = hmac.ComputeHash(bytes); var index = hash[^1] & 15; var binary = ((hash[index] & 127) << 24) | ((hash[index + 1] & 255) << 16) | ((hash[index + 2] & 255) << 8) | (hash[index + 3] & 255); var expected = (binary % 1_000_000).ToString("D6"); if (CryptographicOperations.FixedTimeEquals(Encoding.ASCII.GetBytes(expected), Encoding.ASCII.GetBytes(code))) return true; } return false; }
    public static string Protect(string secret, string keyMaterial) { var key = SHA256.HashData(Encoding.UTF8.GetBytes("AiCare.MFA.Secret.v1|" + keyMaterial)); var nonce = RandomNumberGenerator.GetBytes(12); var plain = Encoding.UTF8.GetBytes(secret); var cipher = new byte[plain.Length]; var tag = new byte[16]; using var aes = new AesGcm(key, 16); aes.Encrypt(nonce, plain, cipher, tag); return $"v1:{Convert.ToBase64String(nonce)}:{Convert.ToBase64String(tag)}:{Convert.ToBase64String(cipher)}"; }
    public static string Unprotect(string value, string keyMaterial) { if (!value.StartsWith("v1:", StringComparison.Ordinal)) return value; var parts = value.Split(':'); var key = SHA256.HashData(Encoding.UTF8.GetBytes("AiCare.MFA.Secret.v1|" + keyMaterial)); var cipher = Convert.FromBase64String(parts[3]); var plain = new byte[cipher.Length]; using var aes = new AesGcm(key, 16); aes.Decrypt(Convert.FromBase64String(parts[1]), cipher, Convert.FromBase64String(parts[2]), plain); return Encoding.UTF8.GetString(plain); }
    public static string GenerateRecoveryCode() { const string chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; var bytes = RandomNumberGenerator.GetBytes(12); return string.Create(14, bytes, (span, random) => { var p = 0; for (var i = 0; i < 12; i++) { if (i is 4 or 8) span[p++] = '-'; span[p++] = chars[random[i] % chars.Length]; } }); }
    public static string HashRecoveryCode(string code, Guid userId, string keyMaterial) => Convert.ToHexString(HMACSHA256.HashData(SHA256.HashData(Encoding.UTF8.GetBytes(keyMaterial)), Encoding.UTF8.GetBytes($"{userId:N}|{Normalize(code)}")));
    public static string Normalize(string code) => code.Replace("-", "", StringComparison.Ordinal).Trim().ToUpperInvariant();
    private static byte[] Decode(string value) { const string alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"; var output = new List<byte>(); int buffer = 0, bits = 0; foreach (var ch in value.ToUpperInvariant()) { var v = alphabet.IndexOf(ch); if (v < 0) continue; buffer = (buffer << 5) | v; bits += 5; if (bits >= 8) { output.Add((byte)(buffer >> (bits - 8))); bits -= 8; buffer &= (1 << bits) - 1; } } return output.ToArray(); }
}
