using System.Data.Common;
using AiCare.Application;
using AiCare.Domain;
using AiCare.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AiCare.Api;

[ApiController]
[Authorize(Roles="CareCoordinator,CareManager,Administrator")]
[Route("api/phase1/person-lifecycle")]
public sealed class PersonLifecycleController(CareDbContext db,ITenantContext tenant,ICurrentUserContext user):ControllerBase
{
    [HttpGet("dashboard")]
    public async Task<IActionResult> Dashboard(CancellationToken t)=>Ok(new{
        referrals=await Query("select id,service_user_id,referral_source,priority,status,screening_due_at,owner,received_at from person_referrals where organization_id=@organization and status not in ('Accepted','Declined','Closed') order by received_at desc limit 50",_=>{},r=>new ReferralQueueItem(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetString(3),r.GetString(4),r.IsDBNull(5)?null:r.GetFieldValue<DateTimeOffset>(5),r.GetString(6),r.GetFieldValue<DateTimeOffset>(7)),t),
        overdueReviews=await Query("select id,service_user_id,checkpoint_type,status,due_at,owner from person_review_checkpoints where organization_id=@organization and status='Open' and due_at<now() order by due_at limit 50",_=>{},r=>new ReviewQueueItem(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetString(3),r.GetFieldValue<DateTimeOffset>(4),r.GetString(5)),t),
        statusCounts=await Query("select \"Status\",count(*)::int from \"ServiceUsers\" where \"OrganizationId\"=@organization group by \"Status\" order by \"Status\"",_=>{},r=>new StatusCount(r.GetString(0),r.GetInt32(1)),t)});

    [HttpGet("service-users/{personId:guid}")]
    public async Task<IActionResult> Summary(Guid personId,CancellationToken t){var person=await FindPerson(personId,t);if(person is null)return NotFound();return Ok(new{person.Id,person.FullName,person.Status,referrals=await Referrals(personId,t),events=await Events(personId,t),reviews=await Reviews(personId,t)});}

    [HttpPost("service-users/{personId:guid}/referrals")]
    public async Task<IActionResult> CreateReferral(Guid personId,CreateReferralRequest request,CancellationToken t){var person=await FindPerson(personId,t);if(person is null)return NotFound();if(Missing(request.ReferralSource)||Missing(request.ReferralReason))return BadRequest(new{message="Referral source and reason are required."});var id=Guid.NewGuid();await Exec("insert into person_referrals(id,service_user_id,organization_id,branch_id,referral_source,referrer_name,referrer_contact,referral_reason,priority,status,received_at,screening_due_at,owner,created_by) values(@id,@person,@organization,@branch,@source,@name,@contact,@reason,@priority,'Received',@received,@due,@owner,@actor)",c=>{Add(c,"id",id);Add(c,"person",personId);Add(c,"source",request.ReferralSource.Trim());Add(c,"name",request.ReferrerName?.Trim()??"");Add(c,"contact",request.ReferrerContact?.Trim()??"");Add(c,"reason",request.ReferralReason.Trim());Add(c,"priority",Clean(request.Priority,"Routine"));Add(c,"received",request.ReceivedAt??DateTimeOffset.UtcNow);Add(c,"due",request.ScreeningDueAt);Add(c,"owner",request.Owner?.Trim()??user.UserName);},t);await RecordEvent(person,"ReferralReceived",person.Status,"Referred",request.ReferralReason,t);await SetStatus(person,"Referred",request.ReferralReason,t);Audit("person_referral.created","PersonReferral",id);await db.SaveChangesAsync(t);return Created($"/api/phase1/person-lifecycle/service-users/{personId}/referrals/{id}",new{id});}

    [HttpPatch("referrals/{id:guid}")]
    public async Task<IActionResult> ProgressReferral(Guid id,ProgressReferralRequest request,CancellationToken t){if(request.Status is not("Screening" or "Accepted" or "Declined" or "Closed"))return BadRequest(new{message="Referral status must be Screening, Accepted, Declined, or Closed."});var row=await Query("select service_user_id,status from person_referrals where id=@id and organization_id=@organization",c=>Add(c,"id",id),r=>new{PersonId=r.GetGuid(0),Status=r.GetString(1)},t);if(row.Count==0)return NotFound();var person=await FindPerson(row[0].PersonId,t);if(person is null)return NotFound();await Exec("update person_referrals set status=@status,outcome=@outcome,closure_reason=@closure,owner=@owner,updated_at=now() where id=@id and organization_id=@organization",c=>{Add(c,"id",id);Add(c,"status",request.Status);Add(c,"outcome",request.Outcome?.Trim()??"");Add(c,"closure",request.ClosureReason?.Trim()??"");Add(c,"owner",request.Owner?.Trim()??user.UserName);},t);var next=request.Status=="Accepted"?"Assessment":request.Status=="Declined"?"Closed":"Referred";await RecordEvent(person,"Referral"+request.Status,person.Status,next,request.Outcome??request.Status,t);await SetStatus(person,next,request.Outcome??request.Status,t);Audit("person_referral.progressed","PersonReferral",id);await db.SaveChangesAsync(t);return NoContent();}

    [HttpPost("service-users/{personId:guid}/status")]
    public async Task<IActionResult> ChangeStatus(Guid personId,ChangePersonStatusRequest request,CancellationToken t){var person=await FindPerson(personId,t);if(person is null)return NotFound();var allowed=new[]{"Referred","Assessment","Onboarding","Active","Suspended","Discharged","Archived"};if(!allowed.Contains(request.Status,StringComparer.OrdinalIgnoreCase))return BadRequest(new{message="Unsupported lifecycle status."});if(Missing(request.Reason))return BadRequest(new{message="Reason is required for lifecycle status changes."});await RecordEvent(person,"StatusChanged",person.Status,request.Status,request.Reason,t);await SetStatus(person,request.Status,request.Reason,t);if(request.Status.Equals("Discharged",StringComparison.OrdinalIgnoreCase))await MarkDischarged(personId,request.EffectiveAt??DateTimeOffset.UtcNow,t);await db.SaveChangesAsync(t);return NoContent();}

    [HttpPost("service-users/{personId:guid}/reviews")]
    public async Task<IActionResult> CreateReview(Guid personId,CreateReviewCheckpointRequest request,CancellationToken t){if(await FindPerson(personId,t) is null)return NotFound();if(Missing(request.CheckpointType)||request.DueAt==default)return BadRequest(new{message="Checkpoint type and due date are required."});var id=Guid.NewGuid();await Exec("insert into person_review_checkpoints(id,service_user_id,organization_id,branch_id,checkpoint_type,status,due_at,owner,notes,created_by) values(@id,@person,@organization,@branch,@type,'Open',@due,@owner,@notes,@actor)",c=>{Add(c,"id",id);Add(c,"person",personId);Add(c,"type",request.CheckpointType.Trim());Add(c,"due",request.DueAt);Add(c,"owner",request.Owner?.Trim()??user.UserName);Add(c,"notes",request.Notes?.Trim()??"");},t);Audit("person_review.created","PersonReviewCheckpoint",id);await db.SaveChangesAsync(t);return Created($"/api/phase1/person-lifecycle/service-users/{personId}/reviews/{id}",new{id});}

    [HttpPatch("reviews/{id:guid}")]
    public async Task<IActionResult> CompleteReview(Guid id,CompleteReviewCheckpointRequest request,CancellationToken t){if(Missing(request.Outcome))return BadRequest(new{message="Review outcome is required."});var n=await Exec("update person_review_checkpoints set status='Completed',completed_at=now(),outcome=@outcome,notes=@notes,updated_at=now() where id=@id and organization_id=@organization and status='Open'",c=>{Add(c,"id",id);Add(c,"outcome",request.Outcome.Trim());Add(c,"notes",request.Notes?.Trim()??"");},t);if(n==0)return NotFound();Audit("person_review.completed","PersonReviewCheckpoint",id);await db.SaveChangesAsync(t);return NoContent();}

    private async Task<ServiceUser?> FindPerson(Guid id,CancellationToken t){var p=await db.ServiceUsers.SingleOrDefaultAsync(x=>x.Id==id,t);return p is not null&&tenant.CanAccess(p.OrganizationId,p.BranchId)?p:null;}
    private async Task SetStatus(ServiceUser person,string status,string reason,CancellationToken t){if(person.Status.Equals(status,StringComparison.OrdinalIgnoreCase))return;db.Entry(person).State=EntityState.Detached;db.ServiceUsers.Update(person with{Status=status});Audit("service_user.status_changed","ServiceUser",person.Id);await Task.CompletedTask;}
    private async Task MarkDischarged(Guid personId,DateTimeOffset at,CancellationToken t)=>await Exec("update \"PersonRecords\" set \"DischargedAt\"=@at,\"LastReviewedAt\"=now() where \"ServiceUserId\"=@person and \"OrganizationId\"=@organization",c=>{Add(c,"person",personId);Add(c,"at",at);},t);
    private async Task RecordEvent(ServiceUser person,string type,string oldStatus,string newStatus,string reason,CancellationToken t)=>await Exec("insert into person_lifecycle_events(id,service_user_id,organization_id,branch_id,event_type,old_status,new_status,reason,effective_at,created_by) values(@id,@person,@organization,@branch,@type,@old,@new,@reason,now(),@actor)",c=>{Add(c,"id",Guid.NewGuid());Add(c,"person",person.Id);Add(c,"type",type);Add(c,"old",oldStatus);Add(c,"new",newStatus);Add(c,"reason",reason);},t);
    private Task<List<ReferralResponse>> Referrals(Guid id,CancellationToken t)=>Query("select id,service_user_id,referral_source,referrer_name,referrer_contact,referral_reason,priority,status,received_at,screening_due_at,owner,outcome,closure_reason from person_referrals where service_user_id=@person and organization_id=@organization order by received_at desc",c=>Add(c,"person",id),r=>new ReferralResponse(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetString(7),r.GetFieldValue<DateTimeOffset>(8),r.IsDBNull(9)?null:r.GetFieldValue<DateTimeOffset>(9),r.GetString(10),r.GetString(11),r.GetString(12)),t);
    private Task<List<LifecycleEventResponse>> Events(Guid id,CancellationToken t)=>Query("select id,service_user_id,event_type,old_status,new_status,reason,effective_at,created_by,created_at from person_lifecycle_events where service_user_id=@person and organization_id=@organization order by created_at desc",c=>Add(c,"person",id),r=>new LifecycleEventResponse(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetString(5),r.GetFieldValue<DateTimeOffset>(6),r.GetString(7),r.GetFieldValue<DateTimeOffset>(8)),t);
    private Task<List<ReviewCheckpointResponse>> Reviews(Guid id,CancellationToken t)=>Query("select id,service_user_id,checkpoint_type,status,due_at,completed_at,owner,outcome,notes from person_review_checkpoints where service_user_id=@person and organization_id=@organization order by due_at desc",c=>Add(c,"person",id),r=>new ReviewCheckpointResponse(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetString(3),r.GetFieldValue<DateTimeOffset>(4),r.IsDBNull(5)?null:r.GetFieldValue<DateTimeOffset>(5),r.GetString(6),r.GetString(7),r.GetString(8)),t);
    private void Audit(string action,string entity,Guid id)=>db.AuditEvents.Add(new AuditEvent(Guid.NewGuid(),action,user.UserName,entity,id,DateTimeOffset.UtcNow,tenant.OrganizationId,tenant.BranchId??TenantDefaults.BranchId));
    private async Task<int> Exec(string sql,Action<DbCommand> bind,CancellationToken t){await using var c=await Command(sql,t);bind(c);return await c.ExecuteNonQueryAsync(t);}private async Task<List<T>> Query<T>(string sql,Action<DbCommand> bind,Func<DbDataReader,T> map,CancellationToken t){var a=new List<T>();await using var c=await Command(sql,t);bind(c);await using var r=await c.ExecuteReaderAsync(t);while(await r.ReadAsync(t))a.Add(map(r));return a;}
    private async Task<DbCommand> Command(string sql,CancellationToken t){var cn=db.Database.GetDbConnection();if(cn.State!=System.Data.ConnectionState.Open)await cn.OpenAsync(t);var c=cn.CreateCommand();c.CommandText=sql;Add(c,"organization",tenant.OrganizationId);Add(c,"branch",tenant.BranchId??TenantDefaults.BranchId);Add(c,"actor",user.UserName);return c;}private static void Add(DbCommand c,string n,object? v){if(c.Parameters.Contains(n))return;var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}private static bool Missing(string? v)=>string.IsNullOrWhiteSpace(v);private static string Clean(string? v,string d)=>string.IsNullOrWhiteSpace(v)?d:v.Trim();
}
public sealed record CreateReferralRequest(string ReferralSource,string? ReferrerName,string? ReferrerContact,string ReferralReason,string? Priority,DateTimeOffset? ReceivedAt,DateTimeOffset? ScreeningDueAt,string? Owner);
public sealed record ProgressReferralRequest(string Status,string? Outcome,string? ClosureReason,string? Owner);
public sealed record ChangePersonStatusRequest(string Status,string Reason,DateTimeOffset? EffectiveAt);
public sealed record CreateReviewCheckpointRequest(string CheckpointType,DateTimeOffset DueAt,string? Owner,string? Notes);
public sealed record CompleteReviewCheckpointRequest(string Outcome,string? Notes);
public sealed record ReferralResponse(Guid Id,Guid ServiceUserId,string ReferralSource,string ReferrerName,string ReferrerContact,string ReferralReason,string Priority,string Status,DateTimeOffset ReceivedAt,DateTimeOffset? ScreeningDueAt,string Owner,string Outcome,string ClosureReason);
public sealed record LifecycleEventResponse(Guid Id,Guid ServiceUserId,string EventType,string OldStatus,string NewStatus,string Reason,DateTimeOffset EffectiveAt,string CreatedBy,DateTimeOffset CreatedAt);
public sealed record ReviewCheckpointResponse(Guid Id,Guid ServiceUserId,string CheckpointType,string Status,DateTimeOffset DueAt,DateTimeOffset? CompletedAt,string Owner,string Outcome,string Notes);
public sealed record ReferralQueueItem(Guid Id,Guid ServiceUserId,string ReferralSource,string Priority,string Status,DateTimeOffset? ScreeningDueAt,string Owner,DateTimeOffset ReceivedAt);
public sealed record ReviewQueueItem(Guid Id,Guid ServiceUserId,string CheckpointType,string Status,DateTimeOffset DueAt,string Owner);
public sealed record StatusCount(string Status,int Count);
