using System.Data;
using System.Data.Common;
using AiCare.Application;
using AiCare.Domain;
using AiCare.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AiCare.Api;

[ApiController]
[Authorize(Policy="Phase1User")]
[Route("api/phase1/emar-safety")]
public sealed class ProductionEmarController(CareDbContext db,ITenantContext tenant,ICurrentUserContext user,IConfiguration configuration):ControllerBase
{
 [HttpGet("witnesses")]
 public async Task<IActionResult> Witnesses(CancellationToken token)=>Ok(await db.AppUsers.AsNoTracking().Where(x=>x.OrganizationId==tenant.OrganizationId&&x.IsActive&&x.Id!=user.UserId&&(x.Role==UserRole.Administrator||x.Role==UserRole.CareManager||x.Role==UserRole.CareCoordinator||x.Role==UserRole.CareWorker)).OrderBy(x=>x.UserName).Select(x=>new{x.Id,x.UserName,x.Role}).ToListAsync(token));

 [HttpGet("mar/{marId:guid}/history")]
 public async Task<IActionResult> History(Guid marId,CancellationToken token){var mar=await Mar(marId,token);if(mar is null)return NotFound();if(!CanRecord(mar.Value.Worker))return Forbid();return Ok(new{entries=await Ledger(marId,token),escalations=await Escalations(marId,token)});}

 [HttpPost("mar/{marId:guid}/record")]
 public async Task<IActionResult> Record(Guid marId,EmarRecordRequest request,CancellationToken token)
 {
  if(!EmarProductionEnabled())return await Block(marId,"emar.disabled_or_rollback","eMAR administration is disabled until the medication clinical-safety gate is approved.",StatusCodes.Status423Locked,token);
  var idempotencyKey=Request.Headers["Idempotency-Key"].ToString();if(Missing(idempotencyKey)){await AuditNow("emar.failed_submission",marId,token);return BadRequest(new{message="Idempotency-Key is required for eMAR administration submissions."});}if(await TryGetIdempotentLedger("POST /api/phase1/emar-safety/mar/record",idempotencyKey,token) is { } replay){await AuditNow("emar.idempotent_replay",marId,token);return Ok(replay);}
  var mar=await Mar(marId,token);if(mar is null)return NotFound();if(!CanRecord(mar.Value.Worker)){await AuditNow("emar.unauthorized_role_attempt",marId,token);return Forbid();}var medicationAuthorization=await MedicationAuthorization(mar.Value.Worker,mar.Value.Route,token);if(medicationAuthorization is not null)return await ConflictBlock(marId,medicationAuthorization.Contains("competency",StringComparison.OrdinalIgnoreCase)?"emar.competency_block":"emar.worker_authorization_block",medicationAuthorization,token);if(mar.Value.Outcome!="Scheduled")return await ConflictBlock(marId,"emar.failed_submission","A terminal MAR outcome already exists.",token);
  var outcome=request.Outcome.Trim();if(outcome is not("Administered" or "Omitted" or "Refused"))return BadRequest(new{message="Outcome must be Administered, Omitted, or Refused."});var serverNow=DateTimeOffset.UtcNow;var occurred=request.OccurredAt??serverNow;if(occurred>serverNow.AddMinutes(5))return Conflict(new{message="Dose occurrence time cannot be in the future; server time is authoritative."});if(occurred<mar.Value.Scheduled.AddHours(-24)&&string.IsNullOrWhiteSpace(request.OverrideReason))return Conflict(new{message="Dose occurrence time is too far before the scheduled time; a documented override is required."});
  var profile=await Profile(mar.Value.Medication,token);if(profile is null||Missing(profile.Value.Indication,profile.Value.Prescriber,profile.Value.ReconciledBy)||profile.Value.ReconciledAt is null)return await ConflictBlock(marId,"emar.blocked_unverified_medication","A complete reconciled medication safety profile is required.",token);if(profile.Value.ReconciliationStatus!="Verified")return await ConflictBlock(marId,"emar.blocked_unverified_medication",$"Medication reconciliation status must be Verified before administration. Current status: {profile.Value.ReconciliationStatus}.",token);
  if(profile.Value.Start is not null&&occurred<profile.Value.Start||profile.Value.End is not null&&occurred>profile.Value.End)return await ConflictBlock(marId,"emar.failed_submission","Medication is outside its prescribed active dates.",token);var medicationSafety=await MedicationSafety(mar.Value.Medication,mar.Value.Person,token);if(medicationSafety.AllergyConflict is not null)return await ConflictBlock(marId,"emar.allergy_block",medicationSafety.AllergyConflict,token);if(medicationSafety.DuplicateConflict is not null)return await ConflictBlock(marId,"emar.duplicate_medication_block",medicationSafety.DuplicateConflict,token);
  var minutes=Math.Abs((occurred-mar.Value.Scheduled).TotalMinutes);if(minutes>profile.Value.Window&&string.IsNullOrWhiteSpace(request.OverrideReason))return Conflict(new{message="Dose is outside its administration window; a documented override is required."});if(minutes>profile.Value.Window&&!user.HasAnyRole(UserRole.CareManager,UserRole.Administrator))return Forbid();
  if(outcome!="Administered"){var allowed=new[]{"NotAvailable","Refused","ClinicalHold","PersonAway","UnableToTake","Other"};if(!allowed.Contains(request.ReasonCode))return BadRequest(new{message="A valid omission/refusal reason code is required."});if(Missing(request.ReasonDetail))return BadRequest(new{message="Omission/refusal detail is required."});}
  if(outcome=="Administered"&&request.DoseQuantity<=0)return BadRequest(new{message="Administered dose quantity must be greater than zero."});
  if(mar.Value.IsPrn&&outcome=="Administered")
  {
   if(Missing(request.PrnIndication)||profile.Value.MaxPrn is null||profile.Value.MinInterval is null||profile.Value.EffectReview is null)return BadRequest(new{message="PRN indication, limits, interval, and effect-review protocol are required."});
   var recent=await RecentPrn(mar.Value.Medication,occurred,token);if(recent.Count>=profile.Value.MaxPrn)return await ConflictBlock(marId,"emar.prn_limit_breach","Maximum PRN doses in 24 hours would be exceeded.",token);if(recent.Last is not null&&(occurred-recent.Last.Value).TotalMinutes<profile.Value.MinInterval)return await ConflictBlock(marId,"emar.prn_interval_breach","Minimum PRN interval has not elapsed.",token);
  }
  var witness=await Witness(request.WitnessUserId,profile.Value.Witness,token);if(witness.Error is not null){await AuditNow(witness.Error.Contains("own",StringComparison.OrdinalIgnoreCase)?"emar.self_witness_rejected":"emar.witness_missing",marId,token);return BadRequest(new{message=witness.Error});}
  if(outcome=="Administered"&&(profile.Value.Stock is null||profile.Value.Stock<request.DoseQuantity))return await ConflictBlock(marId,"emar.stock_shortage","Insufficient reconciled medication stock.",token);
  var id=Guid.NewGuid();var before=profile.Value.Stock;var after=outcome=="Administered"?before-request.DoseQuantity:before;var strategy=db.Database.CreateExecutionStrategy();
  try{await strategy.ExecuteAsync(async()=>{await using var tx=await db.Database.BeginTransactionAsync(token);await Exec("insert into emar_ledger(id,mar_record_id,medication_id,service_user_id,organization_id,branch_id,event_type,outcome,reason_code,reason_detail,prn_indication,dose_quantity,stock_before,stock_after,witness_user_id,witness_name,occurred_at,created_by_user_id,created_by) values(@id,@mar,@medication,@person,@organization,@branch,@event,@outcome,@code,@detail,@prn,@dose,@before,@after,@witness,@witnessName,@occurred,@actorId,@actor)",c=>{Add(c,"id",id);Add(c,"mar",marId);Add(c,"medication",mar.Value.Medication);Add(c,"person",mar.Value.Person);Add(c,"event",outcome=="Administered"?"Administration":outcome=="Omitted"?"Omission":"Refusal");Add(c,"outcome",outcome);Add(c,"code",request.ReasonCode?.Trim()??"");Add(c,"detail",Join(request.ReasonDetail,request.OverrideReason));Add(c,"prn",request.PrnIndication?.Trim()??"");Add(c,"dose",outcome=="Administered"?request.DoseQuantity:null);Add(c,"before",before);Add(c,"after",after);Add(c,"witness",request.WitnessUserId);Add(c,"witnessName",witness.Name);Add(c,"occurred",occurred);},token);if(outcome=="Administered"){await Exec("update medication_safety_profiles set stock_on_hand=@after,updated_at=now() where medication_id=@medication and organization_id=@organization;insert into medication_stock_transactions(id,medication_id,organization_id,branch_id,transaction_type,quantity,balance_before,balance_after,reference,reason,witness_user_id,witness_name,mar_ledger_id,created_by_user_id,created_by) values(@stockId,@medication,@organization,@branch,'Administration',@quantity,@before,@after,@reference,'Dose administered',@witness,@witnessName,@ledger,@actorId,@actor)",c=>{Add(c,"stockId",Guid.NewGuid());Add(c,"medication",mar.Value.Medication);Add(c,"quantity",-request.DoseQuantity);Add(c,"before",before);Add(c,"after",after);Add(c,"reference",marId.ToString());Add(c,"witness",request.WitnessUserId);Add(c,"witnessName",witness.Name);Add(c,"ledger",id);},token);}await Exec("update \"MedicationAdministrationRecords\" set \"AdministeredAt\"=@occurred,\"Outcome\"=@outcome,\"Notes\"=@notes where \"Id\"=@mar and \"Outcome\"='Scheduled'",c=>{Add(c,"occurred",occurred);Add(c,"outcome",outcome);Add(c,"notes",request.ReasonDetail?.Trim()??request.PrnIndication?.Trim()??"");Add(c,"mar",marId);},token);if(outcome!="Administered"||minutes>profile.Value.Window)await CreateEscalation(marId,id,outcome!="Administered"?"MissedDose":"LateDose",outcome=="Refused"?"High":"Medium",outcome!="Administered"?$"{outcome}: {request.ReasonCode} - {request.ReasonDetail}":$"Dose recorded {minutes:0} minutes outside its window.",token);if(mar.Value.IsPrn&&outcome=="Administered")await CreateEscalation(marId,id,"PRNEffectReview","Medium",$"PRN effect review due in {profile.Value.EffectReview} minutes.",token);Audit("emar.governed_outcome_recorded",marId);await db.SaveChangesAsync(token);await tx.CommitAsync(token);});}
  catch(DbUpdateException){return await ConflictBlock(marId,"emar.failed_submission","A terminal MAR outcome already exists.",token);}
  await StoreIdempotentLedger("POST /api/phase1/emar-safety/mar/record",idempotencyKey,id,token);
  return CreatedAtAction(nameof(History),new{marId},new{id,outcome,stockAfter=after,serverRecordedAt=serverNow});
 }

 private bool EmarProductionEnabled()=>configuration.GetValue<bool>("MedicationSafety:EmarProductionEnabled");
 private async Task<IActionResult> ConflictBlock(Guid id,string action,string message,CancellationToken token)=>await Block(id,action,message,StatusCodes.Status409Conflict,token);
 private async Task<IActionResult> Block(Guid id,string action,string message,int status,CancellationToken token){await AuditNow(action,id,token);return StatusCode(status,new{message});}
 private async Task AuditNow(string action,Guid id,CancellationToken token){Audit(action,id);await db.SaveChangesAsync(token);}
 private async Task CreateEscalation(Guid mar,Guid ledger,string type,string severity,string message,CancellationToken token)=>await Exec("insert into emar_escalations(id,mar_record_id,ledger_id,organization_id,branch_id,escalation_type,severity,message,owner) values(@id,@mar,@ledger,@organization,@branch,@type,@severity,@message,'Medication lead')",c=>{Add(c,"id",Guid.NewGuid());Add(c,"mar",mar);Add(c,"ledger",ledger);Add(c,"type",type);Add(c,"severity",severity);Add(c,"message",message);},token);
 private bool CanRecord(Guid worker)=>user.IsAdministrator||user.IsCareManager||user.IsCareCoordinator||(user.IsCareWorker&&user.CareWorkerId==worker);
 private async Task<string?> MedicationAuthorization(Guid worker,string route,CancellationToken t){await using var c=await Command("select status,expires_at from worker_medication_authorizations where care_worker_id=@worker and organization_id=@organization and branch_id=@branch order by created_at desc limit 1",t);Add(c,"worker",worker);await using var r=await c.ExecuteReaderAsync(t);if(await r.ReadAsync(t)){var status=r.GetString(0);var expires=Date(r,1);if(status!="Authorized"||expires is not null&&expires<=DateTimeOffset.UtcNow)return "The assigned worker does not have current medication authorization.";}await r.DisposeAsync();await using var restriction=await Command("select exists(select 1 from worker_assignment_restrictions where care_worker_id=@worker and organization_id=@organization and status='Active' and restriction_type='Medication' and starts_at<=now() and (ends_at is null or ends_at>now()))",t);Add(restriction,"worker",worker);if(Convert.ToBoolean(await restriction.ExecuteScalarAsync(t)))return "The assigned worker has an active medication restriction.";await using var competency=await Command("select exists(select 1 from worker_competency_records where care_worker_id=@worker and organization_id=@organization and branch_id=@branch and status='Valid' and (expires_at is null or expires_at>now()) and (lower(competency)=lower('Medication administration') or lower(competency)=lower(@routeSkill) or lower(competency)=lower(@routeSkillAlt)))",t);Add(competency,"worker",worker);Add(competency,"routeSkill",$"Medication administration - {route}");Add(competency,"routeSkillAlt",$"{route} medication administration");return Convert.ToBoolean(await competency.ExecuteScalarAsync(t))?null:$"Current route-specific medication competency is required for {route} administration.";}
 private async Task<(Guid Medication,Guid Person,Guid Worker,DateTimeOffset Scheduled,string Outcome,bool IsPrn,string Route)?> Mar(Guid id,CancellationToken t){await using var c=await Command("select r.\"MedicationId\",m.\"ServiceUserId\",r.\"CareWorkerId\",r.\"ScheduledAt\",r.\"Outcome\",m.\"IsPrn\",m.\"Route\" from \"MedicationAdministrationRecords\" r join \"Medications\" m on m.\"Id\"=r.\"MedicationId\" where r.\"Id\"=@id and r.\"OrganizationId\"=@organization and r.\"BranchId\"=@branch",t);Add(c,"id",id);await using var r=await c.ExecuteReaderAsync(t);return await r.ReadAsync(t)?(r.GetGuid(0),r.GetGuid(1),r.GetGuid(2),r.GetFieldValue<DateTimeOffset>(3),r.GetString(4),r.GetBoolean(5),r.GetString(6)):null;}
 private async Task<(string Indication,string Prescriber,DateTimeOffset? Start,DateTimeOffset? End,int Window,int? MaxPrn,int? MinInterval,int? EffectReview,decimal? Stock,bool Witness,DateTimeOffset? ReconciledAt,string ReconciledBy,string ReconciliationStatus)?> Profile(Guid id,CancellationToken t){await using var c=await Command("select indication,prescriber,start_date,end_date,dose_window_minutes,max_prn_doses_24h,min_prn_interval_minutes,prn_effect_review_minutes,stock_on_hand,requires_witness,last_reconciled_at,reconciled_by,reconciliation_status from medication_safety_profiles where medication_id=@id and organization_id=@organization and branch_id=@branch",t);Add(c,"id",id);await using var r=await c.ExecuteReaderAsync(t);return await r.ReadAsync(t)?(r.GetString(0),r.GetString(1),Date(r,2),Date(r,3),r.GetInt32(4),Int(r,5),Int(r,6),Int(r,7),Decimal(r,8),r.GetBoolean(9),Date(r,10),r.GetString(11),r.GetString(12)):null;}
 private async Task<(int Count,DateTimeOffset? Last)> RecentPrn(Guid medication,DateTimeOffset at,CancellationToken t){await using var c=await Command("select count(*),max(occurred_at) from emar_ledger where medication_id=@medication and organization_id=@organization and event_type='Administration' and occurred_at>@from and occurred_at<=@at",t);Add(c,"medication",medication);Add(c,"from",at.AddHours(-24));Add(c,"at",at);await using var r=await c.ExecuteReaderAsync(t);await r.ReadAsync(t);return(r.GetInt32(0),r.IsDBNull(1)?null:r.GetFieldValue<DateTimeOffset>(1));}
 private async Task<(string? AllergyConflict,string? DuplicateConflict)> MedicationSafety(Guid medication,Guid person,CancellationToken t){await using var c=await Command("select \"Name\",\"AllergyWarning\" from \"Medications\" where \"Id\"=@id and \"OrganizationId\"=@organization and \"BranchId\"=@branch",t);Add(c,"id",medication);await using var r=await c.ExecuteReaderAsync(t);if(!await r.ReadAsync(t))return("Medication is not accessible.",null);var name=r.GetString(0);var allergy=r.GetString(1);await r.DisposeAsync();if(Missing(allergy))return("Medication allergy status must be confirmed before administration.",null);var normalized=allergy.Trim().ToLowerInvariant();if(normalized is not ("none" or "no known allergies" or "nka" or "no known drug allergies")&&(normalized.Contains(name.ToLowerInvariant(),StringComparison.Ordinal)||name.ToLowerInvariant().Contains(normalized,StringComparison.Ordinal)))return($"Medication conflicts with recorded allergy status: {allergy}.",null);await using var d=await Command("select count(*)::int from \"Medications\" m join medication_safety_profiles p on p.medication_id=m.\"Id\" where m.\"ServiceUserId\"=@person and m.\"OrganizationId\"=@organization and m.\"BranchId\"=@branch and m.\"Id\"<>@id and lower(m.\"Name\")=lower(@name) and p.reconciliation_status='Verified' and (p.end_date is null or p.end_date>now())",t);Add(d,"person",person);Add(d,"id",medication);Add(d,"name",name);var duplicates=Convert.ToInt32(await d.ExecuteScalarAsync(t));return(null,duplicates>0?$"Duplicate active medication requires reconciliation before administration: {name}.":null);}
 private async Task<object?> TryGetIdempotentLedger(string endpoint,string key,CancellationToken t){await using var c=await Command("select resource_id from api_idempotency_keys where organization_id=@organization and actor_user_id=@actorId and endpoint=@endpoint and idempotency_key=@key",t);Add(c,"endpoint",endpoint);Add(c,"key",key.Trim());var value=await c.ExecuteScalarAsync(t);if(value is not Guid id)return null;await using var ledger=await Command("select outcome,stock_after from emar_ledger where id=@id and organization_id=@organization",t);Add(ledger,"id",id);await using var r=await ledger.ExecuteReaderAsync(t);return await r.ReadAsync(t)?new{id,outcome=r.GetString(0),stockAfter=Decimal(r,1),replayed=true}:null;}
 private async Task StoreIdempotentLedger(string endpoint,string key,Guid resource,CancellationToken t){await Exec("insert into api_idempotency_keys(id,organization_id,branch_id,actor_user_id,endpoint,idempotency_key,resource_type,resource_id) values(@id,@organization,@branch,@actorId,@endpoint,@key,'EmarLedger',@resource) on conflict(organization_id,actor_user_id,endpoint,idempotency_key) do nothing",c=>{Add(c,"id",Guid.NewGuid());Add(c,"endpoint",endpoint);Add(c,"key",key.Trim());Add(c,"resource",resource);},t);}
 private async Task<(string Name,string? Error)> Witness(Guid? id,bool required,CancellationToken t){if(id is null)return required?("","A verified witness is required."):("",null);if(id==user.UserId)return("","The administrator cannot witness their own administration.");var witness=await db.AppUsers.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.OrganizationId==tenant.OrganizationId&&x.IsActive,t);return witness is null?("","Witness must be an active user in the same organization."):(witness.UserName,null);}
 private Task<List<object>> Ledger(Guid mar,CancellationToken t)=>Query("select id,event_type,outcome,reason_code,reason_detail,prn_indication,prn_effect,dose_quantity,stock_before,stock_after,witness_name,corrects_ledger_id,occurred_at,created_by,created_at from emar_ledger where mar_record_id=@mar and organization_id=@organization order by created_at",c=>Add(c,"mar",mar),r=>(object)new{id=r.GetGuid(0),eventType=r.GetString(1),outcome=r.GetString(2),reasonCode=r.GetString(3),reasonDetail=r.GetString(4),prnIndication=r.GetString(5),prnEffect=r.GetString(6),doseQuantity=Decimal(r,7),stockBefore=Decimal(r,8),stockAfter=Decimal(r,9),witnessName=r.GetString(10),correctsLedgerId=r.IsDBNull(11)?null:(Guid?)r.GetGuid(11),occurredAt=r.GetFieldValue<DateTimeOffset>(12),createdBy=r.GetString(13),createdAt=r.GetFieldValue<DateTimeOffset>(14)},t);
 private Task<List<object>> Escalations(Guid mar,CancellationToken t)=>Query("select id,escalation_type,severity,status,message,owner,acknowledged_at,acknowledged_by,resolved_at,resolution,created_at from emar_escalations where mar_record_id=@mar and organization_id=@organization order by created_at",c=>Add(c,"mar",mar),r=>(object)new{id=r.GetGuid(0),escalationType=r.GetString(1),severity=r.GetString(2),status=r.GetString(3),message=r.GetString(4),owner=r.GetString(5),acknowledgedAt=Date(r,6),acknowledgedBy=r.GetString(7),resolvedAt=Date(r,8),resolution=r.GetString(9),createdAt=r.GetFieldValue<DateTimeOffset>(10)},t);
 private void Audit(string action,Guid id)=>db.AuditEvents.Add(new AuditEvent(Guid.NewGuid(),action,user.UserName,"MedicationAdministrationRecord",id,DateTimeOffset.UtcNow,tenant.OrganizationId,tenant.BranchId??TenantDefaults.BranchId));private static bool Missing(params string?[] v)=>v.Any(string.IsNullOrWhiteSpace);private static string Join(string? a,string? b)=>string.Join(" | ",new[]{a,b}.Where(x=>!string.IsNullOrWhiteSpace(x)).Select(x=>x!.Trim()));
 private async Task<int> Exec(string sql,Action<DbCommand> bind,CancellationToken t){await using var c=await Command(sql,t);bind(c);return await c.ExecuteNonQueryAsync(t);}private async Task<DbCommand> Command(string sql,CancellationToken t){var connection=db.Database.GetDbConnection();if(connection.State!=ConnectionState.Open)await connection.OpenAsync(t);var c=connection.CreateCommand();c.CommandText=sql;Add(c,"organization",tenant.OrganizationId);Add(c,"branch",tenant.BranchId??TenantDefaults.BranchId);Add(c,"actor",user.UserName);Add(c,"actorId",user.UserId);return c;}private async Task<List<T>> Query<T>(string sql,Action<DbCommand> bind,Func<DbDataReader,T> map,CancellationToken t){await using var c=await Command(sql,t);bind(c);await using var r=await c.ExecuteReaderAsync(t);var list=new List<T>();while(await r.ReadAsync(t))list.Add(map(r));return list;}private static void Add(DbCommand c,string n,object? v){var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}private static DateTimeOffset? Date(DbDataReader r,int i)=>r.IsDBNull(i)?null:r.GetFieldValue<DateTimeOffset>(i);private static int? Int(DbDataReader r,int i)=>r.IsDBNull(i)?null:r.GetInt32(i);private static decimal? Decimal(DbDataReader r,int i)=>r.IsDBNull(i)?null:r.GetDecimal(i);
}

public sealed record EmarRecordRequest(string Outcome,DateTimeOffset? OccurredAt,decimal DoseQuantity,string? ReasonCode,string? ReasonDetail,string? PrnIndication,Guid? WitnessUserId,string? OverrideReason);
