using System.Data;using System.Data.Common;using AiCare.Application;using AiCare.Domain;using AiCare.Infrastructure;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Storage;
namespace AiCare.Api;
[ApiController,Authorize(Policy="Phase1User")][Route("api/phase1/finance/workforce-claims")]
public sealed class WorkforceFinanceController(CareDbContext db,ITenantContext tenant,ICurrentUserContext user):ControllerBase
{
 Guid Branch=>tenant.BranchId??TenantDefaults.BranchId;bool Review=>user.IsAdministrator||user.IsBackOffice||user.IsCareManager;
 [HttpGet]public async Task<IActionResult>List([FromQuery]string?status,CancellationToken t){if(!Review&&!user.IsCareWorker)return Forbid();return Ok(await Rows("select id,care_worker_id,visit_id,claim_type,claim_date,quantity,unit_rate,amount,category,notes,evidence_reference,status from finance_workforce_claims where organization_id=@org and (@wide or branch_id=@branch) and (@review or care_worker_id=@worker) and (coalesce(@status,'')='' or status=@status) order by claim_date desc",c=>{Add(c,"review",Review);Add(c,"worker",user.CareWorkerId??Guid.Empty);Add(c,"status",status??"");},t));}
 [HttpPost]public async Task<IActionResult>Create(WorkforceClaimRequest r,CancellationToken t){if(user.CareWorkerId is null&&!Review)return Forbid();var worker=r.CareWorkerId??user.CareWorkerId;if(worker is null)return BadRequest(new{message="Care worker is required."});if(!Review&&worker!=user.CareWorkerId)return Forbid();if(r.ClaimType is not ("Mileage" or "Expense")||r.Quantity<0||r.UnitRate<0||string.IsNullOrWhiteSpace(r.Notes))return BadRequest(new{message="Valid claim type, nonnegative values, and notes are required."});if(!await db.CareWorkers.AnyAsync(x=>x.Id==worker&&x.OrganizationId==tenant.OrganizationId&&(tenant.IsOrganizationWide||x.BranchId==tenant.BranchId),t))return NotFound();var amount=Math.Round(r.Quantity*r.UnitRate,2,MidpointRounding.AwayFromZero);var id=Guid.NewGuid();await Exec("insert into finance_workforce_claims(id,organization_id,branch_id,care_worker_id,visit_id,claim_type,claim_date,quantity,unit_rate,amount,category,notes,evidence_reference,submitted_by) values(@id,@org,@branch,@worker,@visit,@type,@date,@quantity,@rate,@amount,@category,@notes,@evidence,@actor)",c=>{Add(c,"id",id);Add(c,"worker",worker);Add(c,"visit",r.VisitId);Add(c,"type",r.ClaimType);Add(c,"date",r.ClaimDate);Add(c,"quantity",r.Quantity);Add(c,"rate",r.UnitRate);Add(c,"amount",amount);Add(c,"category",r.Category??"");Add(c,"notes",r.Notes.Trim());Add(c,"evidence",r.EvidenceReference??"");},t);Audit("WORKFORCE_CLAIM_SUBMITTED",id);await db.SaveChangesAsync(t);return Created($"/api/phase1/finance/workforce-claims/{id}",new{id,amount,status="Submitted"});}
 [HttpPost("{id:guid}/review")]public async Task<IActionResult>ReviewClaim(Guid id,ReviewClaimRequest r,CancellationToken t){if(!Review)return Forbid();if(r.Decision is not ("Approve" or "Reject")||string.IsNullOrWhiteSpace(r.Reason))return BadRequest(new{message="Approve/Reject decision and reason are required."});var status=r.Decision=="Approve"?"Approved":"Rejected";var changed=await Exec("update finance_workforce_claims set status=@status,reviewed_by=@actor,reviewed_at=now(),review_reason=@reason where id=@id and organization_id=@org and (@wide or branch_id=@branch) and status='Submitted'",c=>{Add(c,"id",id);Add(c,"status",status);Add(c,"reason",r.Reason.Trim());},t);if(changed==0)return Conflict(new{message="Only submitted claims can be reviewed."});Audit(status=="Approved"?"WORKFORCE_CLAIM_APPROVED":"WORKFORCE_CLAIM_REJECTED",id);await db.SaveChangesAsync(t);return NoContent();}
 async Task<List<Dictionary<string,object?>>>Rows(string s,Action<DbCommand>b,CancellationToken t){var a=new List<Dictionary<string,object?>>();await using var c=await Cmd(s,t);b(c);await using var r=await c.ExecuteReaderAsync(t);while(await r.ReadAsync(t)){var d=new Dictionary<string,object?>();for(var i=0;i<r.FieldCount;i++)d[r.GetName(i)]=r.IsDBNull(i)?null:r.GetValue(i);a.Add(d);}return a;}async Task<int>Exec(string s,Action<DbCommand>b,CancellationToken t){await using var c=await Cmd(s,t);b(c);return await c.ExecuteNonQueryAsync(t);}async Task<DbCommand>Cmd(string s,CancellationToken t){var n=db.Database.GetDbConnection();if(n.State!=ConnectionState.Open)await n.OpenAsync(t);var c=n.CreateCommand();c.Transaction=db.Database.CurrentTransaction?.GetDbTransaction();c.CommandText=s;Add(c,"org",tenant.OrganizationId);Add(c,"branch",Branch);Add(c,"wide",tenant.IsOrganizationWide);Add(c,"actor",user.UserName);return c;}static void Add(DbCommand c,string n,object?v){if(c.Parameters.Contains(n))return;var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}void Audit(string a,Guid id)=>db.AuditEvents.Add(new AuditEvent(Guid.NewGuid(),a,user.UserName,"WorkforceClaim",id,DateTimeOffset.UtcNow,tenant.OrganizationId,Branch));
}
public sealed record WorkforceClaimRequest(Guid? CareWorkerId,Guid? VisitId,string ClaimType,DateOnly ClaimDate,decimal Quantity,decimal UnitRate,string? Category,string Notes,string? EvidenceReference);public sealed record ReviewClaimRequest(string Decision,string Reason);
