using System.Data;
using System.Data.Common;
using AiCare.Application;
using AiCare.Domain;
using AiCare.Infrastructure;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AiCare.Api;

[ApiController]
[Authorize(Policy="Phase1User")]
[Route("api/phase1/workforce-development")]
public sealed class WorkforceDevelopmentController(CareDbContext db,ITenantContext tenant,ICurrentUserContext user):ControllerBase
{
    [HttpGet("care-workers/{workerId:guid}")]
    public async Task<IActionResult> Workspace(Guid workerId,CancellationToken t)
    {
        if(!CanRead(workerId)||!await Worker(workerId,t))return NotFound();
        var recruitment=await Rows("select id,status,application_reference,applied_at,interview_at,interview_outcome,identity_status,right_to_work_status,dbs_status,health_declaration_status,onboarding_status,owner,decision_reason,decided_by,decided_at from worker_recruitment_cases where care_worker_id=@worker and organization_id=@organization and branch_id=@branch",workerId,t);
        var references=recruitment.Count==0?[]:await Rows("select r.id,r.referee_name,r.relationship,r.requested_at,r.received_at,r.outcome,r.evidence_reference from worker_recruitment_references r join worker_recruitment_cases c on c.id=r.recruitment_case_id where c.care_worker_id=@worker and r.organization_id=@organization order by r.requested_at desc",workerId,t);
        var courses=await Rows("select id,code,title,category,provider,validity_months,is_mandatory,active,description from training_catalogue_courses where organization_id=@organization and active=true and (branch_id is null or branch_id=@branch) order by is_mandatory desc,title",workerId,t);
        var bookings=await Rows("select b.id,b.course_id,c.code,c.title,c.category,b.scheduled_at,b.status,b.completion_evidence,b.completed_at,b.expires_at from worker_training_bookings b join training_catalogue_courses c on c.id=b.course_id where b.care_worker_id=@worker and b.organization_id=@organization and b.branch_id=@branch order by b.scheduled_at desc",workerId,t);
        var probation=await Rows("select id,review_at,reviewer,outcome,objectives,evidence_reference,extension_until,completed_at from worker_probation_reviews where care_worker_id=@worker and organization_id=@organization and branch_id=@branch order by review_at desc",workerId,t);
        return Ok(new{careWorkerId=workerId,recruitment=recruitment.FirstOrDefault(),references,courses,bookings,probation,alerts=Alerts(courses,bookings,recruitment.FirstOrDefault())});
    }

    [HttpPut("care-workers/{workerId:guid}/recruitment")]
    [Authorize(Roles="CareManager,Administrator")]
    public async Task<IActionResult> Recruitment(Guid workerId,RecruitmentRequest request,CancellationToken t)
    {
        if(!await Worker(workerId,t))return NotFound();var allowed=new[]{"Application","Interview","ConditionalOffer","Onboarding","Cleared","Rejected","Withdrawn"};if(!allowed.Contains(request.Status)||string.IsNullOrWhiteSpace(request.ApplicationReference))return BadRequest(new{message="A valid status and application reference are required."});
        if(request.Status=="Cleared"&&(request.IdentityStatus!="Verified"||request.RightToWorkStatus!="Verified"||request.DbsStatus!="Verified"||request.HealthDeclarationStatus!="Cleared"||request.OnboardingStatus!="Completed"))return BadRequest(new{message="Identity, right-to-work, DBS, health declaration and onboarding must be cleared first."});
        if(request.Status is "Rejected" or "Withdrawn"&&string.IsNullOrWhiteSpace(request.DecisionReason))return BadRequest(new{message="A decision reason is required."});
        var id=Guid.NewGuid();await Exec("""insert into worker_recruitment_cases(id,care_worker_id,organization_id,branch_id,status,application_reference,applied_at,interview_at,interview_outcome,identity_status,right_to_work_status,dbs_status,health_declaration_status,onboarding_status,owner,decision_reason,decided_by,decided_at) values(@id,@worker,@organization,@branch,@status,@reference,@applied,@interview,@interviewOutcome,@identity,@rtw,@dbs,@health,@onboarding,@owner,@reason,@actor,case when @status in ('Cleared','Rejected','Withdrawn') then now() else null end) on conflict(care_worker_id) do update set status=@status,application_reference=@reference,applied_at=@applied,interview_at=@interview,interview_outcome=@interviewOutcome,identity_status=@identity,right_to_work_status=@rtw,dbs_status=@dbs,health_declaration_status=@health,onboarding_status=@onboarding,owner=@owner,decision_reason=@reason,decided_by=@actor,decided_at=case when @status in ('Cleared','Rejected','Withdrawn') then now() else null end,updated_at=now()""",workerId,c=>{Add(c,"id",id);Add(c,"status",request.Status);Add(c,"reference",request.ApplicationReference.Trim());Add(c,"applied",request.AppliedAt);Add(c,"interview",request.InterviewAt);Add(c,"interviewOutcome",request.InterviewOutcome);Add(c,"identity",request.IdentityStatus);Add(c,"rtw",request.RightToWorkStatus);Add(c,"dbs",request.DbsStatus);Add(c,"health",request.HealthDeclarationStatus);Add(c,"onboarding",request.OnboardingStatus);Add(c,"owner",request.Owner);Add(c,"reason",request.DecisionReason);},t);await Audit("recruitment.updated","WorkerRecruitment",workerId,t);return Ok(new{message="Recruitment case updated."});
    }

    [HttpPost("care-workers/{workerId:guid}/references")]
    [Authorize(Roles="CareCoordinator,CareManager,Administrator")]
    public async Task<IActionResult> Reference(Guid workerId,ReferenceRequest request,CancellationToken t)
    {if(!await Worker(workerId,t))return NotFound();if(string.IsNullOrWhiteSpace(request.RefereeName))return BadRequest(new{message="Referee name is required."});var caseId=await ScalarGuid("select id from worker_recruitment_cases where care_worker_id=@worker and organization_id=@organization",workerId,t);if(caseId is null)return Conflict(new{message="Create the recruitment case before recording references."});if(request.Outcome!="Pending"&&string.IsNullOrWhiteSpace(request.EvidenceReference))return BadRequest(new{message="Received references require evidence."});var id=Guid.NewGuid();await Exec("insert into worker_recruitment_references(id,recruitment_case_id,organization_id,referee_name,relationship,requested_at,received_at,outcome,evidence_reference) values(@id,@case,@organization,@name,@relationship,@requested,@received,@outcome,@evidence)",workerId,c=>{Add(c,"id",id);Add(c,"case",caseId);Add(c,"name",request.RefereeName);Add(c,"relationship",request.Relationship);Add(c,"requested",request.RequestedAt);Add(c,"received",request.ReceivedAt);Add(c,"outcome",request.Outcome);Add(c,"evidence",request.EvidenceReference);},t);await Audit("recruitment.reference_recorded","RecruitmentReference",id,t);return Created("",new{id});}

    [HttpPost("courses")]
    [Authorize(Roles="CareManager,Administrator")]
    public async Task<IActionResult> Course(CourseRequest request,CancellationToken t)
    {if(string.IsNullOrWhiteSpace(request.Code)||string.IsNullOrWhiteSpace(request.Title)||request.ValidityMonths is <=0)return BadRequest(new{message="Course code, title and a valid renewal period are required."});var id=Guid.NewGuid();try{await Exec("insert into training_catalogue_courses(id,organization_id,branch_id,code,title,category,provider,validity_months,is_mandatory,active,description) values(@id,@organization,@courseBranch,@code,@title,@category,@provider,@validity,@mandatory,true,@description)",Guid.Empty,c=>{Add(c,"id",id);Add(c,"courseBranch",request.OrganizationWide?null:tenant.BranchId??TenantDefaults.BranchId);Add(c,"code",request.Code.Trim());Add(c,"title",request.Title.Trim());Add(c,"category",request.Category);Add(c,"provider",request.Provider);Add(c,"validity",request.ValidityMonths);Add(c,"mandatory",request.IsMandatory);Add(c,"description",request.Description);},t);}catch(DbException){return Conflict(new{message="Course code already exists."});}await Audit("training.course_created","TrainingCourse",id,t);return Created("",new{id});}

    [HttpPost("care-workers/{workerId:guid}/bookings")]
    [Authorize(Roles="CareCoordinator,CareManager,Administrator")]
    public async Task<IActionResult> Book(Guid workerId,BookingRequest request,CancellationToken t)
    {if(!await Worker(workerId,t))return NotFound();if(request.ScheduledAt<=DateTimeOffset.UtcNow.AddMinutes(-5))return BadRequest(new{message="Training must be booked for a future time."});var course=await ScalarGuid("select id from training_catalogue_courses where id=@course and organization_id=@organization and active=true and (branch_id is null or branch_id=@branch)",workerId,t,c=>Add(c,"course",request.CourseId));if(course is null)return BadRequest(new{message="Course is not available in this branch."});var id=Guid.NewGuid();await Exec("insert into worker_training_bookings(id,course_id,care_worker_id,organization_id,branch_id,scheduled_at,status,booked_by) values(@id,@course,@worker,@organization,@branch,@scheduled,'Booked',@actor)",workerId,c=>{Add(c,"id",id);Add(c,"course",request.CourseId);Add(c,"scheduled",request.ScheduledAt);},t);await Audit("training.booking_created","TrainingBooking",id,t);return Created("",new{id});}

    [HttpPost("care-workers/{workerId:guid}/bookings/{id:guid}/complete")]
    [Authorize(Roles="CareManager,Administrator")]
    public async Task<IActionResult> Complete(Guid workerId,Guid id,CompleteBookingRequest request,CancellationToken t)
    {if(!await Worker(workerId,t))return NotFound();if(request.CompletedAt>DateTimeOffset.UtcNow.AddMinutes(5)||string.IsNullOrWhiteSpace(request.EvidenceReference))return BadRequest(new{message="Completion time and evidence are required."});await using var command=await Command("select c.title,c.category,c.provider,c.validity_months from worker_training_bookings b join training_catalogue_courses c on c.id=b.course_id where b.id=@id and b.care_worker_id=@worker and b.organization_id=@organization and b.branch_id=@branch and b.status in ('Booked','Attended')",workerId,t);Add(command,"id",id);await using var reader=await command.ExecuteReaderAsync(t);if(!await reader.ReadAsync(t))return Conflict(new{message="Only a current booking can be completed."});var title=reader.GetString(0);var category=reader.GetString(1);var provider=reader.GetString(2);var months=reader.IsDBNull(3)?(int?)null:reader.GetInt32(3);await reader.DisposeAsync();var expires=months is null?(DateTimeOffset?)null:request.CompletedAt.AddMonths(months.Value);
        await Exec("update worker_training_bookings set status='Completed',completion_evidence=@evidence,completed_at=@completed,expires_at=@expires where id=@id and care_worker_id=@worker",workerId,c=>{Add(c,"id",id);Add(c,"evidence",request.EvidenceReference);Add(c,"completed",request.CompletedAt);Add(c,"expires",expires);},t);var record=Guid.NewGuid();await Exec("insert into worker_training_records(id,care_worker_id,organization_id,branch_id,course_name,category,provider,certificate_reference,completed_at,expires_at,status,created_at) values(@id,@worker,@organization,@branch,@title,@category,@provider,@evidence,@completed,@expires,'Valid',now())",workerId,c=>{Add(c,"id",record);Add(c,"title",title);Add(c,"category",category);Add(c,"provider",provider);Add(c,"evidence",request.EvidenceReference);Add(c,"completed",request.CompletedAt);Add(c,"expires",expires);},t);await Audit("training.booking_completed","TrainingBooking",id,t);return Ok(new{id,expiresAt=expires});}

    [HttpPost("care-workers/{workerId:guid}/probation")]
    [Authorize(Roles="CareManager,Administrator")]
    public async Task<IActionResult> Probation(Guid workerId,ProbationRequest request,CancellationToken t)
    {if(!await Worker(workerId,t))return NotFound();if(request.Outcome is not ("Passed" or "Extended" or "Failed")||string.IsNullOrWhiteSpace(request.EvidenceReference)||request.Outcome=="Extended"&&request.ExtensionUntil is null)return BadRequest(new{message="Outcome, evidence and an extension date when extended are required."});var id=Guid.NewGuid();await Exec("insert into worker_probation_reviews(id,care_worker_id,organization_id,branch_id,review_at,reviewer,outcome,objectives,evidence_reference,extension_until) values(@id,@worker,@organization,@branch,@review,@actor,@outcome,@objectives,@evidence,@extension)",workerId,c=>{Add(c,"id",id);Add(c,"review",request.ReviewAt);Add(c,"outcome",request.Outcome);Add(c,"objectives",request.Objectives);Add(c,"evidence",request.EvidenceReference);Add(c,"extension",request.ExtensionUntil);},t);await Audit("probation.review_completed","ProbationReview",id,t);return Created("",new{id});}

    private bool CanRead(Guid id)=>user.IsBackOffice||user.IsAdministrator||user.IsCareManager||user.IsCareCoordinator||(user.IsCareWorker&&user.CareWorkerId==id);private Task<bool> Worker(Guid id,CancellationToken t)=>db.CareWorkers.AnyAsync(x=>x.Id==id&&x.OrganizationId==tenant.OrganizationId&&(tenant.IsOrganizationWide||x.BranchId==tenant.BranchId),t);
    private static object[] Alerts(List<Dictionary<string,object?>> courses,List<Dictionary<string,object?>> bookings,Dictionary<string,object?>? recruitment){var now=DateTimeOffset.UtcNow;var completed=bookings.Where(x=>x["status"]?.ToString()=="Completed").Select(x=>x["courseId"]).ToHashSet();var missing=courses.Where(x=>x["isMandatory"] is true&&!completed.Contains(x["id"])).Select(x=>(object)new{type="MandatoryTrainingMissing",message=$"Mandatory course {x["title"]} requires completion."});var renewal=bookings.Where(x=>x["expiresAt"] is DateTimeOffset expiry&&expiry<=now.AddDays(30)).Select(x=>(object)new{type="TrainingRenewalDue",message=$"{x["title"]} expires within 30 days."});var onboarding=recruitment is not null&&recruitment["status"]?.ToString()!="Cleared"?new object[]{new{type="RecruitmentIncomplete",message="Recruitment and onboarding are not cleared."}}:Array.Empty<object>();return missing.Concat(renewal).Concat(onboarding).ToArray();}
    private async Task<List<Dictionary<string,object?>>> Rows(string sql,Guid worker,CancellationToken t){var list=new List<Dictionary<string,object?>>();await using var c=await Command(sql,worker,t);await using var r=await c.ExecuteReaderAsync(t);while(await r.ReadAsync(t)){var row=new Dictionary<string,object?>();for(var i=0;i<r.FieldCount;i++)row[Camel(r.GetName(i))]=r.IsDBNull(i)?null:r.GetValue(i);list.Add(row);}return list;}
    private async Task<Guid?> ScalarGuid(string sql,Guid worker,CancellationToken t,Action<DbCommand>? bind=null){await using var c=await Command(sql,worker,t);bind?.Invoke(c);var value=await c.ExecuteScalarAsync(t);return value is Guid id?id:null;}
    private async Task<int> Exec(string sql,Guid worker,Action<DbCommand> bind,CancellationToken t){await using var c=await Command(sql,worker,t);bind(c);return await c.ExecuteNonQueryAsync(t);}private async Task<DbCommand> Command(string sql,Guid worker,CancellationToken t){var connection=db.Database.GetDbConnection();if(connection.State!=ConnectionState.Open)await connection.OpenAsync(t);var c=connection.CreateCommand();c.CommandText=sql;Add(c,"worker",worker);Add(c,"organization",tenant.OrganizationId);Add(c,"branch",tenant.BranchId??TenantDefaults.BranchId);Add(c,"actor",user.UserName);return c;}private async Task Audit(string action,string entity,Guid id,CancellationToken t){db.AuditEvents.Add(new AuditEvent(Guid.NewGuid(),action,user.UserName,entity,id,DateTimeOffset.UtcNow,tenant.OrganizationId,tenant.BranchId??TenantDefaults.BranchId));await db.SaveChangesAsync(t);}private static void Add(DbCommand c,string n,object? v){if(c.Parameters.Contains(n))return;var p=c.CreateParameter();p.ParameterName=n;p.Value=v??DBNull.Value;c.Parameters.Add(p);}private static string Camel(string value){var parts=value.Split('_');return parts[0]+string.Concat(parts.Skip(1).Select(x=>char.ToUpperInvariant(x[0])+x[1..]));}
}

public sealed record RecruitmentRequest(string Status,string ApplicationReference,DateTimeOffset AppliedAt,DateTimeOffset? InterviewAt,string InterviewOutcome,string IdentityStatus,string RightToWorkStatus,string DbsStatus,string HealthDeclarationStatus,string OnboardingStatus,string Owner,string DecisionReason);
public sealed record ReferenceRequest(string RefereeName,string Relationship,DateTimeOffset RequestedAt,DateTimeOffset? ReceivedAt,string Outcome,string EvidenceReference);
public sealed record CourseRequest(string Code,string Title,string Category,string Provider,int? ValidityMonths,bool IsMandatory,bool OrganizationWide,string Description);
public sealed record BookingRequest(Guid CourseId,DateTimeOffset ScheduledAt);
public sealed record CompleteBookingRequest(DateTimeOffset CompletedAt,string EvidenceReference);
public sealed record ProbationRequest(DateTimeOffset ReviewAt,string Outcome,string Objectives,string EvidenceReference,DateOnly? ExtensionUntil);
